### ISSUE TITLE
Tools BLEService

### ISSUE THREAD

**Issue by JuPrgn** [espressif/esp-at#112]
EDIT : I successfully created the pull request (I was missing the fork step) but I can only pull to master and this is not working yet so I closed it and I would need some help to finish fixing this.

Hi 
I am using python 3.6.5 and BLEService.py is not working on python 3.x.

I have a local clone from your repo with a new branch and a commit that fix the followings errors : 

Fix error using python 3.x :

- Add parenthesis for print function
- except standarderror, e -> except Exception as e
- python3 "unicode" doesn't exist anymore but all string are unicode -> str

I also changed the csv file open from mode "rb" to "r" because I had error : iterator should return strings, not bytes.

Script is still not working I get :

esp32-at\tools>python BLEService.py GattServiceExample.csv
b'index'

And there is no BIN output file on the folder. This is maybe caused by opening file as text and not as binary ?

**Comment by xcguang** [comment]
Please try it again, my python version is `Python 3.8.0`, it works well.

**Comment by xcguang** [comment]
I will close this issue firstly, if have any question, please reopen it again.
