### ISSUE TITLE
[Question] Is there a way to Disable Radios by Default

### ISSUE THREAD

**Issue by WanaGo** [espressif/esp-at#144]
Hello,

Is there a way with the AT command set to have the ESP32 PICO D4 have its radios disabled by default, so when power is applied its sitting there in a minimal power state, until such a time that the AT commands are issued to it to enable the Radios?

We had a considerable current draw with our device at startup and we are trying to lower the power usage of everything so then we can enable only the parts we need to be enabled at run time. So far we have managed this with most parts of the design, but we have not found a way yet to do it with the AT command set on the ESP32 PICO.

One option is to tie the EN line from ESP32 to the processor, however until the processor is started up, the ESP32 would still be enabled unless we change the pull-up arrangement on that line, which we are unsure of the consequence with programming at this stage. So a software approach might be a better solution.

Is there something in the menuconfig which allows for such behaviour, things being disabled by default rather than enabled?

AT+SLEEP=1
AT+CWMODE=0
AT+BLEINIT=0
for example.

Thanks

**Comment by WanaGo** [comment]
Bump.

**Comment by WanaGo** [comment]
Bump.....

**Comment by xcguang** [comment]
Hi, 
Sorry, the default firmware is enabled
