### ISSUE TITLE
SDIO AT Command

### ISSUE THREAD

**Issue by sathishgkg** [espressif/esp-at#156]
Hi, 
IS there any pin configuration for sdio at communication between master and salve.

**Comment by xcguang** [comment]
Hi,
Slave configuration:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/25979965/51097535-ddfdae00-17ff-11e9-85b7-a2efb4e6eba4.png">

master pin is the same as slave.

https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/api-reference/peripherals/sd_pullup_requirements.html maybe is helpful for you.

We test the project on our internal test board, the schematic is 
[SCH_ESP-SDIO-TESTBOARD_V1.pdf](https://github.com/espressif/esp32-at/files/2754095/SCH_ESP-SDIO-TESTBOARD_V1.pdf)

**Comment by sathishgkg** [comment]
![at_sdio](https://user-images.githubusercontent.com/21238821/51099030-3e86ee00-17f4-11e9-891f-d5b5ed6641a9.png)
im not able to see the window which you mentioned above

**Comment by sathishgkg** [comment]
Hi,
After successful flash at command firmware for sdio: in make monitor I'm getting this error
E (760) SDIO-AT: Cannot get read data address.

**Comment by sathishgkg** [comment]
Hi, 
im trying to interface esp32(At command - SDIO) with rx65n using sdio protocol, in monitor it print like  E (760) SDIO-AT: Cannot get read data address.  how to solve this issue?

Thanks
Regards
Sathish

**Comment by xcguang** [comment]
Hi,
Could you read the data, when master sends data?
Maybe this log level should not be ESP_LOGE in `at_sdio_read_data `, we will change it to ESP_LOGI.
If you always can not get the data, can you capture the SDIO bus raw data?

**Comment by ESP-Coco** [comment]
Can you provide the corresponding log for us to analyze?
