### ISSUE TITLE
AT+BLEGATTCWR execution problem

### ISSUE THREAD

**Issue by kmakhil90** [espressif/esp-at#161]
Hi,

I am trying to write a characteristic RACP under service Glucose from an ESP gattclient to ESP gattserver, but there is no WRITE status in my server side. If i try the same write from nrf app (Client) to ESP server it shows a proper write status with data. May i know anybody having solution to solve this?

![esp client_write](https://user-images.githubusercontent.com/14888670/51319709-cd5d6a00-1a83-11e9-93c0-19597c986249.jpg)
![nrf client_write](https://user-images.githubusercontent.com/14888670/51319710-cdf60080-1a83-11e9-856f-de9109495c06.jpg)

**Comment by xiewenxiang** [comment]
If use ESP32 AT Client write data to the characteristic, The data will be written exactly as it was written.

If use ESP32 AT Client write data to the descriptor(UUID: 0x2902), the data inputed by the user will be ignored. If the characteristic is notification, will write 0x01 to the  remote device, if the characteristic is indication, will write 0x02 to the remote device.

**Comment by kmakhil90** [comment]
Hi,
 Now I added one more characteristics with read and write property and tried to write some data by using AT+BLEGATTCWR=0,3,2,,3 (3 bytes) from TERMITE terminal. But after getting OK message, i have  read the same characteristics and not showing  the valid data here. it means the command not writing the data to the characteristic.
Any suggestions to solve the problem?

**Comment by xiewenxiang** [comment]
Do you mean that the client writes data to the server, but the server doesn't have a log?

**Comment by kmakhil90** [comment]
> Do you mean that the client writes data to the server, but the server doesn't have a log?

Yes, When i write from an ESP32 client not getting any indication in esp32 server as log. But if i try with nRF app as client it shows a WRITE indication in esp32 server log and written the data. 
(The snapshots attached above in this discussion).

**Comment by kmakhil90** [comment]
> But I saw the prompt in your screenshot....
> 
> `+WRITE:<conn_index>,<service_index>,<char_index>,<desc_index>,<length>,<data>`

This message received when we write data from nRF app (Client) and not from ESP32.

**Comment by xiewenxiang** [comment]
The first image should be ESP32 client writing data to server, write ccc is still correct, but write char don't have log. I think it is because the data length is big than attribute value.

1.  which version of AT do you used?
2. Do you using the default service bin? If not, please provide the service bin which you are used.
3. Please try `AT+BLEGATTCWR=0,3,1,,2`

**Comment by d-kato** [comment]
@xiewenxiang, I have the same problem. I am using "ESP32 AT Bin V1.1.3".
It seems that "AT+BLEGATTCWR" does not work properly when the property of the characteristic is **"read-write (0x0a)"**.
```
AT+BLEGATTCPRIMSRV=0
+BLEGATTCPRIMSRV:0,1,0x1801,1
+BLEGATTCPRIMSRV:0,2,0x1800,1
+BLEGATTCPRIMSRV:0,3,0xA000,1

OK
AT+BLEGATTCCHAR=0,3
+BLEGATTCCHAR:"char",0,3,1,0xA001,0x0a
```

If the property of the characteristic is **"write (0x08)"**, it seems to work properly.
```
AT+BLEGATTCPRIMSRV=0
+BLEGATTCPRIMSRV:0,1,0x1801,1
+BLEGATTCPRIMSRV:0,2,0x1800,1
+BLEGATTCPRIMSRV:0,3,0xA000,1

OK
AT+BLEGATTCCHAR=0,3
+BLEGATTCCHAR:"char",0,3,1,0xA001,0x08
```

**Comment by xcguang** [comment]
Can you try the latest master branch?

**Comment by xiewenxiang** [comment]
@d-kato 
If you still have similar problems, please provide your custom service table and reopen an issue.

**Comment by xiewenxiang** [comment]
Please use the latest master branch or release/v2.0
