### ISSUE TITLE
AT+BLECONN ERROR : OR +BLECONN:65535,-1

### ISSUE THREAD

**Issue by mxwang101** [espressif/esp-at#166]
AT+RST

OK

ready
AT+BLEINIT=1

OK
AT+BLECONN=0,"47:76:c6:50:bd:07"

ERROR
+BLECONN:65535,-1

what is +BLECONN:65535,-1????

Old ven never see it? how to fix?

**Comment by xiewenxiang** [comment]
Please provide the version information  `AT+GMR`

**Comment by mxwang101** [comment]
AT+GMR

AT version:1.3.0.0-dev(872c8d8 - Jan 22 2019 06:24:15)

SDK version:v3.3-beta1

compile time:Jan 24 2019 15:09:33

 

OK

 

AT+BLEINIT=1

 

OK

AT+BLECONN=0,"ea:9f:d2:ac:c7:8d"

 

ERROR

+BLECONN:65535,-1

 

[0;31mE (40026) BLE_AT_GATTC: connection failed, status = 133, app_handler_index = 0[0

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 xiewenxiang
发送时间: 2019年1月24日 16:51
收件人: espressif/esp32-at
抄送: mxwang101; Author
主题: Re: [espressif/esp32-at] AT+BLECONN ERROR : OR +BLECONN:65535,-1 (#166)

 

Please provide the version information AT+GMR

**Comment by mxwang101** [comment]
This old version:1.0.b1.0 OK:

 

AT+GMR

AT version:1.0.b1.0(1e9060d - Aug 25 2017 10:37:43)

SDK version:v2.1-2-g7138fb02-dirty

compile time: Jan 24 2019 19:58:43

OK

 

AT+BLEINIT=1

 

OK

 

AT+BLECONN=0,"ea:9f:d2:ac:c7:8d"

 

OK

+BLECONN:0,"ea:9f:d2:ac:c7:8d"

 

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 xiewenxiang
发送时间: 2019年1月24日 16:51
收件人: espressif/esp32-at
抄送: mxwang101; Author
主题: Re: [espressif/esp32-at] AT+BLECONN ERROR : OR +BLECONN:65535,-1 (#166)

 

Please provide the version information AT+GMR

**Comment by mxwang101** [comment]
AT+GMR

AT version:1.3.0.0-dev(872c8d8 - Jan 22 2019 06:24:15)

SDK version:v3.3-beta1

compile time:Jan 24 2019 15:09:33

**Comment by mxwang101** [comment]
any fix info?

**Comment by alexdecei** [comment]
Hi, I got the same issue, with the 1.2 AT version (June 2019)

Also, I get :

```
AT+BLECONN=0,"7d:f9:87:75:e4:63"
+BLECONN:0,-1

ERROR
```

In other words, I can't connect to any device.

**Comment by xiewenxiang** [comment]
First scan to see if the device is sending a connectable broadcast packet

In addition，check the address type, and if it's a random address, you need to add optional parameters

```
AT+BLECONN=0,"7d:f9:87:75:e4:63",1
```

**Comment by alexdecei** [comment]
For a static (not random) adress, I get sometimes:

> AT+BLECONN=0,"d4:ca:6e:b6:ef:57"
> 
> ERROR

That happen when I try just before to connect to a busy periferical or when the periferical rejected the connection.  
To fix that, I must reset the esp with` AT+RST`.   

Is there any clean solution ? Other than reseting the chip I mean.

Thanks

**Comment by FayeY** [comment]
Since this is an old issue, I'm going to close it. If the issue persists with the latest esp-at, please feel free to reopen the issue. Thanks.
