### ISSUE TITLE
Bluetooth GATT multiple Primary Service Declarations

### ISSUE THREAD

**Issue by HyP3r-** [espressif/esp-at#167]
When I add multiple Primary Service Declarations to my Bleutooth Low Energy CSV file, I get an error ([AT+BLEGATTSSRVSTART](https://github.com/espressif/esp32-at/blob/master/docs/ESP32_AT_Commands_Set.md#cmd-GSSRVSTART)) when starting the GATT services:

```
AT+BLEGATTSSRVSTART

ERROR
```

What could be the cause? Can't multiple services be defined?

[Esp32BleGatt.csv.txt](https://github.com/espressif/esp32-at/files/2838085/Esp32BleGatt.csv.txt)

**Update**: It is the very same problem as: https://github.com/espressif/esp32-at/issues/87

**Comment by kurta999** [comment]
Any news/plans when multiple gatt services will be supported?

**Comment by xiewenxiang** [comment]
We will support multiple Primary Service in next release.

**Comment by xcguang** [comment]
Can you try b991a183bd6645340fc73a07cc964cfb3c5aae99? If you have any question, please just feel free to let us know.
