### ISSUE TITLE
Bluetooth Paring Unkown Response

### ISSUE THREAD

**Issue by HyP3r-** [espressif/esp-at#170]
When I try to pair the ESP32 with e.g. the "nRF Connect" Android app (the ESP32 is in server mode). Get the following message:

`+BLESECREQ:0`

This is not mentioned in the manual. How and what should be answered?

**Comment by xiewenxiang** [comment]
This means that the remote device which conn_index is 0 has initiated an encryption request, and ESP32 needs to respond to whether or not to accept the encryption
[AT+BLEENCRSP](https://github.com/espressif/esp32-at/blob/master/docs/ESP32_AT_Commands_Set.md#cmd-BLEENCRSP)
