### ISSUE TITLE
[Question] Is there a way to get network statistics?

### ISSUE THREAD

**Issue by sarai2** [espressif/esp-at#176]
I'm trying to receive a lot of UDP packet using AT command and seeing some packets drop.  Of course, it's UDP and I'm not expecting error-free communication, but I'm wondering if this is because 1) the packet was not received by the ESP32, or 2) ESP32 received the packet, but as I didn't read the data timely, it was lost.  If the latter is the case, I can do something with my software to reduce the number of lost packets.  Is there a way to find out if (or how much) data was lost due buffer overrun?

**Comment by xcguang** [comment]
Hi,
Current AT command does not support this feature.

**Comment by xcguang** [comment]
Hi,
I will close this issue, if you have any question, please reopen it again.
