### ISSUE TITLE
error parseando "esp_at_get_para_as_str"

### ISSUE THREAD

**Issue by maxi03462** [espressif/esp-at#180]
I have a function that receives as argument a number value and a string that contains ',' inside

Example:
`AT+RSEND=32,"0,107,0,0,1,0, , ,23-02-19 14:59"`

The error occurs when obtaining the value of the string with the function "esp_at_get_para_as_str".

I attach the fragment of the code where I get the string.

```
   int32_t  cnt = 0;
   uint8_t* cadena;
   int code;
   
   if (esp_at_get_para_as_digit (cnt++,&code) != ESP_AT_PARA_PARSE_RESULT_OK) {
      esp_at_port_write_data( (uint8_t *)"Error leng\r\n", strlen("Error leng\r\n"));
      return ESP_AT_RESULT_CODE_ERROR;
   }
   
   if (esp_at_get_para_as_str (cnt++, &cadena) != ESP_AT_PARA_PARSE_RESULT_OK) {
      esp_at_port_write_data( (uint8_t *)"Error Data\r\n", strlen("Error Data\r\n"));
      return ESP_AT_RESULT_CODE_ERROR;
   }
```

**Comment by xcguang** [comment]
Please send it as following
`AT+RSEND=32,"0\,107\,0\,0\,1\,0\, \, \,23-02-19 14:59"`
