### ISSUE TITLE
STA IP Error

### ISSUE THREAD

**Issue by wnoliveira** [espressif/esp-at#182]
I was having troubles when trying to connect to a TCP sever. I don't know exactly how, but the source of my problems is that the STA IP is set to "0.0.0.0". I tried to rewrite this IP, to a valid one, but without success. If you notice, the command AT+CIFSR keeps returning the IP "0.0.0.0".

The only way to return to a valid IP was sending a RESTORE command, as shown in the terminal below.

![](https://i.imgur.com/0ob6gwp.png)

I think that it's a bug on firmware. Does anyone have another idea?

**Comment by SONGjiaxiu** [comment]
Hi,
The following is LOG.The image shows the version information for the esp32-at project I used.
![Selection_084](https://user-images.githubusercontent.com/26621056/62192080-82fc6480-b3a7-11e9-9a13-a8f89af1b4bd.png)
Which branch of the esp32-at program do you use?
thanks

**Comment by xcguang** [comment]
Close it because of no update for a long time, if you have any question, please reopen it again.
