### ISSUE TITLE
ESP32 WROOM BLE server not connecting android phone 

### ISSUE THREAD

**Issue by alekarasma** [espressif/esp-at#185]
Hello everyone,

I am newbie to esp32. My company is planning to use esp32 in their product. We are trying to communicate to esp32 through UART using AT commands from iMX6 to use BLE Services. 

I have download the latest firmware ESP32-WROOM-32 AT Bin V1.1.2. I am trying to create BLE server which connects to Smartphone. Server is able to advertise data but when tring to connect from smartphone it does not response anything and nor does it connect. 
Following are the commands I am sending.

```
AT+BLEINIT=2
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

OK

AT+BLEADDR?
+BLEADDR:b4:e6:2d:9e:88:0b
OK
++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++AT+BLEGATTSSRVCRE
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
OK
bbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbAT+BLEGATTSSRVSTART

OK
T+BLEADVPARAM=32,64,0,0,7

OK
+++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++AT+BLEADVDATA="020106"

OK

AT+BLESECPARAM=1,4,16,3,3

OK

AT+BLEADVSTART
YYYYYYYYYYYYYYYYY
OK
```

The above is the output of the command I send through iMX6. Is there any command I am missing. I have also flash default service.bin.

Please help me to connect it with smartphone.

Thanks,
Asma

**Comment by xiewenxiang** [comment]
All the steps are correct. Which APP do you use?
