### ISSUE TITLE
esp-at v1.2 with SparkFun ESP32 Thing

### ISSUE THREAD

**Issue by almoniplo** [espressif/esp-at#186]
Hi,

I want to flash esp32-at project to my SparkFun ESP32 Thing board.

I matched the uart settings to my board - UART0, RX (GPIO1), TX (GPIO3), RTS (GPIO22), CTS (GPIO19), and flashed version 1.2 successfully, but didn't get READY in my terminal (I use HyperTerminal).

In addition, I downloaded ESP32 AT Bin V1.1.3 and Espressif's official Flash Download Tools and tried to work with that, but got gibberish in my terminal (already checked the baudrate).

Did anyone flash esp32-at project to SparkFun ESP32 board before? What did I do wrong?

Thanks a lot!

**Comment by SONGjiaxiu** [comment]
Hi,
The Board sends AT commands through UART1 by default.The debug log will output through UART0 by default, which TXD0 is GPIO1 and RXD0 is GPIO3, but user can change it in menuconfig if needed.
see:https://github.com/espressif/esp32-at/blob/master/docs/ESP_AT_Get_Started.md
Good luck.
