### ISSUE TITLE
binary with bt classic enabled

### ISSUE THREAD

**Issue by alekarasma** [espressif/esp-at#188]
Hi everyone,

I am not able to create binary with esp-idf. I need a binary with bt classic enabled. Do anyone has that, if yes, can you please provide me?

and what address I should flash it with esp flash tool?

**Comment by xcguang** [comment]
https://www.espressif.com/zh-hans/support/download/at
<img width="985" alt="image" src="https://user-images.githubusercontent.com/25979965/68667605-5ef11780-0581-11ea-9808-b35fd4150d92.png">
