### ISSUE TITLE
AT command for reading out internal tempsensor's value?

### ISSUE THREAD

**Issue by kurta999** [espressif/esp-at#190]
Is it planned in future please? We are having temperature issues with ESP and we would like to track it's temperature. This problem of course could be at our side due to wrong PCB design, but tracking the temperature with different RF power settings would be very useful.

**Comment by kurta999** [comment]
Any news on this?

**Comment by kurta999** [comment]
Any news on this please? We would like to track the temperature of ESP chips outside via AT commands and I think it would be useful for others too. I think it's not a really hard work. 

Please answer, thanks!

**Comment by xcguang** [comment]
The chip temperature?

**Comment by kurta999** [comment]
Yes.

**Comment by xcguang** [comment]
Sorry for that, the chip temperature can't be read.
