### ISSUE TITLE
Error compiling firmware: include file "uECC.h" missing

### ISSUE THREAD

**Issue by fantasiiio** [espressif/esp-at#193]
Hi,

I'm following instructions on https://github.com/espressif/esp32-at
I'm on windows and installed toolchain using this guide: https://docs.espressif.com/projects/esp-idf/en/latest/get-started/windows-setup.html#introduction

- 'make defconfig' worked, with a wvroom32 library not found warning.
- 'make menuconfig' worked
- But 'make flash' failed. I attached a screenshot.
![2019-04-05 10_18_59-~_esp_esp32-at](https://user-images.githubusercontent.com/4818842/55634371-61d68f00-578c-11e9-9325-6c8d754de44f.jpg)

Is there something I can do ?

**Comment by imxood** [comment]
in ubuntu, the same

**Comment by imxood** [comment]
Hi, i test a method, it is OK.
1. git clone -b release/v1.2.0.0 https://github.com/espressif/esp32-at.git
    cd esp32-at
2. change the .gitmodules, add one line:
    branch = release/v3.3
    then, run command:
        git submodule update --init --recursive
3. make menuconfig
    make flash -j12

**Comment by fantasiiio** [comment]
It seem to have compiled without error. Thanks, that's awesome !

But now... Does the firmware is uploaded to the mcu ? There was no progress bar of erasing memory and flashing... Is it normal ?

**Comment by imxood** [comment]
It work well. After "make flash -j12", You can find the wifi by your phone.
"make flash -j12", the command can build the esp-idf and esp-at, flash program to your esp32 device.

**Comment by fantasiiio** [comment]
Classic bluetooth commands doesn't seem to be available in the "make menuconfig" in this version.. I need these commands.

**Comment by xcguang** [comment]
Classic bluetooth command configuration  has added in `make menuconfig`

**Comment by xcguang** [comment]
The lastest `ESP32-WROVER AT Bin V2.0` firmware has been released, which enables classic bluetooth command by default, you can find it at https://www.espressif.com/zh-hans/support/download/at
