### ISSUE TITLE
Used UART0 for AT command but didn't respond

### ISSUE THREAD

**Issue by Masi2017** [espressif/esp-at#206]
Hi all,
I am trying to use UART0 instead of UART1. I have changed the AT port in menuconfig (TXD0=1, RXD0=3 , CTS=22 , RTS=19). Also I've redirected debug port to UART1 and changed the UART pins to 16 and 17 for RX and TX. I have turned off flow control. I should add that I am using ESP32_DEV_KIT_V4 ( which has WROOM) . Unfortunately I am not able to communicate with that and I don't get any response from AT port. Also I've changed the factory_param_data too but nothing changed then I commented out those lines that set rx and tx based on partition file and hard forced it to use gpio 1 and 3 but nothingchanged .
 I've attached an screenshot here:
![image](https://user-images.githubusercontent.com/34062463/58347930-24f25480-7e2d-11e9-92f9-ea0b7477f567.png)

**Comment by deadprogram** [comment]
Seems like this commit removed the ability to customize which UART is used for AT commands: https://github.com/espressif/esp32-at/commit/a8126c3e9c836b8e81f1c79de498f9424cf55cb5

This is actually a feature I really need!

**Comment by xcguang** [comment]
Please refer to https://github.com/espressif/esp-at/blob/master/docs/How_To_Set_AT_Port_Pin.md, which we recently added.
