### ISSUE TITLE
Use GPIOs as status indicators for AT+CIPSTATUS command

### ISSUE THREAD

**Issue by kstbh** [espressif/esp-at#207]
I want to use three GPIO as **status indicators** using LED to show different status of ESP32 Module using **_AT+CIPSTATUS_** command.
When i send the  AT+CIPSTATUS command , ESP32 will respond with setting **_GPIOs HIGH/LOW_** as well as with **_UART response_** as per status of module.

**Comment by xcguang** [comment]
You can do it on AT project and compile the firmware.
