### ISSUE TITLE
ESP32-PICO-D4 AT-commands on UART0 - How?

### ISSUE THREAD

**Issue by galyamovm** [espressif/esp-at#214]
Hello. I have an ESP32-PICO-D4 board and I want to use AT commands to control. From the documentation I concluded that only UART0 is available on this board, to which debugging information is sent by default and AT commands are not available. (UART1 and UART2 ports used for flash memory).
I downloaded the esp32-at.bin file to the chip at the appropriate address, but the AT commands did not appear (I also tried to load the factory_PICO-D4.bin file and this did not help either). I suspect that it is necessary to change the firmware so that the AT commands are available on the UART0 port, but I don’t understand how to do it yet.

How to control the chip using AT commands? Maybe there is a detailed instruction on how to enable AT commands on the UART0 port?

**Comment by xiewenxiang** [comment]
You can use Uart0 to input the command, but Uart0 will have some unmasked logs.
If you really want to do this, you can modify 
`esp-at/components/customized_partitions/raw_data/factory_param/factory_param_data.csv`

Then recompile the project

```c
make
make print_flash_cmd | tail -n 1 > build/download.config
make factory_bin
```

**Comment by galyamovm** [comment]
Thanks for the answer. Debug output can be turned off, or am I wrong?
And did I understand correctly that on the ESP32-PICO-D4 board, the control of AT commands is available only through the UART0 port?

**Comment by xiewenxiang** [comment]
Debug information can be turned off, but some boot log cannot be completely turn off.

**Comment by galyamovm** [comment]
Thanks, I will try.

**Comment by galyamovm** [comment]
Hello, xiewenxiang!
I edited the parameters file and generated the firmware for the board, downloaded it - and so far nothing worked :(
![param](https://user-images.githubusercontent.com/20027746/61070871-509abf80-a418-11e9-9e23-f0b04305f513.jpg)

In the Putty console, I see that the board is constantly rebooting:
![reset](https://user-images.githubusercontent.com/20027746/61070875-58f2fa80-a418-11e9-88a4-721f61414e45.jpg)

I tried to change the settings by calling the command "make menuconfig" - screenshots attached.
![uart_1](https://user-images.githubusercontent.com/20027746/61070910-690ada00-a418-11e9-9d69-41462d42f5b2.jpg)

![uart_2](https://user-images.githubusercontent.com/20027746/61070935-758f3280-a418-11e9-8e89-159813766009.jpg)


Probably, I'm doing something wrong again?

**Comment by swouf** [comment]
Hello !
I refresh the the issue as I am also doing this for an ESP32-WROOM. I did the same kind of change @galyamovm did but I couldn't manage to send AT commands to the ESP on its UART0 port. See issue #222 for more details about how I proceeded.

**Comment by xcguang** [comment]
Maybe https://github.com/espressif/esp-at/blob/master/docs/How_To_Set_AT_Port_Pin.md is help to you.
