### ISSUE TITLE
[BLE] Set a Pairing key with AT

### ISSUE THREAD

**Issue by alexdecei** [espressif/esp-at#219]
Hi, is it possible to set a static **pairing key** with AT Commands ?

For the moment, the pairing key is set automatically with `+BLESECNTFYKEY:0,xxxxxx`.

Thank you.

**Comment by xiewenxiang** [comment]
This feature will be added in the next release

**Comment by alexdecei** [comment]
Ok, thank you for the support.

**Comment by xiewenxiang** [comment]
@alexdecei 

The latest master branch has been supported.
