### ISSUE TITLE
+BTDATA data loss

### ISSUE THREAD

**Issue by JudeDalton** [espressif/esp-at#221]
I am sending a 2000 byte packet over BT SPP from a PC. The AT reports +BTDATA:989,..... and I get the first 989 bytes of the packet data - the rest however never arrives.

**Comment by xiewenxiang** [comment]
Is this a 100% recurring problem? Does PC  enable flow control？

**Comment by JudeDalton** [comment]
I have not tried with flow control - I will do so...
