### ISSUE TITLE
Compilation error : no rule to make log.c needed by log.o

### ISSUE THREAD

**Issue by marrakchino** [espressif/esp-at#224]
Hi, 

I am building the project for the ESP32-DevKit V4 development board and have the following error : 
`make[2]: *** No rule to make target 'esp-idf/components/log/log.c', needed by 'log.o'. Stop`

I know this is actually related to esp-idf but I only get this error when compiling this project...

Best,

**Comment by xcguang** [comment]
Do you set ESP_IDF? Please unset it.

**Comment by marrakchino** [comment]
@xcguang do you mean as an environment variable? It's not set.

**Comment by xiewenxiang** [comment]
ESP_IDF must be pointed to the `esp32-at/esp-idf`

**Comment by marrakchino** [comment]
Perfect, thanks!
