### ISSUE TITLE
8266 not support “SSL” related AT command

### ISSUE THREAD

**Issue by lavilycn** [espressif/esp-at#226]
why 8266 AT commad set not support "SSL" related command set,ex:AT+CIPSTART="SSL","xxx",443,ex:AT+CIPSSLCCONF=0,0,0
But i found that the relevant certificate files(ca,crt,key) have been downloaded to the correct location of flash
Are these features supported in later updates or already supported?

**Comment by jandrassy** [comment]
try AT+CIPSTART=4,"SSL","xxx",443,

**Comment by lavilycn** [comment]
thanks a lot，this does not work. and uart printf "ERROR" without error code.
referring in at instructions document :
4.3.3 [ESP32 Only] Establish SSL Connection[AT+CIPSTART]
4.19 [ESP32 Only] Config SSL client [AT+CIPSSLCCONF]

**Comment by xiewenxiang** [comment]
The latest master branch support 8266 SSL.
