### ISSUE TITLE
make flash error  ： IOError:

### ISSUE THREAD

**Issue by stevenzsjcyzz** [espressif/esp-at#230]
App "esp-at" version: ESP-AT
Generating esp32.project.ld
Traceback (most recent call last):
  File "C:/msys32/home/Administrator/esp/esp-idf/tools/ldgen/ldgen.py", line 132, in <module>
    main()
  File "C:/msys32/home/Administrator/esp/esp-idf/tools/ldgen/ldgen.py", line 96, in main
    sdkconfig = SDKConfig(kconfig_file, config_file, args.env)
  File "C:/msys32/home/Administrator/esp/esp-idf/tools/ldgen/sdkconfig.py", line 56, in __init__
    self.config = kconfiglib.Kconfig(kconfig_file)
  File "C:/msys32/home/Administrator/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 656, in __init__
    self.top_node)  # prev_node
  File "C:/msys32/home/Administrator/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1583, in _parse_block
    self._enter_file(sourced_file)
  File "C:/msys32/home/Administrator/esp/esp-idf/tools/kconfig_new/kconfiglib.py", line 1167, in _enter_file
    .format(self._filename, self._linenr, e.message))
IOError: C:/msys32/home/Administrator/esp/esp-idf/Kconfig:65: Could not open 'C:msys32homeAdministratorespesp-idfcomponentsapp_updateKconfig.projbuild' (ENOENT: No such file or directory). Perhaps the $srctree environment variable (which was unset) is set incorrectly. Note that the current value of $srctree is saved when the Kconfig instance is created (for consistency and to cleanly separate instances). Also note that e.g. $FOO in a 'source' statement does not refer to the environment variable FOO, but rather to the Kconfig Symbol FOO (which would commonly have 'option env="FOO"' in its definition).
make: *** [/home/Administrator/esp/esp-idf/components/esp32/Makefile.projbuild:51：/home/Administrator/esp/esp-idf/examples/esp-at/build/esp32/esp32.project.ld] 错误 1

**Comment by Neslon07** [comment]
I had the same probleme, I think the cygpath function removes all backslashes in the path (on Windows).  I used an older ldgen.mk file and then it worked (took me a while to figure it out...).

So just replace the file in esp-idf\ldgen.mk with the one I attached. Hopefully it will work after that.
[ldgen.zip](https://github.com/espressif/esp-at/files/3582323/ldgen.zip)

**Comment by xcguang** [comment]
Hi, 
Now there is a bug in the ldgen.mk, you can change "cygpath -w" to "cygpath -m" for temporary correction.
@Neslon07 It also took me some time to debug it. I have report esp-idf this bug.

**Comment by stevenzsjcyzz** [comment]
@Neslon07  Thanks for your help . I will try.

**Comment by stevenzsjcyzz** [comment]
@xcguang  Thanks .And esp-idf'version if need to match the esp-at'version . I suggest can upload a match version  link of esp-idf for windows and make sure it can run.

**Comment by xcguang** [comment]
The idf version or ldgen.mk version? You can find IDF version at the https://github.com/espressif/esp-at/blob/master/module_config/module_esp32_default/IDF_VERSION.

**Comment by stevenzsjcyzz** [comment]
@xcguang  Thanks But Ican't find whitch version can match the esp-at..... :(

**Comment by xcguang** [comment]
You can check `module_config/module_esp32_default/IDF_VERSION` in you local esp-at.

**Comment by stevenzsjcyzz** [comment]
@xcguang  OK. Thanks

**Comment by stevenzsjcyzz** [comment]
@xcguang  Sorry . E... how to check the idf version in my local...

**Comment by xcguang** [comment]
Which commit id of esp-at do you use？

**Comment by stevenzsjcyzz** [comment]
@xcguang I git clone esp-idf-v3.3 in new path，and change the  $IDF_PATH  to the new path .But The shell will mkdir a new C:\msys32homeAdministratorespesp-idf  Folder to run and appear the same error.

**Comment by xcguang** [comment]
@stevenzsjcyzz 
OK,we will try it. You can unset $IDF_PATH, and get the the project as following:
```
git clone --recursive https://github.com/espressif/esp-at.git
cd esp-at
make defconfig. // it will auto download the esp-idf
make
```

**Comment by jscastonguay** [comment]
Hello,

@xcguang @stevenzsjcyzz 

Now the construction of esp32-at works for you? Have you found the solution of the problem of path without "/"?

Thanks

**Comment by xcguang** [comment]
Same as https://github.com/espressif/esp-at/issues/232

**Comment by xcguang** [comment]
Please try it using the latest master branch, if the issue persists, please reopen it again.

**Comment by Emiel84** [comment]
> I had the same probleme, I think the cygpath function removes all backslashes in the path (on Windows). I used an older ldgen.mk file and then it worked (took me a while to figure it out...).
> 
> So just replace the file in esp-idf\ldgen.mk with the one I attached. Hopefully it will work after that.
> [ldgen.zip](https://github.com/espressif/esp-at/files/3582323/ldgen.zip)

This worked for me! Thanks for this file.
