### ISSUE TITLE
esp32-at with esp-idf 4.0 and websocket

### ISSUE THREAD

**Issue by boriss2oo6** [espressif/esp-at#231]
Hello,

It's a while since ESP-IDF 4.0 was released, are there any plans for a new release on ESP-AT (i did a try but i didn't succeeded to compile) ? Also 4.0 comes with WebSocket, so any plans to include this feature soon ?

Thanks in advance.

**Comment by xiewenxiang** [comment]
The next release of AT will be based on IDF v3.3.

**Comment by MaJerle** [comment]
@xiewenxiang when do you target next release of AT firmware for both, 32 and 8266?

**Comment by xcguang** [comment]
If everything goes well, ESP32 is about this month, and ESP8266 next month.

**Comment by kzoltaan** [comment]
is any news about ESP-AT with esp-idf 4.0?

**Comment by xcguang** [comment]
The latest AT project supports ESP-IDF 4.0, I will close this issue, if you have any question, please create the new issue, thanks.
