### ISSUE TITLE
AT+BLESCANPARAM command units

### ISSUE THREAD

**Issue by marrakchino** [espressif/esp-at#235]
What are the units for this AT command, in particular scan_window and scan_interval ? There is no information in the AT instruction set ...

Thanks!
Nabil

**Comment by xiewenxiang** [comment]
`Scan interval`. 

This is defined as the time interval from when the Controller started its last LE scan until it begins the subsequent LE scan.

  - Range: 0x0004 to 0x4000 Default: 0x0010 (10 ms)
  - Time = N * 0.625 msec
  - Time Range: 2.5 msec to 10.24 seconds

`Scan window`. 

The duration of the LE scan. LE_Scan_Window shall be less than or equal to LE_Scan_Interval

  - Range: 0x0004 to 0x4000 Default: 0x0010 (10 ms)
  - Time = N * 0.625 msec
  - Time Range: 2.5 msec to 10.24 seconds

**Comment by marrakchino** [comment]
Thanks @xiewenxiang .
Given the following command  :  `AT+BLESCANPARAM=0,0,0,320,40`, does this set the following parameters?
* interval : 320 * 0.625 msec = 200 msec
* window : 40 * 0.625 msec = 25 msec

**Comment by marrakchino** [comment]
Anyone ?

**Comment by xiewenxiang** [comment]
@marrakchino 
Yes, you are right.
