### ISSUE TITLE
[AT Ping][docs] Wrong ping response format

### ISSUE THREAD

**Issue by MaJerle** [espressif/esp-at#238]
Documentation states wrong PING response.

https://github.com/espressif/esp-at/blob/master/docs/ESP_AT_Commands_Set.md#425-atping-ping-packets

It says response is `+<time>` while in reality response is `+PING:<time>`.

**Comment by xiewenxiang** [comment]
@MaJerle 
Thanks, we will modify the doc as soon as possible.

**Comment by xcguang** [comment]
Has updated.
