### ISSUE TITLE
[AT][CIPDNS][docs] Wrong CIPDNS format on query

### ISSUE THREAD

**Issue by MaJerle** [espressif/esp-at#239]
https://github.com/espressif/esp-at/blob/master/docs/ESP_AT_Commands_Set.md#426-atcipdns--configures-domain-name-system

Docs says on query, this is response: `+CIPDNS:<enable>[,<"DNS IP1">,<"DNS IP2">,<"DNS IP3">]`.

Reality:
```
AT+CIPDNS?
+CIPDNS:8.8.8.8
+CIPDNS:8.8.4.4
OK
```

**Comment by xcguang** [comment]
Please give the AT version by AT+GMR.

**Comment by MaJerle** [comment]
Esp32 1.2 from espressif website.

Its very unclear how to compile this under windows by myself.

**Comment by xiewenxiang** [comment]
@MaJerle 

Thank you for your information and we will fix it as soon as possible

**Comment by xcguang** [comment]
Has updated.

**Comment by jandrassy** [comment]
I expected the reference to change, not the implementation which was the same as on esp8266

**Comment by xcguang** [comment]
Currently response is `+CIPDNS:<enable>[,<"DNS IP1">,<"DNS IP2">,<"DNS IP3">]`
