### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by katarinaar** [espressif/esp-at#250]
Does ESP-AT firmware support SNI?

**Comment by xcguang** [comment]
We've added it to the to-do list, but we don't have a detailed schedule. We we are waiting esp-tls component support it.

**Comment by daveatpanic** [comment]
Does ESP-TLS not support SNI? It's listed here: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/protocols/esp_tls.html

**Comment by pshank** [comment]
I thought I also saw a previous issue where SNI was integrated with the library. Was I seeing things, or is SNI not supported? That would explain quite a bit if this were the case...

**Comment by daveatpanic** [comment]
Nope, this says the AT firmware's not sending SNI: https://check-tls.akamaized.net/v1/tlssni.json

**Comment by FayeY** [comment]
SNI seems to be supported now. https://docs.espressif.com/projects/esp-at/en/latest/AT_Command_Set/TCP-IP_AT_Commands.html#cmd-sslcsni
