### ISSUE TITLE
No "+STA_CONNECTED" message when station connects to ESP SoftAP (edited)

### ISSUE THREAD

**Issue by tvandergeer** [espressif/esp-at#252]
In previous versions of the ESP software (e.g. 1.7.0 for ESP8266) a message was sent by the ESP when a station (e.g. mobile phone) connected to the ESP's SoftAP. 

I'ver performed several tests on an ESP32 and ESP8266 on the v2.0 firmware, but the message never appeared. Is this a known issue? Is it possible to bring back a notification when a station connects to the SoftAP?

I've discussed this with @MaJerle[ in this ticket on his ESP_AT_Lib project](https://github.com/MaJerle/ESP_AT_Lib/issues/48). He confirmed that the message is no longer there.

**Comment by MaJerle** [comment]
@tvandergeer `+LINK_CONN` is still available. Missing one is `+STA_CONNECTED`, `+STA_DISCONNECTED`, `+STA_GOT_IP`.

**Comment by tvandergeer** [comment]
@MaJerle : You're right! I've modified my initial question accordingly to prevent confusion.

**Comment by xcguang** [comment]
Yes, I will firstly add it on the ESP32 AT. There is something  is based on SDK, but current ESP8266 SDK is missing it.

**Comment by xcguang** [comment]
The message on the ESP32 AT has been added.

**Comment by tvandergeer** [comment]
Great, thank you!

**Comment by MaJerle** [comment]
@xcguang could you please upload complete compiled project here? Thanks

**Comment by xcguang** [comment]
Done on ESP8266 via 75ee09f84625aa

**Comment by xcguang** [comment]
I will close this issue, if have any question, please reopen it or create a new issue.
