### ISSUE TITLE
[BLE] AT+BLECONN gives ERROR

### ISSUE THREAD

**Issue by alexdecei** [espressif/esp-at#253]
Hi, my problem is simple: AT+BLECONN does not work.  I type:

```
AT+BLEINIT = 1

AT+BLECONN=0,"5b:f5:b9:de:b2:65"
```
(I let an uuid for the exemple)  
And I randomly get one of those 3 ERRORS:  

**1)After 15 seconds**

> +BLECONN:0,-1
> 
> ERROR

**2)Immediately**

> ERROR

**3)After 15 seconds**
> +BLECONN:65535,-1
> 
> ERROR

## Here is what I tried
- I changed the service
- I changed the uuid
- I changed the device
- I checked the uuid with AT+BLESCAN=1
- I always succed to connect with an other client device (a phone or a computer)   
  
And surprisingly, it once worked for severeal seconds without changing any parameter. But just one time.  

Did I missed something ?

Thank you,  

Alex

**Comment by alexdecei** [comment]
By the way, my firmware version is 1.2

```
AT+GMR
AT version:1.2.0.0(6fe4345 - Jun 27 2019 05:39:23)
SDK version:v3.2-127-gddbce78
compile time:Jun 27 2019 12:08:01
Bin version:1.2.0(Unknown)
```

**Comment by xiewenxiang** [comment]
The remote device must be needed in broadcast

Also note the address type, if the remote device is a random address type, you need to add optional parameters

```
AT+BLECONN=0,"5b:f5:b9:de:b2:65",1
```

**Comment by ikalogic** [comment]
@alexdecei could you please share a little more about how it worked? I feel like I'm having exactly the same problème here #334. I even tried downgrading my ESP32 to have exactly the same firmware as you, but still I can't get it to work.

Thank a lot indeed

**Comment by alexdecei** [comment]
Hi, as I said here #166 there is still a problem (I must reset the ESP sometimes) :

> For a static (not random) adress, I get sometimes:
> 
> AT+BLECONN=0,"d4:ca:6e:b6:ef:57"
> +BLECONN:0,-1
> 
> ERROR
> 
> That happens when I try just before to connect to a busy periferical or when the periferical rejected the connection.
> To fix that, I must reset the esp with AT+RST.
> 
> Is there any clean solution ? Other than reseting the chip I mean.
> 
> Thanks


I assume that BLE AT commands for ESP32 are not perfect at all. I am working on since June and I found a lot of bugs.
