### ISSUE TITLE
Issue receiving data from server

### ISSUE THREAD

**Issue by Masi2018** [espressif/esp-at#254]
I am using Wroom-32 as wifi module in my application . I have connected my MCU to the WIFi module through Uart port. When I program the Wroom module with old version of esp-at firmware (v1.0.0.0) I don't have any issues sending and receiving information to/from the MQTT server while when I use the latest code (the one is in the master branch), most of the time I can't receive data from MQTT server while I see the response has been sent from the server ( I use MQTT Explorer to monitor the data) . I don't have problem in sending data but nothing shows up on TX port of the ESP32 module which is connected to my MCU RX port. 
I should add that when I send a CIPRECVLEN command while I am in active mode len is not zero however when I send CIPRECVDATA to get the data it returns error. here is an screenshot of the outouts:
![image](https://user-images.githubusercontent.com/36539878/67884138-ad32ff00-fb1b-11e9-8b55-063af516fe29.png)

**Comment by xcguang** [comment]
Hi, 
Can you provide all command sequences starting with the first command? We will try it.

**Comment by Masi2018** [comment]
@xcguang  Please see the command sequences below:

![image](https://user-images.githubusercontent.com/36539878/68250974-2e910280-fff0-11e9-93e2-e8f2250e4629.png)

**Comment by Masi2018** [comment]
@xcguang Hi, Just wanna know that if you had a chance to have a look at this issue ?

**Comment by jandrassy** [comment]
did you set `AT+CIPRECVMODE=1` to use the passive recieve mode with `AT+CIPRECVDATA`?

**Comment by Masi2018** [comment]
@jandrassy  No I didn't, you can see CIPRECVMODE is 0 in my first screenshot.

**Comment by xcguang** [comment]
We tested it, but it looks well. Could you test it on PC serial port?

**Comment by jandrassy** [comment]
> @jandrassy No I didn't, you can see CIPRECVMODE is 0 in my first screenshot.

so? you want to use it but didn't activate it

**Comment by Masi2018** [comment]
@jandrassy No I don't want use this. I want the received socket data is sent instantly to host MCU through UART. So I don't want to activate this

**Comment by jandrassy** [comment]
> 
> 
> @jandrassy No I don't want use this. I want the received socket data is sent instantly to host MCU through UART. So I don't want to activate this

then don't use `AT+CIPRECVLEN?'. it is part of the passive mode approach

**Comment by Masi2018** [comment]
@jandrassy I only used AT+CIPRECVLEN to demonstrate that although I haven't used passive mode,  data is buffered , in my real code I don't use that. As I had mentioned my issue is after sometimes I don't receive any data from MQTT while it has been sent. Only I can get the data shortly after the connection is made, After that data is sent to the server but not received by the ESP32 and looks like it starts buffering the received data instead of sending out to the port while it is in active mode

**Comment by jandrassy** [comment]
the data are always buffered. the TCP packet is read much faster from network then it can be pushed over UART. so focus on why you didn't receive `+IPD`

**Comment by Masi2018** [comment]
@jandrassy  I don't have issue with older revision only in this new revision I have issue. data is not sent out to the UART port

**Comment by xcguang** [comment]
Can you try the latest master branch? We did some process optimization, I'm not sure whether it affects this issue, because we cannot reproduce it.

**Comment by niziak** [comment]
@Masi2018 Any results?
