### ISSUE TITLE
GP-SPI Clock Control ESP32-DOWDQb

### ISSUE THREAD

**Issue by Sebastiangka** [espressif/esp-at#257]
Im wondering why is it the maximum input clock frequency of the ESP32 SPI slave a fapb/8?

![image](https://user-images.githubusercontent.com/45280710/68024691-1d23bf80-fcab-11e9-9aa8-8e380ca2b3c2.png)

I got the info from the technical reference manual for the ESP32 (page 124)
@projectgus @kedars @mahavirj @igrr @Spritetm 
Thank you in advance

**Comment by ginkgm** [comment]
Hi @Sebastiangka,
The slave's speed has no relation to this internal clock divider. It tries to sample the data and clock signals with its APB clock (80MHz) and respond to them.

fapb/8 is just the design target for the SPI slave part, which means, we didn't expect it to be used over this frequency. Above this frequency, the clock may not be correctly sampled, the input data (MOSI) may be sampled incorrectly, or the returning data (MISO) may violate the timing requirements of the spec. Applications above this frequency will have no guarantee from Espressif.
