### ISSUE TITLE
esp-at\example\at_http_webserver

### ISSUE THREAD

**Issue by LiThirteen** [espressif/esp-at#258]
ESP-AT的案例中 at_http_webserver是否支持ESP8266_RTOS_SDK环境的编译与下载，本人使用ESP8266_RTOS_SDK_Master 对齐进行编译，但是报错httpserver/include/espfs.h:8:25: fatal error: esp_vfs_fat.h: No such file or directory ，究竟是不支持呢还是我个人项目配置的出错？

**Comment by xcguang** [comment]
暂时不支持，后面我们添加上

**Comment by LiThirteen** [comment]
好的，我会持续关注的，感谢
