### ISSUE TITLE
Rebond problem with iOS

### ISSUE THREAD

**Issue by Neslon07** [espressif/esp-at#260]
Dear Espressif team

Can you tell me how to handle the following use case:
iOS device and ESP32 are bonded over BLE (just works), ESP32 makes factory reset (AT+RESTORE), then iOS want's to reconnect to device. Connecting / pairing fails always unless I remove the ESP32 device manualy from iOS device list.

When do I have to send a slave security request message (AT+BLEENC)?

At the end I have the following use cases:
Android
->Phone and ESP32 bonded, Phone removes ESP32 BT device, connect again
->Phone and ESP32 bonded, ESP32 removes Phone from pairing list, connect again

iOS
->Phone and ESP32 bonded, Phone removes ESP32 BT device, connect again
->Phone and ESP32 bonded, ESP32 removes Phone from pairing list, connect again

As of now I'm not able to go through all of this use cases without having the end user to do a manual remove of BLE device (mainly in iOS), which is a very bad user experience. Please advise.

Thank you in advance.

**Comment by xiewenxiang** [comment]
If ESP32 bonded with phone, No matter which party is clear the bonded information, The other end also needs to be cleared.

You can use `AT+RST` to restart ESP32.
