### ISSUE TITLE
Q: AT commands over UART

### ISSUE THREAD

**Issue by theborg1** [espressif/esp-at#261]
Hi.

I have in an previous version V1.2.0.0 used AT command via UART 0 (Changed from 1 to 0), 
how to select which used shall be used in the latest V2.0.0.0_ESP32 ?

Thanks in advance.

**Comment by xcguang** [comment]
https://github.com/espressif/esp-at/blob/master/docs/How_To_Set_AT_Port_Pin.md 
Is it helpful for you?

**Comment by theborg1** [comment]
Thanks a lot for you fast reply, this guide solved my issue :-)
