### ISSUE TITLE
Q: CTS & RTS pins are the must for UART AT?

### ISSUE THREAD

**Issue by zslzxm** [espressif/esp-at#262]
Hi，
Does the cts & rts pin must be connected for uart at?
We only connect two pins(tx & rx)...

**Comment by PowerfulCat** [comment]
Is‘s not necessary.
In  / At / uart setting /
[] the uart flow control for AT port, the range is [0, 3]
assign this value to zero, it meanings disable cts/rts pin.

**Comment by xcguang** [comment]
If you do not want to use them, you should set them `-1`.

**Comment by zslzxm** [comment]
Thanks.
I have enable the uart AT without rts & cts pins already.
