### ISSUE TITLE
ESP32: How to do software upgrade through AT command.

### ISSUE THREAD

**Issue by zslzxm** [espressif/esp-at#265]
Hi,
I know esp32 support upgrade through OTA.
But for our project, we can't use that method.
The esp32 was connected to a STM32 chip in my project.
We want to first download the FW to stm32 through our specific tcp protocol,
and then send the FW to esp32 to upgrade esp32.
Does there have any way to implement this?
Thanks!

**Comment by xcguang** [comment]
You have two methods to do it
1. Customize your command to receive FW data from MCU, then write it into flash
2. Implement download function on MCU like https://github.com/espressif/esptool
