### ISSUE TITLE
Compile for 1M size flash fail

### ISSUE THREAD

**Issue by Dangku** [espressif/esp-at#272]
make menuconfig and select:

`CONFIG_IDF_TARGET_ESP8266=y`
`CONFIG_IDF_TARGET="esp8266"`
`CONFIG_ESPTOOLPY_FLASHSIZE_1MB=y`
`CONFIG_ESPTOOLPY_FLASHSIZE="1MB"`
`CONFIG_SPI_FLASH_SIZE=0x100000`
`CONFIG_PARTITION_TABLE_TWO_OTA=y`
`# CONFIG_PARTITION_TABLE_CUSTOM is not set`

run make command and got the error:

Generating esp8266.project.ld
LD build/esp-at.elf
/esp/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/bin/ld: /esp/esp-at/build/esp-at.elf section `.flash.text' will not fit in region `iram0_2_seg'
/esp/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/bin/ld: address 0x402a9ba4 of /esp/esp-at/build/esp-at.elf section `.flash.rodata' is not within region `iram0_2_seg'
/esp/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/5.2.0/../../../../xtensa-lx106-elf/bin/ld: address 0x402a9ba4 of /esp/esp-at/build/esp-at.elf section `.flash.rodata' is not within region `iram0_2_seg'
collect2: error: ld returned 1 exit status

in esp-at.map 

.flash.text     0x0000000040210010    0x8a610
                0x0000000040210010                _stext = .
                0x0000000040210010                _text_start = ABSOLUTE (.)

.flash.rodata   0x000000004029a620     0xf584
                0x000000004029a620                _rodata_start = ABSOLUTE (.)
                0x0000000000000008                . = 0x8

Memory Configuration

Name             Origin             Length             Attributes
iram0_0_seg      0x0000000040100000 0x000000000000c000 xr
iram0_2_seg      0x0000000040210010 0x000000000006fff0 xr
dram0_0_seg      0x000000003ffe8000 0x0000000000018000 rw
rtc_data_seg     0x0000000060001200 0x0000000000000200 rw
*default*        0x0000000000000000 0xffffffffffffffff

Thanks

**Comment by xcguang** [comment]
The firmware is too large for 1MB flash.

**Comment by Dangku** [comment]
Yes, esp-at.bin oversize app partition, So using the default sdkconfig must set  flash size >= 2MB,  Is there a minimal sdkconfig for 1MB flash? or a docs for firmware size optimization?

Thanks

**Comment by xcguang** [comment]
If enable OTA, it is too difficult using 1MB flash. You can disable some AT command and `make SILENCE=1` to try it.

**Comment by hallard** [comment]
@Dangku did you succeeded  to have latest version running on 1MB flash (even without OTA)?

**Comment by jandrassy** [comment]
@hallard use the latest master. there is a new option

**Comment by hallard** [comment]
Awesome, I'll try that, to be honest I succedeed to compile the 2MB version but when flashed on ESP Wemos Mini D1 the code never started and stopped after boot message, I'll try this one thank

**Comment by hallard** [comment]
@jandrassy just tried without success, more logs at #351
