### ISSUE TITLE
ESP32的AT固件是写入到外部flash还是内部flash呀？

### ISSUE THREAD

**Issue by PowerfulCat** [espressif/esp-at#274]
普通的Arduino固件呢？

**Comment by xcguang** [comment]
啥意思？

**Comment by PowerfulCat** [comment]
我们的SDIO连接到了FLASH了，HSPI和SAMD51的SPI连在一起的，应该和AT这块是有冲突的。

**Comment by xcguang** [comment]
你们什么问题啊？如果管脚有冲突，uart 是可以配置到其它管脚的

**Comment by PowerfulCat** [comment]
我们想要支持一下SPI和ESP32 At通信，UART工作得很好的。

**Comment by PowerfulCat** [comment]
之前推荐用ESP SDIO使用AT，发现SDIO已经连接了FLASH了，但是menuconfig里的SDIO口不能再配置到其他引脚了。
T...T

**Comment by PowerfulCat** [comment]
就是我想确认一下，ROOM32 ESP是不是把程序存到内部FLASH啦，或者使用其他接口连接FLASH，所以空处了可用的SDIO口

**Comment by xcguang** [comment]
是外部的 Flash，可以看一下我们官网的 wroom32 参考设计

**Comment by PowerfulCat** [comment]
好的👌

**Comment by PowerfulCat** [comment]
我看到WROOM32的SDIO接的是FLASH呀，这样就和AT使用的SDIO冲突了呀

**Comment by xcguang** [comment]
wrover32 的模组是可以跑 sdio 的，我们 AT 里面的 SDIO 程序也是基于 wrover32 模组测试的
