### ISSUE TITLE
希望AT能增加查询已连接wifi的ssid和pwd的功能

### ISSUE THREAD

**Issue by PowerfulCat** [espressif/esp-at#277]
AT+CWQAP在断开网络的同时也会忘记密码。
比如可以提供一个命令查询保存连结成功过的wifi清单，当然也可以选择忘记指定wifi。
查询时可以得到列表长度和ssid,pwd,bssid等信息，然后可以用一个命令输入下标号连接网络指定索引的wifi，可以筛选列表中实际可用的（有些记住密码的wifi可能不在信号范围）。

**Comment by xcguang** [comment]
好的，我们会记录下此 feature，下次制定 AT feature 时，进行评估
