### ISSUE TITLE
AT+CWLAP WiFi scan duration

### ISSUE THREAD

**Issue by marrakchino** [espressif/esp-at#279]
Hello,

I am using `AT+CWLAP` command to scan nearby APs (while writing the results to a buffer) and for my application purposes I need to know the duration of the scan to wake a function that processes the results.

I cannot find this information in the AT command manual.
Do you have any pointers?

Thanks,
Nabil

**Comment by PowerfulCat** [comment]
Perhaps you can use the interrupt to handle it when receive data from esp32 and then check the response line prefix whether it is start with +CWLAP:

**Comment by marrakchino** [comment]
Yes I finally figured out a way to do so, thanks @PowerfulCat
