### ISSUE TITLE
BT Classic HID

### ISSUE THREAD

**Issue by JuPrgn** [espressif/esp-at#282]
Hi,

Do you plan to add BT clasic HID (when) ?

I am not very familiar with BT and BLE but in my case the device use BT 3.0 so I think BLEHID will not work with this one. Can you confirm this please ?

With latest software (2019/11/13) and default configuration : `AT+BLEHIDINIT?` I get `ERROR`.
I have been looking for parameters in menuconfig but could not find anything related to BLEHID.

**Comment by xiewenxiang** [comment]
The classic HID is not planned yet.
