### ISSUE TITLE
ERR CODE:0x010b0000 and "busy p..." when configuring SSL with AT+CIPSSLCCONF

### ISSUE THREAD

**Issue by tvandergeer** [espressif/esp-at#283]
During the init phase of my ESP32 I run a dozen commands. Right after setting the configuration of the NTP server with `AT+CIPSNTPCFG` and getting the current time with `AT+CIPSNTPTIME?` I'm setting the SSL config for link ID 4 to auth mode 3. The `AT+CIPSSLCCONF` command returns with an error and a "busy p..." followed by an OK. 

```
AT+CIPSNTPCFG=1,0,"2.nl.pool.ntp.org"

OK
AT+CIPSNTPTIME?
+CIPSNTPTIME:Mon Nov 25 20:39:19 2019
OK
AT+CIPSSLCCONF=4,3,0,0
ERR CODE:0x010b0000

busy p...

OK
```

I'm not sure whether the SSL connections are configured correctly.

What's going on?

**Comment by xcguang** [comment]
Hi,
It looks the command you send is correct. 
Maybe there are other blank characters following `AT+CIPSSLCCONF=4,3,0,0\r\n`, and it will cause the error code and a "busy p..."

**Comment by xcguang** [comment]
Hi,
Is the issue solved?

**Comment by tvandergeer** [comment]
I haven't tested yet with the most recent version of the firmware. Did you fix anything in this respect?

**Comment by ustccw** [comment]
@tvandergeer i am not sure it there some wrong input AT command in your side.
it looks work well here.
![ESP-20200114-02](https://user-images.githubusercontent.com/24221485/72321023-ccced200-36dd-11ea-9c57-f856adcc0be0.png)

**Comment by tvandergeer** [comment]
Ok, that looks slightly better. There's still an error though. Any idea why that is?

**Comment by ustccw** [comment]
@tvandergeer cause here is no a valid link, which linkID=4

**Comment by tvandergeer** [comment]
@ustccw But this config should be set prior to setting up a link. As per [documentation](https://github.com/espressif/esp-at/blob/master/docs/ESP_AT_Commands_Set.md#cmd-SSLCCONF):
> Call this command before establish SSL connection if you want configuration take effect immediately.

**Comment by ustccw** [comment]
@tvandergeer i am so sorry for my wrong reply.

user should enable the multi-link firstly by `AT+CIPMUX=1`
then to configure, like the following: 

![ESP-20200114-04](https://user-images.githubusercontent.com/24221485/72328198-749fcc00-36ed-11ea-8178-bb33df3b8e05.png)

**Comment by tvandergeer** [comment]
@ustccw Ah, clear! Looks good. Will give it a try and report back

**Comment by xcguang** [comment]
Hi,
Is the issue solved? Can I close it?
