### ISSUE TITLE
AT port

### ISSUE THREAD

**Issue by reshma26p** [espressif/esp-at#285]
hello,
i am using esp32 wroom board
by using separate port as to flash gpio1,3 and for ATgpio16,17 working well 
 i want to use same port for flash code which is of UART0 AND pin tx gpio1 ,rx gpio3 and AT port which is given that at UART1 of pin tx gpio17 ,rx gpio16 in https://github.com/espressif/esp-at  but actually in wroom32  datasheet pin tx gpio17,rx gpio16 of UART2.
As given in https://github.com/espressif/esp-at/blob/master/docs/How_To_Set_AT_Port_Pin.md
i made that setting 
make menuconfig > Component config > ESP32-specific > UART peripheral to use for console output (0-1) > UART1
their is UART0 UART1 option but actually from data sheet gpio16,17 which is of UART2 no option
SO THAT AT COMMANDS DOES NOT GET TX

**Comment by xcguang** [comment]
The pins for UART can be configured as others. Please refer to the chapter about IO_MUX  and GPIO in the datasheet and `esp32 technical reference manual`.

**Comment by reshma26p** [comment]
YES ..but in this case how to change...i trying for change as procedure in https://github.com/espressif/esp-at/blob/master/docs/How_To_Set_AT_Port_Pin.md
make menuconfig > Component config > ESP32-specific > UART peripheral to use for console output (0-1) > UART1
NO OPTION OF UART2

**Comment by reshma26p** [comment]
@xcguang please give me response its urgent for me

**Comment by xcguang** [comment]
Why UART2?   
The port sending AT command is UART1.  gpio16,17 are not only for UART2, you can configure it for UART0 or UART1.

**Comment by reshma26p** [comment]
yes i am done settings as given but commands does not get tx instead  of i am using separate pin without change in menuconfig as gpio1,3 to flash and gpio16,17 for AT commands is working well

**Comment by xcguang** [comment]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/25979965/69853708-7f7bda00-12c2-11ea-9897-02413ae1a113.png">
Do you modify them? If so, Please `make clean & make`

**Comment by reshma26p** [comment]
yes..i did all  procedure given in https://github.com/espressif/esp-at/blob/master/docs/How_To_Set_AT_Port_Pin.md
  
  
  

----------------------------------------

**Comment by SONGjiaxiu** [comment]
Set GPIO1(TX) and GPIO3(RX) to be both the log pin and AT port pin according to the document`How_To_Set_AT_Port_Pin.md`, it works well.

![333_2](https://user-images.githubusercontent.com/26621056/69864988-1a80ae00-12db-11ea-808e-11b76de02514.png)
