### ISSUE TITLE
AT BT

### ISSUE THREAD

**Issue by reshma26p** [espressif/esp-at#286]
i want to turn on bluetooth by power on and available to discover and connectable 
and want to change bluetooth name and  settings of baud rate ,parity by AT commands from bluetooth COM port
please give response as soon as possible

**Comment by reshma26p** [comment]
please give me response

**Comment by xcguang** [comment]
turn on bluetooth by power on and available to discover and connectable
---- The default firmware does not support it

change bluetooth name and settings of baud rate ,parity by AT commands from bluetooth COM port
----- Please refer to the AT command document

**Comment by reshma26p** [comment]
i want to change name , baud rate from COM port which is getting by bluetooth pairing i.e bluetooth port

**Comment by xcguang** [comment]
Now have no such command, maybe you can customize it.

**Comment by reshma26p** [comment]
how?

**Comment by xiewenxiang** [comment]
SPP transmission has no baud rate concept and is completely dependent on the actual transmission speed of the bluetooth chip, which can be understood as 3Mbps.

If you want to set device name , you can use comand `AT+BTNAME`
