### ISSUE TITLE
AT_BLE_Pass-through_Mode

### ISSUE THREAD

**Issue by thuLssss** [espressif/esp-at#291]
When in the pass-through mode, APP breaks the link with ESP32 and then trys to re-link, and it will not find the service. At this time, we need to manually exit the pass-through mode through transmitting "+++" in the serial port, and then reconnect and enter the pass-through mode again. If we can re-link without exiting the pass-through mode? and how?

**Comment by xiewenxiang** [comment]
Please provide the version you used.

```c
AT+GMR
```
