### ISSUE TITLE
esp8266 有计划支持MQTT吗？

### ISSUE THREAD

**Issue by fengfeng0328** [espressif/esp-at#297]
请问esp8266 有计划支持MQTT吗？

**Comment by xcguang** [comment]
这个月添加上

**Comment by fengfeng0328** [comment]
多谢，请尽快支持，已与贵司商务沟通

**Comment by xcguang** [comment]
请使用 0c0bc4bf 测试，由于 8266 内存限制，使用 MQTT SSL 功能可能会失败，这个依赖于证书大小、加密套件等。

**Comment by fengfeng0328** [comment]
MQTT测试BUG：https://github.com/espressif/esp-at/issues/307

**Comment by xcguang** [comment]
如果有新的问题，提创建新的 issue，谢谢！
