### ISSUE TITLE
AT nvs_flash

### ISSUE THREAD

**Issue by LiThirteen** [espressif/esp-at#300]
请问保存AT指令配置的站模式的SSID，PASSWORD，都保存在哪个nvs_flash的命名空间中的哪些键呢，本人在AT的基础上准备在ESP8266中增加http_web_server,想跟nvs_flash中的站信息数据同步，AT中的命名空间和键是否能够告知于开发者

**Comment by xcguang** [comment]
在初始化之后，你可以通过 esp_wifi_set_config 来获取Wi-Fi信息
