### ISSUE TITLE
Apple MFI support

### ISSUE THREAD

**Issue by boyhuesd** [espressif/esp-at#304]
Hi, 

We want to use Bluetooth Classic with iOS device. 
Can we support Apple MFi with this firmware? Please support.

Best regards,
Dat.

**Comment by lhespress** [comment]
@boyhuesd Sorry, We don't support Apple MFi with Bluetooth.

**Comment by boyhuesd** [comment]
> 
> 
> @boyhuesd Sorry, We don't support Apple MFi with Bluetooth.

Thank you.
