### ISSUE TITLE
MASTER-ESP32-MQTT只能发送一次消息，不返回OK

### ISSUE THREAD

**Issue by fengfeng0328** [espressif/esp-at#307]
AT+MQTTPUB=0,"thinker-pr01","HelloWorld",0,0

busy p...

busy p...

busy p...

busy p...

**Comment by fengfeng0328** [comment]
刚刚测试了多个分支，都发现这个问题，在ESP32上面，请提供可用分支

**Comment by ustccw** [comment]
@fengfeng0328 当 QoS 为 0 时，问题确实存在，请先使用 QoS1 测试: 
`AT+MQTTPUB=0,"thinker-pr01","HelloWorld",1,0`
我们内部已经修复了，很快也会同步到 github,

**Comment by fengfeng0328** [comment]
请问QoS0的修复版本什么时候能开放出来，我们的应用场景需要使用到Qos0

**Comment by ustccw** [comment]
@fengfeng0328 please try with latest version. It has fixed.

**Comment by xcguang** [comment]
Hi,
Is the issue solved? Can I close it?
