### ISSUE TITLE
where to donwload AT Firmware 2.0 for ESP32 (but with included MQTT)

### ISSUE THREAD

**Issue by valoni** [espressif/esp-at#309]
i downloaded ready AT Firmware for ESP32 v2.0 but there not included MQTT commands.
where i can download variant that include MQTT as part of AT Commands.

regards,
VALONI

**Comment by ustccw** [comment]
@valoni The released AT firmware does not contain MQTT features.
user can use MQTT by compiling AT SDK, following by [README.md](https://github.com/espressif/esp-at/blob/master/README.md)

**Comment by ustccw** [comment]
If you're not interested in compiling。You could provide me your module type, I will provide a AT fireware according your module, here.

**Comment by valoni** [comment]
i have an ESP32s module (ESP32-WROOM-32 [with default 4 Mb flash , 540 kb sram])
or exactly ESP32-DevKitC

**Comment by kurta999** [comment]
Im interested too. Anyway consider release them with MQTT and BT, or create another releases where those are enabled by default. That would help for plenty of people, including me. Thanks.

**Comment by ustccw** [comment]
@valoni Please download the bin from address 0x0, it will work on ESP32-WROOM-32.
[target.zip](https://github.com/espressif/esp-at/files/4001174/target.zip)

**Comment by ustccw** [comment]
@valoni @kurta999 As the issues 284 said, https://github.com/espressif/esp-at/issues/284, We have a guidance about AT connect to AWS, but it is written in Chinese.
You also could take a look at [AT commands](https://github.com/espressif/esp-at/blob/master/docs/ESP_AT_Commands_Set.md)

In fact, MQTT based on TLS depend on certificates, So it is recommended that you compile AT firmware according to [README.md](https://github.com/espressif/esp-at)

**Comment by valoni** [comment]
> Im interested too. Anyway consider release them with MQTT and BT, or create another releases where those are enabled by default. That would help for plenty of people, including me. Thanks.

I'm too

**Comment by valoni** [comment]
> @valoni @kurta999 As the issues 284 said, #284, We have a guidance about AT connect to AWS, but it is written in Chinese.
> You also could take a look at [AT commands](https://github.com/espressif/esp-at/blob/master/docs/ESP_AT_Commands_Set.md)
> 
> In fact, MQTT based on TLS depend on certificates, So it is recommended that you compile AT firmware according to [README.md](https://github.com/espressif/esp-at)

can i use MQTT Based on TLS with this bin file that you provided to me

**Comment by ustccw** [comment]
> > @valoni @kurta999 As the issues 284 said, #284, We have a guidance about AT connect to AWS, but it is written in Chinese.
> > You also could take a look at [AT commands](https://github.com/espressif/esp-at/blob/master/docs/ESP_AT_Commands_Set.md)
> > In fact, MQTT based on TLS depend on certificates, So it is recommended that you compile AT firmware according to [README.md](https://github.com/espressif/esp-at)
> 
> @ustccw thank you for compile bin file
> butt can i use MQTT Based on TLS with this bin file that you provided to us

If there is no a certificates auth, it can works on TLS, otherwise, user has to compile the AT firmware.

**Comment by valoni** [comment]
now i was able to compile via ubuntu 1806 ova (with vmware) ,
thanks a lot for help .
