### ISSUE TITLE
esp - password on ubuntu1804.ova

### ISSUE THREAD

**Issue by valoni** [espressif/esp-at#318]
since i used vmware workstation 15.x i tried to install vmware tools for mymachin to be able to use drag n drop for copy of binary compiled files so how to install vmware tools on the 

virtual machine (for windows 64bits user): http://download.espressif.com/esp_share/env/ubuntu1804.ova

![image](https://user-images.githubusercontent.com/238540/71973378-20897900-320f-11ea-9bda-9ffa95885221.png)

or how to re-login after screen saver ...

**Comment by xcguang** [comment]
the password is: 1234567890

**Comment by valoni** [comment]
thanx a lot it work fine ..
