### ISSUE TITLE
Compiling AT failed - IOError: C:/msys32/home/Ati/esp/esp-idf/Kconfig:59. Could anybody send me binaries with BT Classic?

### ISSUE THREAD

**Issue by kurta999** [espressif/esp-at#319]
I tried to compile it myself and this is the result.

https://www.esp32.com/viewtopic.php?f=13&t=13777

Before this is fixed, could anybody send me pre-compiled AT with Bluetooth Classic + MQTT enabled? My priority is on BT Classic, if MQTT not included it doesn't matter.

**Comment by xcguang** [comment]
[artifacts-31.zip](https://github.com/espressif/esp-at/files/4038297/artifacts-31.zip)
You can try this.

**Comment by kurta999** [comment]
Thank you for helping me out.
Does this release requires WROVER, classic BT only works with WROVER?

Since log says:  <ESC>[0;31mE (750) cpu_start: Failed to init external RAM!<ESC>[abort() was called at PC 0x40081437 on core 0

**Comment by xcguang** [comment]
Could you try compile firmware using the latest master branch? Before compiling, you'd better remove sdkconfig file, and then `make`

**Comment by kurta999** [comment]
You also mean latest for ESP-IDF or I should use 3.3 as before?

**Comment by xcguang** [comment]
Hi,
Yes, the old branch is based on IDF v3.3, and there is a compiling issue you mentioned.
Please use the latest master branch, and make sure you delete sdkconfig file in the project before you compile it. Or you can enable `CONFIG_SPI_FLASH_USE_LEGACY_IMPL` in menuconfig by yourself

**Comment by kurta999** [comment]
Thanks!

Now I sucessfully compiled it on Ubuntu, on windows I was unable to do it.

**Comment by kurta999** [comment]
Now it says that partition is too big for ota_0. But If I use your build, it accepts at firmware but this is the output. I would be very glad if it was working to replace our laird BT chips to ESP in future.

https://gtfkephost.hu/files/2020/03/15/lkzem1yi76.png

**Comment by xcguang** [comment]
How do you download the firmware? Can you give a screenshot?

**Comment by kurta999** [comment]
https://gtfkephost.hu/files/2020/03/16/e1xs1i2oi9.png

**Comment by kurta999** [comment]
Any ideas please?

**Comment by Emiel84** [comment]
Seems that enabling BT classic is not as simple as following the online instructions.
I'm trying to get this to work and spend many days already on this aswell.
Why was there not decided to make a release including BT classic support ?

**Comment by xcguang** [comment]
May I close this issue？

**Comment by kurta999** [comment]
The main issue is solved but BT still doesn't work so can be closed. It is possible please create another release with BT and all functions enabled for ESP Wrover in the future please? Thanks.

**Comment by xcguang** [comment]
In the next release, we will enable it for WROVER32 module.
