### ISSUE TITLE
ESP AT is not true response 

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#320]
HELLO. I have a problem with at command. I couldnt do correctly ESP32 AT firmware. After firmware adding finish I connected ttl converter to esp's 16th and 17th pins. What I transmit that is coming same.
![image](https://user-images.githubusercontent.com/40715973/72054931-f7ceb580-32da-11ea-839f-863352c1dbcd.png)
![image](https://user-images.githubusercontent.com/40715973/72054979-0c12b280-32db-11ea-8498-15dad29bb390.png)
Can  you help me pls. My device is ESP32 Devkitc V4.

**Comment by hiflord** [comment]
Also I see 'ready' when I push en button. 
![image](https://user-images.githubusercontent.com/40715973/72058307-f3a59680-32e0-11ea-81c5-998994f7be0b.png)

**Comment by xcguang** [comment]
[QCOM.zip](https://github.com/espressif/esp-at/files/4040056/QCOM.zip)
Could you try this tool?

**Comment by hiflord** [comment]
![image](https://user-images.githubusercontent.com/40715973/72064376-c6f77c00-32ec-11ea-975b-9aee59666889.png)
![image](https://user-images.githubusercontent.com/40715973/72064527-1b026080-32ed-11ea-89f6-8d58657e8208.png)
Same. It is returning What I send.

**Comment by hiflord** [comment]
When I do send with enter It is done. Nearly 1 month I am working on it. It is need <CR> end of command. 
![image](https://user-images.githubusercontent.com/40715973/72065816-27d48380-32f0-11ea-8363-b803fd14ffa3.png)
Thank you so much! Have a better life

**Comment by xcguang** [comment]
Please choose this
<img width="683" alt="image" src="https://user-images.githubusercontent.com/25979965/72123569-a555cd80-339c-11ea-895e-1ba06ac995f7.png">

**Comment by hiflord** [comment]
When I send at commands, the same command coming first. After that at command answer is coming. Is it normal?
![image](https://user-images.githubusercontent.com/40715973/72126935-feaf0400-337e-11ea-8fe6-87501e238e7e.png)
Thesee all responses of wifi module. I send data AT command from nucleo-l073rz and I am watching with ttl's receiver root.
