### ISSUE TITLE
AT+BLEGATTCWR  how to send sequence of bytes as hex values

### ISSUE THREAD

**Issue by marcrupprath** [espressif/esp-at#324]
A typical command / value set i have to send to my peripheral charactersistics lokks like:
 uint8_t SendData[]={0x08,0x00,0x81,0x00,0x10,0x51,0x00,0xA0};

How to send the number of hex bytes using BLEGATTCWR write what would be the correct form
i have to type in when prompt appears  in terminal programm i use for test?

Thanks in advance

**Comment by xiewenxiang** [comment]
All you need to do is specify a length of 8 bytes and then enter the data.

**Comment by marcrupprath** [comment]
Hello,
i am sorry but that was not the question:
The question is:
After i specified lenghth , what is correct spelling at prompt.
Example: When i send "AAAAAAAA" i receive :4141414141414141 > HEX representation of my string send, thats ok but When i have to send hex values like 0x08,0x00,0x81,0x00,0x10,0x51,0x00,0xA0

How to type in at prompt so that they are reveived as : 0x08,0x00,0x81,0x00,0x10,0x51,0x00,0xA0

What must the input string  at the prompt look like, would you please give me a tested example on how to send fex values, thank you

**Comment by xiewenxiang** [comment]
Hi,
Did you use the Serial port tools and input the command to test it? 
If so, you can do as this:

 - Select the input format of the serial tool as string.
 - Input command `AT+BLEGATTCWR=<conn_index>,<srv_index>,<char_index>[,<desc_index>],8`
 - then, you will get the response `>`
 - Select the input format of the serial tool as HEX, and input the hex value `08008100105100A0`

**Comment by marcrupprath** [comment]
Thanks,
i will try if i ahev time.
meanwhile i changed concpt.
