### ISSUE TITLE
How to set 32 byte Service and Characteristic uuid to esp32

### ISSUE THREAD

**Issue by vijaya-karagi** [espressif/esp-at#337]
how to set 32 byte Service and Characteristic uuid through "AT Commands" for ESP32 BLE using arduino mega 2560 or firebeetle-esp32 board?

**Comment by xcguang** [comment]
I'm not sure if arduino mega 2560 and firebeetle-esp32 board support ESP AT commands.

**Comment by xiewenxiang** [comment]
You can change the length of the UUID to 32 bytes by yourself.

[ble service](https://github.com/espressif/esp-at/blob/master/components/customized_partitions/raw_data/ble_data/example.csv)

**Comment by xcguang** [comment]
Is the issue solved? May I close it?
