### ISSUE TITLE
MQTT ESP32 setup

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#339]
Hello. I have graduate project about IoT using with esp32. I need to setup mqtt broker with AT commands. I dont know which AT commands I should use. so Is there any document about it? I couldnt find can you help me please?

**Comment by xcguang** [comment]
There are 3 blogs in Chinese, they may be helpful for you.
- AT+MQTT overview: https://blog.csdn.net/espressif/article/details/101713780
- Azure IoT: https://blog.csdn.net/espressif/article/details/103736743
- AWS IoT: https://blog.csdn.net/espressif/article/details/101714951

**Comment by hiflord** [comment]
AT+MQTTUSERCFG=<LinkID>,<scheme>,<"client_id">,<"username">,<"password">,<cert_key_ID>,<CA_ID>,<"path">
I couldnt work it.
![image](https://user-images.githubusercontent.com/40715973/74005808-10d68f00-498b-11ea-8563-a47a4925caf8.png)
AT+MQTTUSERCFG=0,1,"","mrijxgpu","zPx3ho...",0,0,""\r\n 
Can you say what is my client_id?
![image](https://user-images.githubusercontent.com/40715973/74006123-c43f8380-498b-11ea-8139-2ca3c8b77c7c.png)
I see always ERROR return. Please help me

**Comment by hiflord** [comment]
Whole mqtt command gives me error. 
![image](https://user-images.githubusercontent.com/40715973/74012632-c1e52580-499b-11ea-9159-4ce4032dcf1e.png)

**Comment by xcguang** [comment]
Please compile firmware using the latest master branch by yourself. 
@ustccw

**Comment by hiflord** [comment]
Thank you for help @xcguang But I have latest firmware
![image](https://user-images.githubusercontent.com/40715973/74019249-65d4ce00-49a8-11ea-9d8e-a0d94f3e21b5.png)

**Comment by xcguang** [comment]
The latest release firmware does not support MQTT command. Currently you have to compile it by yourself. It will be enabled by default in the next release version.

**Comment by hiflord** [comment]
When will you publish new release? And is there any document to compile it by myself? Then you can close. Thank you btw

**Comment by xcguang** [comment]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/25979965/74029548-e1a23b00-49e7-11ea-99b3-901f67ea26d0.png">

If you use virtual box, you can try ubuntu1804.ova, which we have setup compile environment

Or you can try the bin [artifacts-5.zip](https://github.com/espressif/esp-at/files/4170736/artifacts-5.zip)
I will close this issue, if you have any other question, please create new issue
