### ISSUE TITLE
Adresses for at command firmware

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#340]
You sent me a firmware but I dont have whole adresses.
bootloader.bin: 0x1000
at_customize.bin: 0x20000
server_cert.bin: 0x24000
server_key.bin: 0x26000
server_ca.bin: 0x28000
client_cert.bin: 0x2a000
client_key.bin:0x2c000
client_ca.bin: 0x2e000
phy_init_data.bin: 0xf000
esp-at.bin: 0x100000
partitions_at.bin: 0x8000
Theese are some of your send files of adresses. I need adresses for others. Can you help me about it?
![image](https://user-images.githubusercontent.com/40715973/74032674-9b3be480-49c5-11ea-9f5c-cacfd91892f8.png)
![image](https://user-images.githubusercontent.com/40715973/74032695-b1e23b80-49c5-11ea-9d12-b003d7634e3a.png)

**Comment by xcguang** [comment]
Please refer to download.config

**Comment by hiflord** [comment]
Thank you
