### ISSUE TITLE
AT+GMR中AT版本

### ISSUE THREAD

**Issue by LiThirteen** [espressif/esp-at#342]
今日更新了项目版本，使用AT+GMR指令查询一下版本，
内容：AT version:2.1.0.0-dev(debug - Jan 20 2020 06:16:56)，
而不是像以往的版本内容一样
内容：AT version:2.1.0.0-dev(f7f172e - Dec 4 2019 08:43:54)，
更新后的将at core核心版本号改为了debug，请问这是通过设置的还是作者就是这么写的，
个人认为还是显示核心版本号会方便区分

**Comment by xcguang** [comment]
你是不是使用了给你的临时版本的 at core？可以 git status 看看 at core 文件是否有改动？

**Comment by LiThirteen** [comment]
@xcguang 
![at core](https://user-images.githubusercontent.com/37564450/74133346-590fde80-4c23-11ea-9c53-e63d529f7ab9.png)
