### ISSUE TITLE
TLS MQTT Server Setup

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#343]
Hello. I am trying to setup MQTT server via TLS. I can create TCP MQTT server but I couldnt create TLS MQTT server. I used this at commands for setup TCP mqtt server. It is working fine

AT+MQTTUSERCFG=0,1,"mrijxgpu","mrijxgpu","zPx3hoYuBRl5",0,0,""
AT+MQTTCONN=0,"hairdresser.cloudmqtt.com",16743,0
AT+MQTTSUB=0,"topic1",1
AT+MQTTPUB=0,"topic1","test1",1,0
AT+MQTTCLEAN=0

I will try to use thesee at commands for TLS MQTT server,
AT+CIPSNTPCFG=1,8,"ntp1.aliyun.com"
AT+CIPSNTPTIME?
AT+MQTTUSERCFG=0,3,"mrijxgpu","mrijxgpu","zPx3hoYuBRl5",0,0,""
AT+MQTTCONNCFG=0,0,0,"lwtt","lwtm",0,0
AT+MQTTCONN=0,"hairdresser.cloudmqtt.com",16743,0
AT+MQTTSUB=0,"topic",1
AT+MQTTPUB=0,"topic","test",1,0
AT+MQTTCLEAN=0
But the second at commands part When I send AT+MQTTCONN=0,"hairdresser.cloudmqtt.com",1883,0
It gives me error. What is wrong? I couldnt fix it. Please help!

**Comment by ustccw** [comment]
@hiflord it looks ssl handshake failed.
Had you instead of CA certificates and re-compile?
here is a demo will show you how to connect to AWS by SSL, but it was written by Chinese.
[ESP-AT 应用: AT+MQTT 对接亚马逊云](https://blog.csdn.net/espressif/article/details/101714951)

One more, you could collect the AT log for checking whether ssl handshake failed.

**Comment by hiflord** [comment]
I am not good about network knowladge but here is my log
![image](https://user-images.githubusercontent.com/40715973/74404394-6acbce80-4e3b-11ea-8b96-9d28e233e32f.png)
If I try to setup normal TCP server it is successfull. Here is my succesfull log
![image](https://user-images.githubusercontent.com/40715973/74404507-c1d1a380-4e3b-11ea-8ca8-5daba8378168.png)
I tried AWS and it is failled too. What am I doing wrong?

**Comment by hiflord** [comment]
Should I send any certificate for TLS?
![image](https://user-images.githubusercontent.com/40715973/74423952-2a337b80-4e62-11ea-9a54-9a4807900e99.png)
![image](https://user-images.githubusercontent.com/40715973/74424019-46cfb380-4e62-11ea-845c-165adc81edb1.png)

**Comment by hiflord** [comment]
I need document about load certificates.

**Comment by ustccw** [comment]
@hiflord For easily understand, you could connect to your MQTT broker on PC firstly, via mosquitto or mqttfx.  
then try with ESP32, maybe it could help you to understand.

**Comment by hiflord** [comment]
Thank you for advice. it is logical.
