### ISSUE TITLE
ESP-32 AT+CWJEAP

### ISSUE THREAD

**Issue by nathandickey** [espressif/esp-at#344]
When trying to connect to the eduroam (WPA2 Enterprise) network at my school with the AT+CWJEAP command I always the "+CWJEAP:Timeout" error. Anyone know what causes this and what I need to do to be able to connect?

format: AT+CWJEAP="eduroam",1,"username@school.edu","username","password",2

**Comment by xcguang** [comment]
@ustccw Please give some advice

**Comment by ustccw** [comment]
@nathandickey have you replaced the CA certificate, and re-compile AT?

**Comment by ustccw** [comment]
@nathandickey it looks like a certificate issue.

**Comment by nathandickey** [comment]
@ustccw do I need to generate a new cert or have one provided by my school's IT? Forgot to mention earlier that my school uses PEAP/MSCHAPv2 for the eduroam network.

**Comment by ustccw** [comment]
@nathandickey you could have a try with `AT+CWJEAP="eduroam",1,"username@school.edu","username","password",0`.

you could query a certificate from your school IT department if school network enables a certificate authorization.
