### ISSUE TITLE
AT+CIPSSLCCONF=0 returns ERROR

### ISSUE THREAD

**Issue by markreds81** [espressif/esp-at#345]
I'm unable to get AT+CIPSSLCCONF=0 command to work on my ESP32 module. It returns always error. I'm using AT+CIPMUX=0

AT version:2.0.0.0(e44648c - Nov  4 2019 02:18:57)
SDK version:v3.3
compile time(7cac7ad):Nov  4 2019 06:11:40
Bin version:2.0.0(WROOM-32)

**Comment by SUNLUXIN** [comment]
We did not reproduce this problem, could you provide some logs?

log:
//
AT+GMR
AT+GMR
AT version:2.0.0.0(e44648c - Nov  4 2019 02:18:57)
SDK version:v3.3
compile time(7cac7ad):Nov  4 2019 06:11:40
Bin version:2.0.0(WROOM-32)
OK
AT+RESTORE
AT+RESTORE
OK
ready
AT+CWMODE=1
AT+CWMODE=1
OK
AT+CWJAP="MERCURY_2414","1234567890"
AT+CWJAP="MERCURY_2414","1234567890"
WIFI CONNECTED
WIFI GOT IP
OK
AT+CIPMUX=0
AT+CIPMUX=0
OK
AT+CIPSSLCCONF=0
AT+CIPSSLCCONF=0
OK
//
