### ISSUE TITLE
pem.key to bin

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#346]
Hello. I am Ali. I need to convert these files to bin file. How can I do that. Thanks for help
![image](https://user-images.githubusercontent.com/40715973/74503837-4cc9a100-4f03-11ea-828a-e4b8e629c3f3.png)

**Comment by xcguang** [comment]
Please refer to https://github.com/espressif/esp-at/blob/master/tools/README.md#2-pki-bin

**Comment by hiflord** [comment]
Thank you. I converted.
