### ISSUE TITLE
NO CA FOUND

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#347]
I am getting this error:
![image](https://user-images.githubusercontent.com/40715973/74508563-602f3900-4f10-11ea-9b24-b6d5d0cf043b.png)
I added bin files to true adress which in below.
![image](https://user-images.githubusercontent.com/40715973/74508543-53aae080-4f10-11ea-85be-17c08a269c73.png)
What is my fault? Help please

**Comment by hiflord** [comment]
I used these ofsets
client_cert	0x40	5	0x2a000	8K
client_key	0x40	6	0x2c000	8K
client_ca	        0x40	7	0x2e000	8K
and my at command set is
AT+CWMODE=1
AT+CIPMUX=0
AT+CWJAP="Test","helloworld"
AT+CIPSNTPCFG=1,1,"us.pool.ntp.org"
AT+CIPSNTPTIME?
AT+CIPSSLCCONF=3,0,0
and when I send 
AT+CIPSTART="SSL","a2u7s0al75g2nd-ats.iot.us-east-2.amazonaws.com",8443
It returns NO CA FOUND

**Comment by xcguang** [comment]
Please do not change the partition name. And your amazon_ca looks 14KB, but the size of partition client_ca is 8K

**Comment by hiflord** [comment]
What should I do for that size? What do you mean dont change the partition name? 
![image](https://user-images.githubusercontent.com/40715973/74526591-bada8c00-4f34-11ea-8896-0948ccffbde0.png)

**Comment by hiflord** [comment]
[download.txt](https://github.com/espressif/esp-at/files/4204271/download.txt)
I am using these adresses

**Comment by hiflord** [comment]
I increased ofset but still same error and I changed my bin file's name.
![image](https://user-images.githubusercontent.com/40715973/74533592-fda36080-4f42-11ea-87ec-1a1e57fabea0.png)
still it is not working.
![image](https://user-images.githubusercontent.com/40715973/74533641-13188a80-4f43-11ea-94a3-5bfc300d145e.png)
Please help

**Comment by hiflord** [comment]
@xcguang @ustccw ?

**Comment by hiflord** [comment]
![image](https://user-images.githubusercontent.com/40715973/74709486-52d7be80-5230-11ea-84ef-4d51e25565ea.png)
UART1 and UART0 log

**Comment by xcguang** [comment]
Please provide your at_customize.csv

**Comment by hiflord** [comment]
I dont use your esp-idf library. I am connecting esp32 with stm and there is uart wire between esp32 and stm. What is relevant at_customize.csv ? Do you mean at_customize.bin?

**Comment by hiflord** [comment]
I fixed it. CA certificate should download with click save as. After that move my certificate file had 1k size. .docx is making file's size too high. Thank you.
