### ISSUE TITLE
ESP8285 Partition Table 1MB

### ISSUE THREAD

**Issue by hallard** [espressif/esp-at#348]
I there,
I'd like to flash AT Firmware to an ESP8285 so I understand I will need to remove some features to fit.

1st I removed OTA but when I'm trying to compile (setup 1M with `make menuconfig`) but it's not "sync" with `partitions_at.csv` that is default with OTA and 2MB
```
Partitions defined in '/Users/charles/esp/esp-at/module_config/module_esp8266_default/partitions_at.csv' occupy 2.0MB of flash (2097152 bytes) which does not fit in configured flash size 1MB. Change the flash size in menuconfig under the 'Serial Flasher Config' menu.
```

Could anyone could help me telling me what I need to put in the file `partitions_at.csv`  for ESP8285 (1MB)

Currently it's 
```
# Name,   Type, SubType, Offset,  Size
otadata,data,ota,0x9000,8K
phy_init, data, phy,0xf000,0x1000
ota_0,app,ota_0,0x10000,0xE0000
at_customize,0x40,0,0xF0000,0x20000
ota_1,app,ota_1,0x110000,0xE0000
nvs,data,nvs,0x1F0000,0x10000
```

Thanks

**Comment by xcguang** [comment]
Solved it in https://github.com/espressif/esp-at/issues/351
