### ISSUE TITLE
CAN'T CONNECT AWS

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#349]
Hello. I'm Ali. I couldnt connect AWS with at commands via UART1. These are my AT command order:
![image](https://user-images.githubusercontent.com/40715973/74737153-55084000-5265-11ea-99a0-367e65c9da63.png)
What is my fault here? Also how can I learn what is my client ID and name and password? please help.
I am sure to I added certificates correctly.

**Comment by hiflord** [comment]
@xcguang @ustccw

**Comment by ustccw** [comment]
@hiflord Hi, could you please test connection via MQTT tool, mqttfx or mosquitto or others firstly.

the log looks like a connection timeout.

**Comment by hiflord** [comment]
I will try but can I ask one question? 
![image](https://user-images.githubusercontent.com/40715973/75319145-20a40d80-587d-11ea-8d51-68ee6a25ebcf.png)
These are my certificates folder. client_key.bin is private.pem.key's bin extension version 
![image](https://user-images.githubusercontent.com/40715973/75319429-b2ac1600-587d-11ea-815a-ef1706b9a247.png)
I just wanna know that I should change it with client_key.bin or mqtt_key.bin?

**Comment by ustccw** [comment]
@hiflord here is a guide about how to connect to AWS by AT: https://blog.csdn.net/espressif/article/details/101714951, but it was wrotten by Chinese.
you could take a look.

**Comment by xcguang** [comment]
Is the issue solved? May I close it?

**Comment by hiflord** [comment]
can you wait a little more. I had some works to do.

**Comment by xcguang** [comment]
If this issue is solved, I suggest you close it, and if you have any other question, you can create a new one.
