### ISSUE TITLE
esp-at如何使用4M的flash

### ISSUE THREAD

**Issue by LiThirteen** [espressif/esp-at#355]
将项目上2Mflash设置成4M需要修改哪些配置？，使用的是ESP-12F模块，修改成4M后似乎无法获取efuse_mac，获取时程序错误无法往下执行，有时可能会执行成功，但在OTA后成功下载固件后，也无法成功启动ota1分区，修改分区如下
otadata,data,ota,0x9000,8K
phy_init, data, phy,0xf000,0x1000
nvs,data,nvs,0x10000,0xE0000
at_customize,0x40,0,0xF0000,0x20000
ota_0,app,ota_0,0x110000,0x178000
ota_1,app,ota_1,0x288000,0x178000

错误1如下：
Fatal exception (0): 
epc1=0x403116aa, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Fatal exception (0): 
epc1=0x403116aa, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Fatal exception (0): 
epc1=0x403116aa, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Fatal exception (0): 
epc1=0x403116aa, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
Fatal exception (0): 

汇编代码如下：
void call_start_cpu(size_t start_addr)
{
403116a4:	d0c112        	addi	a1, a1, -48
403116a7:	91d9      	s32i.n	a13, a1, 36
    int *p;

    extern int _bss_start, _bss_end;
    extern int _iram_bss_start, _iram_bss_end;

    esp_image_header_t *head = (esp_image_header_t *)(FLASH_BASE + (start_addr & (FLASH_SIZE - 1)));
403116a9:	fa68d1        	l32r	a13, 4031004c <_flash_cache_start+0x3c>
403116ac:	fa6931        	l32r	a3, 40310050 <_flash_cache_start+0x40>
403116af:	1022d0        	and	a2, a2, a13
403116b2:	323a      	add.n	a3, a2, a3

    vTaskDelete(NULL);
}

**Comment by xcguang** [comment]
当前 8266 不支持 2M 以后的区域执行代码

**Comment by LiThirteen** [comment]
@xcguang 是否可以将2M后的分区当作NVS Flash使用，存储网页或者其他数据？

**Comment by xcguang** [comment]
好像是可以的，你可以先试试，现在我们手里面没有大的 flash

**Comment by LiThirteen** [comment]
@xcguang  好的感谢您的答复
