### ISSUE TITLE
iot.espressif.cn平台产品的使用周期

### ISSUE THREAD

**Issue by LiThirteen** [espressif/esp-at#358]
您好，我在iot.espressif.cn创建自己的私人产品，并使用了ESP-AT中的FOTA功能，请问这个是否有使用时时长限制，时间是多长，如何延长使用周期。
![iot](https://user-images.githubusercontent.com/37564450/75658280-fdc19100-5ca2-11ea-88fc-162885af1424.jpg)

**Comment by FayeY** [comment]
您好，

想请问，您是做调试研究，还是做产品呢？如果是产品，一般会采用自己的服务器，或者租用服务器。

请知悉，谢谢。

**Comment by LiThirteen** [comment]
用于个人设备的，做测试研究用，后期可能会搭建自己的服务器，感谢您的回复
