### ISSUE TITLE
AT+MQTTUSERCFG设置阿里云mqtt-clientid时错误

### ISSUE THREAD

**Issue by Yuval-guo** [espressif/esp-at#364]
阿里云的的mqttClientId格式为clientId+"|securemode=3,signmethod=hmacsha1,timestamp=132323232|"，AT+MQTTUSERCFG命令无法识别字符串中的“，”，发送命令时返回错误，去掉“，”就正常，如何解决？

**Comment by xcguang** [comment]
`,` 前面加个转意符 `\`，如 `\,`

**Comment by Yuval-guo** [comment]
谢谢，我试试

**Comment by Yuval-guo** [comment]
非常感谢，成功了。
