### ISSUE TITLE
AT COMMAND to read the status of GPIO(high or low)?

### ISSUE THREAD

**Issue by thisisausername-rgb** [espressif/esp-at#365]
I try to make the MCU communicate with the esp32-solo-1 flashed the esp_AT firmware in the form of AT COMMAND through the UART.
Is there a AT command that can help read the status of GPIO(high or low) of ESP32?
I didn't find such AT command in official document[https://github.com/espressif/esp-at/blob/master/docs/ESP_AT_Commands_Set.md](url)

**Comment by hallard** [comment]
See #336, should be the same feature, read and write.

Not implemented yet, but should be easy, so we wait or we do a pull request, but I have no time fir this now

**Comment by danistm** [comment]
@thisisausername-rgb I did some work: https://github.com/danistm/esp-at-gpio
