### ISSUE TITLE
HTTP无法请求PBM格式文件

### ISSUE THREAD

**Issue by aithinker2222** [espressif/esp-at#367]
具体的现象如下
![image](https://user-images.githubusercontent.com/51082494/76269258-dcb4fd80-62ab-11ea-9607-678d51ebc097.png)

可以看到512后面是空白的，用打开二进制的软件可以查看这个文件的具体HEX字节为
![image](https://user-images.githubusercontent.com/51082494/76270846-a67a7c80-62b1-11ea-9da3-43da938b3654.png)

AT+HTTPCLIENT=2,0,"http://ai-thinker.oss-cn-shenzhen.aliyuncs.com/eCos/Fapiao400ppi.pbm",,,1
这个问题是无法请求数据还是指请求后的0x00数据无法在串口助手显示出来，这个有解决办法吗

**Comment by xcguang** [comment]
@songjiaxiu-espressif 请复现一下

**Comment by aithinker2222** [comment]
这个问题有最新进展吗
