### ISSUE TITLE
ESP32 WROOM Module

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#372]
I want to use ESP32 WROOM 32D wifi module. I want to control it with an stm32l0 microprocessor via uart using with AT commands. I want to know minimum pin number to communicate and which are they? Should en pin shortcut with 3.3v all the time? Also which pins should be used to update firmware inside? Do you have document for it?

**Comment by hiflord** [comment]
![image](https://user-images.githubusercontent.com/40715973/76948597-5f773180-6918-11ea-9bf3-ed020d281a16.png)
I did all of these and I can communicate with at commands. But when I try listen module's TX0 a lot of word is coming via uart. The example picture is below.
![image](https://user-images.githubusercontent.com/40715973/76948836-b250e900-6918-11ea-81ca-c89089348548.png)
If The communication is not stopped it the data is coming continuously. What is wrong can you help me? Is it normal I dont know but I think it is not normal.

**Comment by hiflord** [comment]
When if I do IO0 pin shortcut with gnd it is stopped but I dont know if I design my pcb when exactly should I do shortcut? For firmware update IO0 connected shortcut with gnd if I want to communicate it with  AT commands IO0 is pulled of from gnd.

**Comment by xcguang** [comment]
Maybe you can refer to https://www.espressif.com/sites/default/files/documentation/esp32-devkitc-v2_reference_design_0.zip
