### ISSUE TITLE
PICO_D4 wrong tx rx pin out

### ISSUE THREAD

**Issue by ShashaDDD** [espressif/esp-at#373]
In datasheet of pico-d4 module, the uart1-rx and tx is GPIO9, GPIO10, but why in 'factory_param_data' tx and rx pinout are totally make no sense ????

**Comment by xcguang** [comment]
<img width="530" alt="image" src="https://user-images.githubusercontent.com/25979965/77027533-762d8f00-69d1-11ea-8e76-d5fc84f38f4c.png">
Please read chapter 4 in esp32_technical_reference_manual.pdf
