### ISSUE TITLE
ESP32 AWS Problem

### ISSUE THREAD

**Issue by hiflord** [espressif/esp-at#374]
![image](https://user-images.githubusercontent.com/40715973/77033700-0b705980-69b9-11ea-987b-95d7118366e1.png)
I am doing it but AT+MQTTUSERCFG giving me always error. I am working on it over 1 month.
I have also done it with openssl commends
![image](https://user-images.githubusercontent.com/40715973/77034422-044a4b00-69bb-11ea-93c4-720acc0837d0.png)
![image](https://user-images.githubusercontent.com/40715973/77034349-c6e5bd80-69ba-11ea-88c5-b5ddff903041.png)
What is wrong can you help me please?

**Comment by ustccw** [comment]
@hiflord Hi, could you please provide the error code, or more logs, by `AT+SYSLOG=1`

Emm, have you re-compiled the esp-at firmware?
To verify the validity of the certificate, please enable the SNTP before connection.
```
AT+CIPSNTPCFG=1,8,"ntp1.aliyun.com"
AT+CIPSNTPTIME?
```

If the problem can not get resolved, would you mind provide all of your certificates for us to test.

**Comment by hiflord** [comment]
Hi dear @ustccw 
I tried it always before connection actually. 
![image](https://user-images.githubusercontent.com/40715973/77039758-a8d28a00-69c7-11ea-91e0-63b2db193aa8.png)
this is my aws link
a2u7s0al75g2nd-ats.iot.us-east-1.amazonaws.com
[aws_changed_binfile.zip](https://github.com/espressif/esp-at/files/4353064/aws_changed_binfile.zip)
[original_aws_files.zip](https://github.com/espressif/esp-at/files/4353065/original_aws_files.zip)
I changed pem files to bin with openssl commands not python commands
Thank you.

**Comment by ustccw** [comment]
@hiflord Hi, it looks work well.

![ESP-20200319-03](https://user-images.githubusercontent.com/24221485/77042096-12698d00-69f6-11ea-989e-725eee0ccb50.png)

From your log, maybe some wrong operations on your certficates.
Please ensure replaced the certificates by the right way again.

> error code: `0x6023` means that `AT_MQTT_CERT_LENGTH_ERROR`, all error code described here: https://blog.csdn.net/espressif/article/details/101713780

**Comment by hiflord** [comment]
Did you use my bin file right? not pem files?
![image](https://user-images.githubusercontent.com/40715973/77044033-c4da2980-69cf-11ea-8073-2cd0442ac9aa.png)

These are my adding adresses of bin files. What do you thing about adresses? Are they right adresses? How can I check that I added is  correct or not?

**Comment by hiflord** [comment]
I fixed it. I dont know how it is happened but I think The process of pem file to bin file I was using openssl commands but now I used python commands using with terminal. After that process it is fixed. Thank you <3
