### ISSUE TITLE
Wifi Init Crashes on boot

### ISSUE THREAD

**Issue by ShashaDDD** [espressif/esp-at#375]
Hi, 

I'm using the latest commit in master of esp-at and the corresponding commit of esp-idf which is release/v4.0 
after setting up the environment, I modified: `export ESP_AT_MODULE_NAME ?= PICO-D4`

here is what i got when i finish the make flash: (this even happens when using the default esp32 module)
![image](https://user-images.githubusercontent.com/14155719/77044088-c6204c00-69f9-11ea-812b-e92f0211d4a4.png)

**Comment by ustccw** [comment]
@ShashaDDD Hi, could you please providing the `AT+GMR`, and AT commands sequence you input.
