### ISSUE TITLE
AT+CIPSSLCCONF= always returns ERROR

### ISSUE THREAD

**Issue by mjessome** [espressif/esp-at#384]
Hello,

I'm having some issues with `AT+CIPSSLCCONF=2,0,0` and `AT+CIPSSLCCONF=0` on esp32.
I have generated a certificate with `python3 tools/AtPKI.py generate_bin -b build/at-ca.bin ca ca_client.pem` and have flashed it to `0x2e000`.

The command `AT+CIPSSLCCONF=2,0,0` reports `client_cert format error`, but it actually seems to work. You can see in the output below that it works for my certificate's URL, but fails BADCERT_NOT_TRUSTED for google.

```
WIFI GOT IP

OK
AT+CIPSSLCCONF=2,0,0
D (13291) nvs: nvs_open_from_partition NVM_009 1
D (13291) nvs: nvs_set maxlink 1 5
D (13292) nvs: nvs_set auth0 1 2
D (13293) nvs: nvs_set pkiid0 1 0
D (13294) nvs: nvs_set caid0 1 0
D (13294) nvs: nvs_close 16
D (13294) nvs: nvs_open_from_partition NVM_009 1
D (13295) nvs: nvs_set maxlink 1 5
D (13295) nvs: nvs_set auth1 1 2
D (13296) nvs: nvs_set pkiid1 1 0
D (13297) nvs: nvs_set caid1 1 0
D (13297) nvs: nvs_close 17
D (13297) nvs: nvs_open_from_partition NVM_009 1
D (13298) nvs: nvs_set maxlink 1 5
D (13298) nvs: nvs_set auth2 1 2
D (13299) nvs: nvs_set pkiid2 1 0
D (13300) nvs: nvs_set caid2 1 0
D (13300) nvs: nvs_close 18
D (13300) nvs: nvs_open_from_partition NVM_009 1
D (13300) nvs: nvs_set maxlink 1 5
D (13301) nvs: nvs_set auth3 1 2
D (13302) nvs: nvs_set pkiid3 1 0
D (13302) nvs: nvs_set caid3 1 0
D (13303) nvs: nvs_close 19
D (13303) nvs: nvs_open_from_partition NVM_009 1
D (13303) nvs: nvs_set maxlink 1 5
D (13304) nvs: nvs_set auth4 1 2
D (13305) nvs: nvs_set pkiid4 1 0
D (13305) nvs: nvs_set caid4 1 0
D (13306) nvs: nvs_close 20
client_cert format error

ERROR
AT+CIPSTART="SSL","my.url",443
ca_len=2167
ctx ok
CONNECT
AT+CIPCLOSE
CLOSED

AT+CIPSTART="SSL","google.com",443
ca_len=2167
ctx ok
I (15101) openssl: mbedtls_ssl_get_verify_result() return 0x8   <-- BADCERT_NOT_TRUSTED
ssl connect fail
I (15110) openssl: mbedtls_ssl_close_notify() return -0x4e
create 0 socket fail

ERROR
```

Using `AT+RESTORE` or `AT+CIPSSLCCONF=0` is required for me to be able to connect to other hosts again. When I run `AT+CIPSSLCCONF=0`, it also returns ERROR and logs `client_cert format error`.

I would appreciate any help figuring out why I am getting a "client_cert format error" here, and what the reason is for `CIPSSLCCONF` always returns ERROR even though it seems to work!

Thank you!

**Comment by ustccw** [comment]
@mjessome Please try to instead of components/customized_partitions/raw_data/client_ca/client_ca_00.crt with your google root CA.
compile esp-at and test again.

Actually, the CA certificate did not load to `esp-at` rightly.
