### ISSUE TITLE
关于使用AT-MQTT的问题

### ISSUE THREAD

**Issue by Yuval-guo** [espressif/esp-at#389]
1、在AT+MQTTCONNCFG中设置的keeplive时间是给远程服务器的，还是esp8266的。esp8266会根据keeplive时间向服务器发送心跳包吗？

2、在使用AT+MQTTCONN成功连接服务器以后，大概过5分钟多的时间，就会在串口返回“+MQTTDISCONNECTED:0”，但是远程服务器并没有断开。知道过了keeplive时间以后服务器才会断开。

3、esp-at 固件会自动发送心跳包吗？固件如何判断与服务器的连接？为何服务器在连接中，模块就返回断开的提示？

**Comment by ustccw** [comment]
@Yuval-guo 
1. `ESP8266/ESP32` will send `MQTT` `PINGREQ` according to `keepalive`, timely.

2. Please provide the 802.11 packets for us.

3. you can see the link state by `AT+MQTTCONN?`

more details see as: https://blog.csdn.net/espressif/article/details/101713780

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details. Thanks.
