### ISSUE TITLE
at指令，发送数据到云平台 AT+CIPSEND=

### ISSUE THREAD

**Issue by woshi520laoxie** [espressif/esp-at#391]
at指令，发送数据到云平台 AT+CIPSEND=
如果发送没有接收到 ‘>‘ 获取判断 ‘>‘ 失误了，能否退出本次数据的发送
1、因为有时候发送数据的时候出现串口没有接收到 '>'  或者其他的一些原因，希望终止这次数据的发送。有没有哪些指令是可以终止这次数据发送的。

**Comment by ustccw** [comment]
`AT+CIPSEND` is serial port, user should input matched length data to exit `AT+CIPSEND`

**Comment by woshi520laoxie** [comment]
如果我想主动退出这次的数据发送呢？

**Comment by ustccw** [comment]
If esp-at is in `AT+CIPMODE=1`, user can exit the send by `+++`.
Otherwise, the only way to exit send is input matched length data.

In addition, user can reboot by `AT+RST`

**Comment by woshi520laoxie** [comment]
我仅仅是想取消这次数据的发送，需要AT+RST。那还是算了。

**Comment by woshi520laoxie** [comment]
@ustccw  我目前使用的时候出现过这样的现象，往服务器发数据，<目前数据交互500ms交互一次，每次20个字节，然后有时候需要收发500个字节数据>这个时候很容出现发送指令:AT+CIPSEND=1,15，然后模块没有回应。就超时了。因为没有退出指令，还不能退出这次数据发送

**Comment by xcguang** [comment]
看下 AT+CIPSENDEX
