### ISSUE TITLE
esp32-wrover-b烧录AT固件

### ISSUE THREAD

**Issue by FaeSorceress** [espressif/esp-at#396]
如题，我从GitHub上获取到esp-at,查看到处于(HEAD -> master, tag: v2.0.0.0_esp32)，然后直接编译，最终编译成功后，uart0即烧录串口可以看到正常的打印信息“2.0.0
max tx power=78,ret=0” 。但是在at通讯串口看不到任何输出，输入AT也并无反应。我最初尝试IO16 IO17,后来查询到相关资料后又使用IO22 IO19,但是都没有任何信息。请问使用esp32-wrover-b烧录AT固件是否还需要其他特殊设置

**Comment by xiewenxiang** [comment]
先把命令口设置到 IO1 和 IO3， 让命令口和 log 都从 UART0 出来，看看是不是有 `ready` 打印，排除下是不是你接的USB转串口工具有问题。

**Comment by ChannaYu** [comment]
如果你的AT输入格式不对的话，
 AT 指令以回⻋车换⾏行行符 (CR-LF) 结尾。请注意设置串串⼝口⼯工具为 “新行模式”。
