### ISSUE TITLE
Change module from WROOM-32 to PICO-D4 or SOLO

### ISSUE THREAD

**Issue by Honzik321** [espressif/esp-at#401]
Hello,

PICO-D4 has another settings at components/customized_partitions/raw_data/factory_param/factory_param_type.csv.

My question is, what is the right  process to change to PICO-D4 dev kit or SOLO module and build ?
I made only one change in Makefile:

export ESP_AT_MODULE_NAME ?= PICO-D4

During the make defconfi, there is some warning:
Makefile:29: There is no module_config/module_pico-d4,Using module_config/module_esp32_default

During build process, there is some error:
usage: factory_param_generate.py [-h] [--platform PLATFORM] [--module MODULE]
                                 [--define_file DEFINE_FILE]
                                 [--module_file MODULE_FILE]
                                 [--bin_name BIN_NAME] [--log_file LOG_FILE]
factory_param_generate.py: error: argument --platform: expected one argument

Should I doing some next steps to define platform and change to desired module ?

Jan

**Comment by ustccw** [comment]
@Honzik321 sorry for missing it, please take a look at https://github.com/espressif/esp-at/issues/414
