### ISSUE TITLE
AT+SLEEP

### ISSUE THREAD

**Issue by Honzik321** [espressif/esp-at#403]
Hi,

AT+SLEEP command (modem or light sleep) successfully sleeps the module, but UART communication stops working even if a wake-up pin is activated.

Is somebody successful with AT+SLEEP command and wake-up to continue UART communication ? Please let me know in which configuration it works (module name, flow control activated or deactivated). I'm using SOLO module.

Thank you,
Jan

**Comment by ustccw** [comment]
@Honzik321 I am deeply sorry for my late reply, because we don't have enough time to deal with the esp-at issues and reply in time.

**Comment by ustccw** [comment]
Is it the same as issue #429
