### ISSUE TITLE
取消串口输出一些状态信息

### ISSUE THREAD

**Issue by LiThirteen** [espressif/esp-at#405]
如何取消掉输出到串口的wifi连接状态，如：
$?
ready
WIFI CONNECTED
WIFI GOT IP
以及其他的一些信息，因为不需要使用这些提示，如何才能去掉呢？

**Comment by ustccw** [comment]
@LiThirteen you can re-write the `at_port_write_data()` API, in file `esp-at/main/interface/uart/at_uart_task.c`, all the data to UART port will pass by it.  

Filter what you need.

**Comment by xcguang** [comment]
MCU 不解析就是就行了

**Comment by LiThirteen** [comment]
@xcguang 是的，我并没有去解析，只是来询问一下是否可以取消输出

**Comment by LiThirteen** [comment]
@ustccw 好的，我去试试看

**Comment by LiThirteen** [comment]
@xcguang 如果在进入透传模式，传输二进制数据时，突然向串口发送“WIFI GOT IP”，是否能够阻止该情况的发送呢？

**Comment by LiThirteen** [comment]
@ustccw  尝试了您的方法，确实是可以的

**Comment by ustccw** [comment]
> @ustccw 尝试了您的方法，确实是可以的，非常感谢

u r welcome
