### ISSUE TITLE
Need help to use flash_download_tool_v3.8.5 for flashing 

### ISSUE THREAD

**Issue by Masi2018** [espressif/esp-at#411]
Hi all,

I need to send the binary file for our production unit and I don't want to install esp-idf and instead just send them "flash_download_tool_v3.8.5" tools. However I am not sure how which binary files I need to include and what is the file address for each. I'd appreciate if some one can help me with that.

**Comment by ustccw** [comment]
@Masi2018 Hi, you can take a look.

- see the download parameters
```
make print_flash_cmd
```

- see the total download command
```
make | tail -n 1 > build/download.config && cat build/download.config
```

- combine the multi-bin into one factory bin
```
make factory_bin
```
