### ISSUE TITLE
virtual machine ubuntu1804.ova root password

### ISSUE THREAD

**Issue by Honzik321** [espressif/esp-at#413]
Hi, 
what is the root password in virtual machine ubuntu1804.ova ? I have no permission to flash the device /dev/ttyUSB0, I must change permission, but its not possible without root password.

Thank you

**Comment by ustccw** [comment]
@Honzik321 the password is in the desktop background.

**Comment by ustccw** [comment]
you can try with `1234567890`.

```
sudo chmod 777 /dev/ttyUSB0
```

**Comment by Honzik321** [comment]
Thank you it works! 

BTW, I have explored the desktop background, the password is there but I don't speak Chinese language:
![image](https://user-images.githubusercontent.com/63306413/82187955-71ac2680-98ed-11ea-8185-74fe22cd5d83.png)

**Comment by ustccw** [comment]
@Honzik321 thanks for you observation. It means the following:
- ubuntu admin password: `1234567890`
- run `./mount_share_dir.sh` on shell, mount the share directory to /mnt/share (please create share directory on windows D disk firstly)
- here are two projects in `~/project`, for `ESP32` and `ESP8266` platform. user can update the SDK by `git pull`
