### ISSUE TITLE
Feature Request:  Persistent Transparent Xmission UDP Server w/Multiple Connections

### ISSUE THREAD

**Issue by jwestmoreland** [espressif/esp-at#416]
Hello,

A suggestion/request:

Is it possible to set up (maybe in future releases) a transparent UDP Server that will support multiple clients?  Maybe a transparent multicast type of protocol configuration?

Thanks In Advance,
John W.

**Comment by ustccw** [comment]
@xcguang PTAL

**Comment by jwestmoreland** [comment]
Hello @xcguang ,

Not sure if I understand the reply - please take another look - as I don't
think there's a true multicast server (yet) in the code that would handle
not only transparent persistent transmission and/or multiple target ports
as in
a true multicast protocol configuration; maybe I just haven't seen that yet
or found that yet.  Pretty sure from what I've looked at that mDNS won't do
actual true multicast - maybe I'm wrong.

Thanks,
John W.

**Comment by xcguang** [comment]
Hi,
You can create an UDP connection with a specified port; and the remote UDP can send data to it. If the remote address is  multicast type, it will send multicast packet; as https://esp32.com/viewtopic.php?f=2&t=14247&hilit=multicast

**Comment by jwestmoreland** [comment]
@xcguang ,

Yes - the point of the question is to have this be a part of ESP-AT, and
also be persistent across boots, and also be transparent - that's the
actual point of the question/request.

Unless I'm not seeing something - this is not part of the current ESP-AT
capability; hence the question/request.

Persistence and transparency across boots are part of this question and
request - which are two important points.

I'm not just simply asking for UDP multicast service - if I was, this
question would be posted under the esp-idf forum.

Thanks,
John W.

**Comment by jwestmoreland** [comment]
@xcguang ,

Which build of ESP-AT will support multicast with the AT+CIPSTART command?
I don't see that in any of the current documentation.

I have a custom target board I designed since connectBlue's modules went
obsolete - so I can't use the build in the post you pointed out above.

Thanks,
John W.

**Comment by jwestmoreland** [comment]
Hello Again,

OK - see it here:

SHA-1: 759cf597be22f6b8ee81238161fd4d84fb853cb7

* feat: Update at core version 38662e04

- feat: Optimize socket process
- feat: Optimize cipstatus command process
- feat: AT+CIPSTART support multicast for multicast address from 224.0.0.0
to 239.255.255.255
- feat: Add command for BT COD
- feat: Add command to support light sleep

Thanks,
John W.

**Comment by xcguang** [comment]
The latest master branch should work well, you can try it.

**Comment by jwestmoreland** [comment]
AT+CIPMODE=1
AT+CIPMODE=1
<CR>
ERROR<CR>

**Comment by jwestmoreland** [comment]
AT+CIPSTART="UDP","239.192.1.2",0,123,0  <== ,2 here didn't work
AT+CIPSTART="UDP","239.192.1.2",0,123,0
local port:123<CR><CR>
change type:0<CR><CR>
CONNECT<CR>
<CR>
OK<CR>
AT+CIPMODE=1
AT+CIPMODE=1
<CR>
OK<CR>

**Comment by jwestmoreland** [comment]
Running wireshark and not seeing any multicast packets being transmitted
from the ESP32...

**Comment by jwestmoreland** [comment]
@xcguang ,

I fixed a routing issue on my test system and the ESP32 is receiving
multicast packets but it doesn't appear to be sending them - do I have to
enable mDNS or do something else to get the server working on the ESP32?

Thanks,
John W.

**Comment by jwestmoreland** [comment]
@xcguang ,

Do I need any special set up to be able to send multicast packets from the ESP32 using the 4.0 compatible ESP-AT build?

Thanks,
John

**Comment by xcguang** [comment]
Please set remote port parameter

**Comment by xcguang** [comment]
![image](https://user-images.githubusercontent.com/25979965/83516458-af25cc00-a509-11ea-9279-f2f59adf836f.png)

**Comment by jwestmoreland** [comment]
@xcguang ,

I am not seeing the +IPD,6:123455 in my log - am I missing something?

Thanks,
John

**Comment by xcguang** [comment]
> Do I need any special set up to be able to send multicast packets from the ESP32 using the 4.0 compatible ESP-AT build?

Failed to send data or not received data?

**Comment by jwestmoreland** [comment]
@xcguang ,

I have it working now - in a test mode configuration.  As soon as I have
more than one station reporting it's receiving the multicast packets OK -
I'll make a report - hopefully by the end of the day today.

Thanks,
John

**Comment by jwestmoreland** [comment]
@xcguang ,

Multicast is working - I currently have one station broadcasting the multicast packets and two stations receiving - also - the
AT+SAVETRANSLINK command is working.

I suppose you guys can add this to your next round of docs as it's extremely useful.

Thanks for the help!
John W.

**Comment by jwestmoreland** [comment]
Wanted to add this screen shot showing multicast packets being received OK...
Regards,
John W.
![MULTICAST](https://user-images.githubusercontent.com/2308903/84385523-95892200-aba4-11ea-869a-9e198035f526.jpg)

**Comment by ustccw** [comment]
@jwestmoreland We really appreciate your seriousness!
