### ISSUE TITLE
A fatal error occurred: Found 2 segments that could be irom0. Bad ELF file?

### ISSUE THREAD

**Issue by PontusO** [espressif/esp-at#421]
When trying to build for 1MB ESP8266 i get the following problem:

Generating esp8266.project.ld
LD build/esp-at.elf
esptool.py v2.8
A fatal error occurred: Found 2 segments that could be irom0. Bad ELF file?

Moving back to V2.0.0 I don't see this problem.

**Comment by ustccw** [comment]
@PontusO Hi, it looks like you firmware has exceeded the limit.
The maximum size allowed for firmware is 896KB (0xE0000), which defined in https://github.com/espressif/esp-at/blob/master/module_config/module_esp8266_1mb/partitions_at.csv

Maybe you can try to disable some AT features you would not use, to reduce firmware size.
- `make menuconfig` -> `Component config` -> `AT` - `mdns/wps/smartconfig/ping/mqtt/etc..`

**Comment by PontusO** [comment]
Hi, I tried that but I still have the same problem.  I tried disabling most of the features and still have the same issue.
Although, woudn't the linker already have thrown an error if the image was to big ?

**Comment by PontusO** [comment]
I cloned a new tree and now it works right out of the box. Not sure what I did wrong previously but all is good now.  I am closing this.
