### ISSUE TITLE
ESP32经典蓝牙 安卓手机正常，苹果手机无法获取到经典蓝牙

### ISSUE THREAD

**Issue by woshi520laoxie** [espressif/esp-at#423]
1、使用ESP32的经典蓝牙
      实际使用过程中，安卓吧版本的的蓝牙开启的时候，可以获取到经典蓝牙，但是苹果手机无法获取到经典蓝牙，这里面是有些什么要求吗？

**Comment by xiewenxiang** [comment]
`无法获取到经典蓝牙`, 指的是无法扫描到吗

**Comment by xiewenxiang** [comment]
@woshi520laoxie 
有新的信息可以同步吗？

**Comment by jerrytry1** [comment]
APPLE, CLASSIC BLUETOOTH NEED MFI, ESP32 BLUETOOTH+MFI
