### ISSUE TITLE
AT+BTNAME not saving name into NVS

### ISSUE THREAD

**Issue by sdrabb** [espressif/esp-at#425]
Hello 

From doc i got this:

The default device name is esp32, If use command to set the device name, it will be stored in NVS.
`AT+BTNAME="EXAMPLE"`

but if i restart **ESP32** after using the above **at-command** and send following commands:

`AT+BTINIT=1`     
`AT+BTSPPINIT=2`  
`AT+BTSPPSTART`   
`AT+BTSCANMODE=2`         
`AT+BTSECPARAM=3,1,"9527"` 

device name is forgotten.
How can i solve it?

**Comment by ustccw** [comment]
@xiewenxiang could you please take a look

**Comment by xiewenxiang** [comment]
This issue has been resolved and you can use the latest MASTER branch or rlease/ V2.1 branch.
