### ISSUE TITLE
8266 调试信息 sta trace 0

### ISSUE THREAD

**Issue by woshi520laoxie** [espressif/esp-at#430]
![image](https://user-images.githubusercontent.com/24913012/84968933-369a4e80-b14a-11ea-8d28-f3ce63ff0f14.png)

查看调试信息中 提示 sta trace 0

使用的at固件版本为:

接收:AT+GMR
AT version:1.5.0.0(Oct 24 2017 12:03:18)
SDK version:2.1.0(ace2d95)
compile time:Oct 24 2017 15:48:02
Bin version(Wroom 02):1.5.1
OK

**Comment by woshi520laoxie** [comment]
请问 这个信息是什么意思呢？或者有哪些文档有介绍这个调试信息是什么含义的吗？

**Comment by xiewenxiang** [comment]
@woshi520laoxie 
这个固件是你自己编译的吗

**Comment by xiewenxiang** [comment]
是不是修改了 phy_init_data.bin

**Comment by xcguang** [comment]
这个是 nonos 的 AT，这里是 RTOS 的仓库

**Comment by woshi520laoxie** [comment]
@xcguang @xiewenxiang 这个是原厂的固件，是不是不应该在这里提问，拷机的时候发现，debug口一直在发送这个，但是不知道什么意思，所以问问

**Comment by xcguang** [comment]
重新擦除 flash，使用新版本的试吧，官网有新固件，这个太老了
