### ISSUE TITLE
AT MQTT指令中的topic长度限制有没有办法改大一些？

### ISSUE THREAD

**Issue by ze9hyr** [espressif/esp-at#435]
我现在使用的是esp32的2.0.0.0版的固件， 自己使能了MQTT，但是topic的长度限制在64字节， 无法满足业务需求，请问有没有绕过这个限制的方法？

**Comment by ustccw** [comment]
@ze9hyr Hi, what i would like to suggest is to reduce and optimise the topic length.  

**MQTT** as the lightweight protocol is applied for resource constrained IOT devices,  
Memory and throughput should be considered first.  
Please know.

**Comment by ze9hyr** [comment]
> @ze9hyr Hi, what i would like to suggest is to reduce and optimise the topic length.
> 
> **MQTT** as the lightweight protocol is applied for resource constrained IOT devices,
> Memory and throughput should be considered first.
> Please know.

我这边是想连接到阿里云， topic长度上优化的可能性不大，而且阿里的topic限制是128字节。所以想问一下固件上是否有什么方式把这个长度限制改大一些

**Comment by ustccw** [comment]
@ze9hyr As far as i know, maximum topic length: 64 bytes at `aliyun`  is enough for product.

![image](https://user-images.githubusercontent.com/24221485/85980550-36853300-ba15-11ea-8a78-03315d3d51e1.png)

**Comment by ze9hyr** [comment]
@ustccw 我们需要使用到物模型， 会使用到的topic包含下图中的一些。
![image](https://user-images.githubusercontent.com/12229359/85981572-00e14980-ba17-11ea-8326-4e1ee51b32e8.png)
图中的打码部分有11字节， 而deviceName范围是4-32字节， ${tsl.event.identifer}表示的事件ID长度会由阿里生成，按不同的设备生成的长度不一致， 我这边遇到最长的是26字节， 所以确实会遇到不够的情况。

**Comment by ustccw** [comment]
@xcguang Could we consider different MQTT configurations for ESP8266 and ESP32?
