### ISSUE TITLE
ESP32 AT2.0 WiFi自动重连机制

### ISSUE THREAD

**Issue by RomeliFeng** [espressif/esp-at#438]
你好：
问题1：在使用AT+SWJAP指令连接AP时，bssid为空 reconn=1的时候。模块实际进行重连时使用的是SSID还是BSSID。
实际问题是：如果把设备从第一个AP区域移动到第二个AP区域（两个AP SSID一致 BSSID不同），会不会自动连接第二个AP（第一个AP完全没信号）。或当第一个AP还有微弱信号会连接那个AP。
问题：在2.0版固件中指令AT+SWJAP指令无法使用[\<scan_mode>]参数，请问是怎么回事？

**Comment by ustccw** [comment]
@RomeliFeng did you mean `AT+CWJAP` command?   
Could you please open an issue with only one problem.  
It looks like a little confused what you expected and what the fact.  

Please read the esp-at/docs if something not clear

**Comment by RomeliFeng** [comment]
好的。我重开两个issue
