### ISSUE TITLE
[Question] _DEF and _CUR postfixes

### ISSUE THREAD

**Issue by pstolarz-prox** [espressif/esp-at#441]
During work on some 3rd party ESP8266 WiFi driver I have encountered `_DEF` and `_CUR` family of commands (like `AT+CWMODE_CUR` and `AT+CWMODE_DEF`) which seems to be absent in this `esp-at` project. The commands are described on some Espressif ESP8266 docs like [this one](https://cdn.sparkfun.com/assets/learn_tutorials/4/0/3/4A-ESP8266__AT_Instruction_Set__EN_v0.30.pdf). On the other hand `esp-at` provides `AT+SYSSTORE` command which along with `AT+CWMODE` seem to have similar functionality like `AT+CWMODE_DEF` and `AT+CWMODE_CUR`.

What is the reason of such discrepancy?

EDIT: After some more investigation it looks like the `_DEF` and `_CUR` commands are specific for ESP8266 NonOS SDK's AT library. Does it mean they are deprecated as ESP8266 NonOS SDK is deprecated?

Thanks,
Piotrek

**Comment by ustccw** [comment]
@pstolarz-prox yeah, `AT+XXX_DEF` and `AT+XXX_CUR` serial command is deprecated now.
`AT+SYSSTORE` is recommended instead of the `_DEF` and `_CUR` feature.

About the `AT+SYSSTORE` command detail, please refer to [AT+SYSSTORE](https://docs.espressif.com/projects/esp-at/en/latest/get-started/ESP_AT_Commands_Set.html#at-sysstore-config-parameter-store-mode) doc.

> newest command as the onoff button to decide AT command save configuration into flash or not, will optimise internal code.
> At the same time, it is easier to save configuration or not for AT user.

**Comment by pstolarz-prox** [comment]
@ustccw thanks for the clarification.
The problem with `AT+SYSSTORE` command is - it's not supported by any official release yet. It's present on `master` development branch only. Are you gonna release a new version of the firmware supporting with this command in the near future?

**Comment by ustccw** [comment]
@pstolarz-prox We are conducting AT command testing and system testing internally, there will be no more change in the overall functionality.  
It will be released soon, please know.

**Comment by pstolarz-prox** [comment]
Thanks
