### ISSUE TITLE
AT Command parser issue?

### ISSUE THREAD

**Issue by gipobbe** [espressif/esp-at#446]
Here I'm again,
I think I found an unwanted behaviour about esp-at firmware. 
Basically what I found is that the payload can't contain any comma, so if I want to send a JSON with more than 1 parameter like for example: 
"{"state":{"reported":{"Speed": 2, "Lights":"ON"}}}"
it can't be done since AT+MQTTPUB always return error and the message is not sent to AWS.
If I delete the comma, the message is sent but AWS can't recognize the message as JSON (since comma is missing AWS display the message with 2 parameters as plain text). 
The last alternative I thought to continue working with JSON is to send 1 parameter per MQTT message to AWS. I'm not an IOT expert but I think this is really a sub optimal solution (or is it ok doing this way?).
BTW, I'm working with a firmware written in "C" language so the payload is full of escape characters for the ( -> " must be written as -> \\\" <-). Maybe I'm missing some escape character for the comma? Anyone has suggestions? I tried lot of combination, even using ASCII code but nothing work as I'm expecting.

**Comment by ustccw** [comment]
Maybe you can try one of the following:
1. escape by `\`
2. try with `AT+MQTTPUBRAW` command

**Comment by ctrlgeek** [comment]
I am having same issue.

This string works fine:
String pub = "AT+MQTTPUB=0,\"/v1.6/devices/new-device\",`\"{sensor:50}\"`,1,0";

But if I insert a set of inverted commas "" within the curly brackets {} as below:
String pub = "AT+MQTTPUB=0,\"/v1.6/devices/new-device\",`\"{\"sensor\":012}\"`,1,0";

the firmware returns error:
_AT+MQTTPUB=0,"/v1.6/devices/new-device","{"sensor":012}",1,0
[at-mqtt]error code:0x6044_

Tried with both AT+MQTTPUB and AT+MQTTPUBRAW

**Comment by gipobbe** [comment]
> Maybe you can try one of the following:
> 
> 1. escape by `\`
> 2. try with `AT+MQTTPUBRAW` command

Problem solved with AT+MQTTPUBRAW, I can now finally send a valid JSON with multiple parameter correctly separated by commas. Honestly I always used MQTTPUB but MQTTPUBRAW seems a lot nicer to use. I can get rid of all the escape sequences (at some point there were more escape sequences that real data on my payloads).
Thank you again ustccw for your help. You know your stuff ;)

**Comment by ustccw** [comment]
@gipobbe @ctrlgeek escape is necessary to sensitive, related to delimiters in AT command.
- `\\`: escape backslash itself
- `\,`: escape comma which used to separate each parameter
- `\"`: eacape double quotation marks which used to mark string input

**Comment by ustccw** [comment]
> I am having same issue.
> 
> This string works fine:
> String pub = "AT+MQTTPUB=0,"/v1.6/devices/new-device",`\"{sensor:50}\"`,1,0";
> 
> But if I insert a set of inverted commas "" within the curly brackets {} as below:
> String pub = "AT+MQTTPUB=0,"/v1.6/devices/new-device",`\"{\"sensor\":012}\"`,1,0";
> 
> the firmware returns error:
> _AT+MQTTPUB=0,"/v1.6/devices/new-device","{"sensor":012}",1,0 [at-mqtt]error code:0x6044_
> 
> Tried with both AT+MQTTPUB and AT+MQTTPUBRAW


@ctrlgeek Please try:
```c
AT+MQTTPUB=0,"/v1.6/devices/new-device","\"{sensor:50}\"",1,0
AT+MQTTPUB=0,"/v1.6/devices/new-device","{\"sensor\":012}",1,0
```

**Comment by gipobbe** [comment]
> @gipobbe @ctrlgeek escape is necessary to sensitive, related to delimiters in AT command.
> 
> * `\\`: escape backslash itself
> * `\,`: escape comma which used to separate each parameter
> * `\"`: eacape double quotation marks which used to mark string input

Escape comma didn't work for me earlier with MQTTPUB. But since MQTTPUBRAW works really nice I'm fine. 
@ctrlgeek 
If you're working with C firmware, try this "\"{\\\"state\\\":{\\\"reported\\\":{\\\"S\\\":0}\"" if you want to send a correct JSON.

**Comment by ustccw** [comment]
@gipobbe comma should be okey with  
`AT+MQTTPUB=0,"/v1.6/devices/new-device","{\"state\":{\"reported\":{\"Speed\": 2\, \"Lights\":\"ON\"}}}",1,0`

![image](https://user-images.githubusercontent.com/24221485/87013742-b1143680-c1fd-11ea-9b79-881353c73b8d.png)

**Comment by ctrlgeek** [comment]
> > I am having same issue.
> > This string works fine:
> > String pub = "AT+MQTTPUB=0,"/v1.6/devices/new-device",`\"{sensor:50}\"`,1,0";
> > But if I insert a set of inverted commas "" within the curly brackets {} as below:
> > String pub = "AT+MQTTPUB=0,"/v1.6/devices/new-device",`\"{\"sensor\":012}\"`,1,0";
> > the firmware returns error:
> > _AT+MQTTPUB=0,"/v1.6/devices/new-device","{"sensor":012}",1,0 [at-mqtt]error code:0x6044_
> > Tried with both AT+MQTTPUB and AT+MQTTPUBRAW
> 
> @ctrlgeek Please try:
> 
> ```c
> AT+MQTTPUB=0,"/v1.6/devices/new-device","\"{sensor:50}\"",1,0
> AT+MQTTPUB=0,"/v1.6/devices/new-device","{\"sensor\":012}",1,0
> ```

Tried your suggestion, does not solve the problem.

**Comment by ustccw** [comment]
@ctrlgeek I tried, it looks good. please try again. What is the error number?

![image](https://user-images.githubusercontent.com/24221485/87014911-5aa7f780-c1ff-11ea-83b0-ec9dbe1b53f2.png)

**Comment by ustccw** [comment]
`AT+MQTTPUB=0,"/v1.6/devices/new-device","\"{\"sensor\":012}\"",1,0` maybe is a completed JSON format in peer.

**Comment by ctrlgeek** [comment]
@ustccw @gipobbe 
Thanks for the help.

I am programming in Arduino to talk to an ESP8266 with ESP-AT firmware. My arduino code:
```
SoftwareSerial mySerial(7, 6); // RX, TX
mySerial.begin(19200);
......
String pub = "AT+MQTTPUBRAW=0,\"/v1.6/devices/new-device\",\"{\"sensor\":50}\",1,0";
mySerial.println(pub);
```
I've also tried:
`String pub = "AT+MQTTPUBRAW=0,\"/v1.6/devices/new-device\",{\"sensor\":50},1,0";
`
Both return error `[at-mqtt]error code:0x604B`

**Comment by ustccw** [comment]
@ctrlgeek wow, maybe you had confused the parameter of MQTT command `AT+MQTTPUB` and `AT+MQTTPUBRAW`

please know.

**Comment by ctrlgeek** [comment]
> @ctrlgeek I tried, it looks good. please try again. What is the error number?
> 
> ![image](https://user-images.githubusercontent.com/24221485/87014911-5aa7f780-c1ff-11ea-83b0-ec9dbe1b53f2.png)



```
AT+MQTTPUB=0,"/v1.6/devices/new-device",{"sensor":50},1,0
[at-mqtt]error code:0x6044


ERROR
```
My arduino code:
```
String pub = "AT+MQTTPUB=0,\"/v1.6/devices/new-device\",{\"sensor\":50},1,0";
mySerial.println(pub);
```

**Comment by ustccw** [comment]
it is **NOT** `AT+MQTTPUB=0,"/v1.6/devices/new-device",{"sensor":50},1,0`,   
**BUT** `AT+MQTTPUB=0,"/v1.6/devices/new-device","\"{\"sensor\":50}\"",1,0`

**Comment by ctrlgeek** [comment]
> it is **NOT** `AT+MQTTPUB=0,"/v1.6/devices/new-device",{"sensor":50},1,0`,
> **BUT** `AT+MQTTPUB=0,"/v1.6/devices/new-device","\"{\"sensor\":50}\"",1,0`

Thanks for the help

my code:
```
String pub = "AT+MQTTPUB=0,\"/v1.6/devices/new-device\",\"\"{\"sensor\":50}\"\",1,0";
mySerial.println(pub);
```

Result:
<img width="442" alt="Screenshot 2020-07-10 at 12 05 21 PM" src="https://user-images.githubusercontent.com/38683051/87115386-aad99500-c2a5-11ea-8ce4-0b3d5bdbe9a8.png">

My code:
```
String pub = "AT+MQTTPUB=0,\"/v1.6/devices/new-device\",\"{\"sensor\":50}\",1,0";
 mySerial.println(pub);
```

Result:
<img width="424" alt="Screenshot 2020-07-10 at 12 07 31 PM" src="https://user-images.githubusercontent.com/38683051/87115460-f429e480-c2a5-11ea-8fe9-89a0c722ebca.png">

**Comment by ustccw** [comment]
@ctrlgeek  It looks like a issue about `arduino code`,  cause to the AT wrong command input.

What i would like to suggest is to test `AT+MQTTPUB` command with serial port tool, such as secureCRT, cutecom, minicom, etc

Then find out what the difference between the serial port tool and your mcu.
