### ISSUE TITLE
AT+HTTPGETSIZE answer add a NULL character after size when reaching a large file(and before <CR> <LF> OK <CR> <LF>)

### ISSUE THREAD

**Issue by mougz** [espressif/esp-at#447]
Hi,

I'm currently using a ESP32-WROOM-32D with AT commands ( built from Github source, latest version with HTTP and MQTT commands)

I'm writing a C function "wrapping" the AT command  **AT+HTTPGETSIZE** and I'm testing it on 4 HTTP resources from our test server. The 4 files have very different size (from 24bytes to 200k bytes) , in order to test the behavior and the rapidity of the command depending on the size of the file. 

I have 2 different behavior depending on the size of the file. See examples below.

A 686 bytes file (screen from oscilloscope and printing of the string buffer parsing the answer)

![TEK00005](https://user-images.githubusercontent.com/22322895/87066288-9d26ff80-c212-11ea-9ec4-b2afc805dc04.PNG)
![TEK00007](https://user-images.githubusercontent.com/22322895/87066289-9dbf9600-c212-11ea-9163-29de57e76a2a.PNG)
![unknown](https://user-images.githubusercontent.com/22322895/87066415-d3647f00-c212-11ea-933a-658404f389f2.png)

A 204 792 bytes file 

![TEK00008](https://user-images.githubusercontent.com/22322895/87066705-47068c00-c213-11ea-9b8f-ad47b6141e15.PNG)
![TEK00009](https://user-images.githubusercontent.com/22322895/87066707-47068c00-c213-11ea-93d4-ce8174614cd7.PNG)
![Capture du 2020-07-09 17-36-49](https://user-images.githubusercontent.com/22322895/87066702-466df580-c213-11ea-85bf-3a036eb41da4.png)

For the "small" file, there is a' \r\n' (CR LF) just after the size in digits , and before and after the "OK".

But for the large file, there is '\0 'and 1 after the size. I've tested this command several times and the pattern is always '\0' instead of the '\r' (CR) and a random character instead of the '\n' (LF) (it is not necessary '1' )

Not only that this behavior is not really "stable", it is also interfering with the way my firmware is parsing the answer : to be sure that the AT command succeed, I always check for the "OK" answer. But the NULL character is misleading my parser which always read the "+HTTPGETSIZE" part but not the "OK" part, **because a string in C always finished with a NULL char**. I don't understand why this happens only for "large" file but it might be a clue. I did not try to find a "boundary size" delimiting the triggering of the bug.

**Comment by ustccw** [comment]
@mougz This is a very good description of the issue!  
AT fixed it internally, will auto-sync to GitHub next week.

Please test the following firmware if you need it urgently. 
[factory_WROOM-32.zip](https://github.com/espressif/esp-at/files/4903114/factory_WROOM-32.zip)

**Comment by mougz** [comment]
Thanks for your reactivity !
