### ISSUE TITLE
AT UART SPEED

### ISSUE THREAD

**Issue by zf201911** [espressif/esp-at#449]
what is the maximum uart speed  when running at ethernet and wifi command under esp32?

Thanks.

**Comment by zf201911** [comment]
I tried 2mb, and 5mb with pin tx1 and rx3, not working. break at the middle, when doing stress test.

**Comment by ustccw** [comment]
@zf201911 The maximum uart baud rate can reach to 5Mbps.
I am not sure have you enable UART hardware flow control on esp-at and PC serial port tool.

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details. Thanks.
