### ISSUE TITLE
Safety check of "double MQTT subscribe" or "double MQTT unsubscribe" does not work

### ISSUE THREAD

**Issue by mougz** [espressif/esp-at#453]
Hardware : ESP32-WROOM-32D
Firmware : AT Firmware built from GitHub source with MQTT and HTTP AT command

Hi,

I'm currently testing MQTT AT commands. I've noticed a little issue with `AT+MQTTSUB` and` AT+MQTTUNSUB` functions.

The documentation says , for `AT+MQTTSUB` : **If the topic has been subscribed before, it will prompt:ALREADY SUBSCRIBE**
And for `AT+MQTTUNSUB` : **If the topic has not been subscribed, then the AT log will prompt NO UNSUBSCRIBE**

However, when I test these safety checks (by calling the same AT command twice ie `AT+MQTTSUB:0,"something/test",0`x2 & `AT+MQTTUNSUB:0,"something/test"`x2) , the AT will always respond  "OK". 
Note that for the `AT+MQTTUNSUB` function , the second call answers " OK" but the answer is way slower (~160ms VS ~25ms for the first call) 

Is that a bug or I'm missing something here ?

Thanks in advance,
Hugo

**Comment by ustccw** [comment]
@mougz Hi, prompt information will print by `UART0 port`, other than `UART1 port`.

**Comment by mougz** [comment]
Duly noted ! I have discover the UART debug port ^^
I close the issue !
