### ISSUE TITLE
AT+BLESCAN,没有蓝牙名称出现

### ISSUE THREAD

**Issue by hwj4001** [espressif/esp-at#454]
有方法知道BLE的设备名字吗？

Command:
AT+BLEINIT=1
AT+BLESCAN=1,3

 Response:
 +BLESCAN: <BLE address>,<rssi>,<adv_data>,<scan_rsp_data>
 OK

**Comment by hwj4001** [comment]
固件：ESP32-WROOM-32 AT Bin (Latest)，
开发板：NodeMCU-32 V1.3


1.使用使用AT+BLESCAN=1,3
返回数据：addr,rssi,adv_data,scan_rsp_data,addr_type

问题1：返回的数据里面没有BLE蓝牙名称。


2.另外使用AT+BLESCAN=1,3,2,"esp"
这里面的名称是需要蓝牙的全部名称？还是名称里面包含的字符？

问题2：我使用这个指令时scan不到BLE设备。使用"nRF Connect"可以搜索到设备

**Comment by xiewenxiang** [comment]
问题1.

名字会包含在 adv_data 里面的字段中，需要自己去解析，这里只返回 raw data

问题2.

是全部名称，而且是广播数据中所包含的名字，不是services里面包含的那个名字

**Comment by xiewenxiang** [comment]
如果还问题，可以随时打开；如果有新的问题，可以随时创建新的 issues .

**Comment by scroot** [comment]
名称的位置是固定的吗？相对adv_data 偏移量是多少，长度多少
