### ISSUE TITLE
Missing header file called from app_main.c, Compiling fail on (internal/esp_wifi_internal.h: "No such file")

### ISSUE THREAD

**Issue by commcad** [espressif/esp-at#470]
## Environment
- IDF version: v2.1.0.0_esp32s2-36-gcb4fecb
- Build System:         [Make]
- Compiler version: xtensa-esp32-elf-gcc.exe (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
- Operating System:    Windows

## Problem Description
1. Compiling for "esp-at\module_config\module_esp8266_1mb"
2. Header file missing esp_wifi_internal.h, compiling fails

========Source=============
Code in: app_main.c
#ifdef CONFIG_IDF_TARGET_ESP8266
#include "internal/esp_wifi_internal.h"
#endif

=========Compiler Error============
App "esp-at" version: ESP-AT
CC build/main/app_main.o
D:/msys32/home/comcad/esp/esp-at/main/app_main.c:37:40: fatal error: internal/esp_wifi_internal.h: No such file or directory
compilation terminated.

Thank you

**Comment by zeeshan0309** [comment]
hi! have you fixed this error? i'm facing this rn
