### ISSUE TITLE
ova image size/hash 

### ISSUE THREAD

**Issue by valoni** [espressif/esp-at#486]
i tried to download OVA image but , since i don't know did i download it well or not,
i can not test this image because it doesn't import well to virtualbox , vmware player so we need a little help to make sure of proper image download (and that are capable to be imported at vmware/virtualbox without issues.

http://download.espressif.com/esp_share/env/ubuntu1804.ova
- size of image and hash of image (to be sure we downloaded properly)

**example of additional info that could help us - and that was tested by your side** 
Size : 5.27 GB
HASH : MD5 - xxxxxxx
            SHA1 - xxxxxxx
            SHA256 - xxxxxx

**tested on virtual machines**
-- virtualbox 6.1.16
-- vmware player 16.0.0

to help us to be sure we downloaded properly file

**Comment by ustccw** [comment]
@valoni sorry for late reply.
Here is a list of `md5sum`:
- [ubuntu1804.ova](http://download.espressif.com/esp_share/env/ubuntu1804.ova): `4847e100346df2c21a478925e0933617`
- [virtualbox-5.2.16.exe](http://download.espressif.com/esp_share/env/virtualbox-5.2.16.exe):`b21175b80bbbaed2e72ac62807b05b8f`
- [virtual-box-plug](http://download.espressif.com/esp_share/env/virtual-box-plug):`76ccda092e0e2f1775a4050f1ece3db7`

**Comment by valoni** [comment]
thanks for info and just downloaded : 
----------------------------------------------------------------------------
Test of : 12.01.2021
----------------------------------------------------------------------------
Here is a list of md5sum:
----------------------------------------------------------------------------
2020.03.12 09:36 - created image info
----------------------------------------------------------------------------
http://download.espressif.com/esp_share/env/ubuntu1804.ova (5.32 GB)
ubuntu1804.ova: 4847e100346df2c21a478925e0933617 (OK)
----------------------------------------------------------------------------
2019.12.18 03:24  - virtual box info
----------------------------------------------------------------------------
http://download.espressif.com/esp_share/env/virtualbox-5.2.16.exe (108 MB)
virtualbox-5.2.16.exe:b21175b80bbbaed2e72ac62807b05b8f (OK)
----------------------------------------------------------------------------
2019.12.18 03:23  - virtual box plugins
----------------------------------------------------------------------------
http://download.espressif.com/esp_share/env/virtual-box-plug.tar (52.8 MB)
----------------------------------------------------------------------------
it show to me as MD5 -> AAC23AAF9DDDE9FAE689F90BD4FEFDB9 is not 76ccda092e0e2f1775a4050f1ece3db7


![image](https://user-images.githubusercontent.com/238540/104328759-6f39b500-54ec-11eb-91d3-a3c320626032.png)

**Comment by ustccw** [comment]
@valoni Hi, i checked it again, it looks nothing different. Could you please check it again?

![ESP-20210113-01](https://user-images.githubusercontent.com/24221485/104404569-e8411700-5595-11eb-8405-6e2ab202007b.png)

**Comment by valoni** [comment]
found issues of this file

if you download with wget it download as you said but if you (without .tar extension throught wget) and if you download from browser it download something another things  (.tar extension)  ..

wget is MD5 sum as you described (18.6 MB)
browser (.tar file) is as it showed to me from browser (52.8 MB) have other MD5 hash

thanks for clarify it.

**Comment by ustccw** [comment]
just a little curious, i can not get any resources if appended the `.tar` to the end of URL.
```c
chenwu@espressif:$ wget http://download.espressif.com/esp_share/env/virtual-box-plug.tar
--2021-01-14 10:34:28--  http://download.espressif.com/esp_share/env/virtual-box-plug.tar
Resolving download.espressif.com (download.espressif.com)... 119.9.116.168
Connecting to download.espressif.com (download.espressif.com)|119.9.116.168|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-14 10:34:28 ERROR 404: Not Found.
```

**Comment by valoni** [comment]
> just a little curious, i can not get any resources if appended the `.tar` to the end of URL (same situation to my chrome browser).
> 
> ```c
> chenwu@espressif:$ wget http://download.espressif.com/esp_share/env/virtual-box-plug.tar
> --2021-01-14 10:34:28--  http://download.espressif.com/esp_share/env/virtual-box-plug.tar
> Resolving download.espressif.com (download.espressif.com)... 119.9.116.168
> Connecting to download.espressif.com (download.espressif.com)|119.9.116.168|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2021-01-14 10:34:28 ERROR 404: Not Found.
> ```

no no you don't need to create .TAR extension,
it created by iteself when on browser wh you tried to open link

http://download.espressif.com/esp_share/env/virtual-box-plug

**Comment by ustccw** [comment]
much clear, thanks for your explanation!
