### ISSUE TITLE
branch vs master compile 

### ISSUE THREAD

**Issue by valoni** [espressif/esp-at#487]
**if i use master branch with** 
git clone  --recursive https://github.com/espressif/esp-at.git

**i can not compile because have error on ethernet module** 

**if i use stable branch v2.1.0.0 with** 
git clone  -b v2.1.0.0_esp32 --recursive https://github.com/espressif/esp-at.git

there's no download of IDF and nothing available inside how to compile stable branch

**Comment by ustccw** [comment]
@valoni sorry for the late reply. esp-at had fixed ethernet compile, please try with the latest version.

**Comment by valoni** [comment]
now it compile thanx
