### ISSUE TITLE
Wakeup fail from light sleep

### ISSUE THREAD

**Issue by Honzik321** [espressif/esp-at#493]
Hello,

I found out new release ESP32-AT V2.1.0.0 20200728

In the Release Note, there is written: "SDK Update and Known issue: **Wakeup fail from light sleep**"

![image](https://user-images.githubusercontent.com/63306413/100159821-bc1aeb00-2eae-11eb-92a7-e0b1a42b406f.png)

When this issue will be solved ? I waiting for almost one year, without light sleep my project cannot be completed.

Thank you,
Jan Kijonka,
HKMeas s.r.o. developer

**Comment by xcguang** [comment]
Will you wakeup esp device by GPIO or UART?

**Comment by Honzik321** [comment]
I tested both UART and then GPIO wake-up sources. The problem is always the same, after wake-up, the UART starts to repond, but the reponses are some unspecified characters (the UART communication never wake up correctly and never respond normally). I tested the ESP32-AT V2.1.0.0. 20200728 (older release has the same problem).

**Comment by ArthurTimmermans** [comment]
I'm also having the same problem here.

**Comment by Honzik321** [comment]
Hello, any progress in this issue ? I can offer monetary reward if this issue is solved in the following SDK release. Contact me on kijonka84@gmail.com, HKmeas s.r.o. company, Czech Rep.

**Comment by Alson-tang** [comment]
@Honzik321 Hello, we are looking at the question. Thank you for your feedback.

**Comment by Alson-tang** [comment]
@Honzik321 Hello, we are looking at the question. Thank you for your feedback.

**Comment by ustccw** [comment]
@Honzik321 @ArthurTimmermans very sorry for the late reply.

It got fixed on https://github.com/espressif/esp-at/commit/0605b8fa7d55e1a9a261974c14f681453daa3777,  could you please `git pull` the latest code and test.
