### ISSUE TITLE
spiram 4/8 MB on firmware with AT Commands

### ISSUE THREAD

**Issue by valoni** [espressif/esp-at#500]
how to create AT Firmware and include external SPIRAM as part of AT Firmware RAM. 

- AT Firmware use default RAM of MCU but if we have boards with external ram , how to include those ram on firmware ??

**Comment by ustccw** [comment]
esp-at core uses the default internal RAM, other than external SPIRAM. (Internal RAM has already met the requirements of  esp-at general firmware)

It is recommended that application layer use the external SPIRAM, please follow the https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/external-ram.html for more details.
