### ISSUE TITLE
to build project under Eclipse

### ISSUE THREAD

**Issue by edbek** [espressif/esp-at#501]
Give advice, please, but how to build an "esp-at" project under Eclipse (similar to "esp-idf") ?

**Comment by ustccw** [comment]
@edbek sorry, esp-at does not support compiling under eclipse.  

Please build the esp-at project according to https://docs.espressif.com/projects/esp-at/en/latest/Compile_and_Develop/How_to_clone_project_and_compile_it.html

**Comment by edbek** [comment]
Yes, thank you.
