### ISSUE TITLE
How to disable ALPN if it was activated once

### ISSUE THREAD

**Issue by ubichsel** [espressif/esp-at#506]
Dear Espressif Team

How can I disable ALPN on a specific linkId if it was enabled before.
(cipMux=1)
I was thinking when sending:
**AT+CIPSSLCALPN=1,0** (=> returns "OK")
it will disable ALPN but the TLS connection fails after set such a command.

Sending a AT+CIPSSLCALPN? after such a command above it returns:
+CIPSSLCALPN:0

Any advise is highly appreciated.

Best regards

**Comment by ustccw** [comment]
@ubichsel Thanks for the report, will fix it this week.
