### ISSUE TITLE
Virtual machine (for windows 64bits user): Missing password of esp user

### ISSUE THREAD

**Issue by FBEZ** [espressif/esp-at#511]
The password of the "esp" user of the virtual machine should be written next to the link to download it.

![immagine](https://user-images.githubusercontent.com/19321724/109143193-08045700-7760-11eb-975b-26dfbd2a5613.png)

**Comment by ustccw** [comment]
same to https://github.com/espressif/esp-at/issues/413

**Comment by FBEZ** [comment]
duplicate
