### ISSUE TITLE
AT+BLUFI example and documentation

### ISSUE THREAD

**Issue by rudib** [espressif/esp-at#519]
I'm looking for some documentation on how to use the new `AT+BLUFI` command in the 2.1.0.0 release. I've tried various permutations of disabling/enabling WIFI/Bluetooth radios and services, but haven't yet figured it out. Does it need a custom BT server binary file or should it work with the factory binary? A fully worked example would be great.

```
AT+RST
OK
ready
AT+GMR
AT version:2.1.0.0(883f7f2 - Jul 24 2020 11:50:07)
SDK version:v4.0.1-193-ge7ac221
compile time(0ad6331):Jul 28 2020 02:47:21
Bin version:2.1.0(WROOM-32)
OK
AT+CWMODE=0
OK
AT+BLEINIT=2
OK
AT+BLUFI=1
ERROR
```

**Comment by ustccw** [comment]
@xiewenxiang please take a look

**Comment by Luxin812** [comment]
@rudib The ESP-AT firmware used to not enable the BLUFI command by default. At present, the latest ESP-AT master firmware already supports the BLUFI command by default. You can use the latest ESP-AT master to test and develop.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
