### ISSUE TITLE
Table in Documentation not showing properly.

### ISSUE THREAD

**Issue by FBEZ** [espressif/esp-at#524]
In the markdown [here](https://github.com/espressif/esp-at/commit/c198065d34c69d15390864601675ccf8a1755fc1#diff-87c6951ed2cebce5df38894758d7d7c25fb4ad626cd00dbd04b585e9e9bbaa9dR184-R199) at lines 184 and 199 there are five columns instead of two, disrupting the doc layout as shown [here ](https://docs.espressif.com/projects/esp-at/en/latest/Compile_and_Develop/How_to_understand_the_differences_of_each_type_of_module.html) .

**Comment by ustccw** [comment]
@FBEZ Thanks! will fix the docs.

**Comment by ustccw** [comment]
@FBEZ it should get fixed. thanks for the feedback.
