### ISSUE TITLE
Race condition AT+CIPSTARTEX with server

### ISSUE THREAD

**Issue by MaJerle** [espressif/esp-at#527]
Using latest (cloned today) AT commands set and tested, `AT+CIPSTARTEX` command has race condition with server mode.

`+LINK_CONN` is returned on the command, same as automatic connection info when in server mode.
This leads to improper understanding which is now server and what is now client connection.

It could be solved by looking at +LINK_CONN details but this is not right solution

**Comment by ustccw** [comment]
@MaJerle I am sorry that we have no a plan to make this breaking changes.
Because it will break the original MCU parse workflow, after OTA, and then affect the mass-produced products.

It is recommended that you still use `+LINK_CONN` to look into details.

Thanks
CW
