### ISSUE TITLE
MQTT Publish Crash on ESP8266

### ISSUE THREAD

**Issue by leungngok** [espressif/esp-at#531]
**Environment**
chip: ESP8266
version: v2.1.0.0_esp8266
connect with STM32 via UART

**Problem**
If ESP8266 receives two messages via MQTT subscription very very closely and STM32 responses with "AT+MQTTCONN" command immediately, ESP8266 will not reply until I send a command, then it will print "busy p...", "+MQTTDISCONNECTED:0" and "ERROR".

(problem updated)

**Comment by ustccw** [comment]
@leungngok please use the latest version. if the issue still exists, provide the `AT+GMR` for us.

**Comment by ustccw** [comment]
you can download the latest firmware at https://github.com/espressif/esp-at/actions/runs/782418171#artifacts
