### ISSUE TITLE
Error environment path

### ISSUE THREAD

**Issue by leungngok** [espressif/esp-at#532]
Spelling mistakes causing error environment path "ESP_AT_P**OR**JECT_PATH" in following files:
./build.py: 168
./.gilab-ci.yml: 970
./main/Kconfig: 12, 13, 14, 15

**Comment by leungngok** [comment]
New problem when "make all"
esp-at/main/interface/uart/at_uart_task.c:39:10: fatal error: at_interface.h: No such file or directory #include "at_interface.h"

**Comment by xcguang** [comment]
Now "make all" is not support in AT project
