### ISSUE TITLE
Readme Broken Link How to set AT port

### ISSUE THREAD

**Issue by FBEZ** [espressif/esp-at#537]
The link in the main readme is broken, https://github.com/espressif/esp-at/blob/master/docs/en/Compile_and_Develop/How_to_set_AT_port_pin.md  does not exist, it should be changed to https://github.com/espressif/esp-at/blob/master/docs/en/Compile_and_Develop/How_to_set_AT_port_pin.rst

**Comment by ustccw** [comment]
@FBEZ thanks, will fix it.

**Comment by FayeY** [comment]
Thanks for your report, we have fixed it with the latest master. Thanks for your interest in ESP!
