### ISSUE TITLE
HTTPCPOST: "text/plain"

### ISSUE THREAD

**Issue by xdjbobo** [espressif/esp-at#538]
## Environment

- Development Kit:      ESP32-S2-Saola-1
- V1.2
- Module or chip used:  [ESP32S2-WROOM-32]
- IDF version (run ``git describe --tags`` to find it): 
    v4.2-351-gce2c615bb
- Build System:         [CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     [Windows]
- Power Supply:         [USB]

## Problem Description

//Detailed problem description goes here.

### Expected Behavior

Header request "Content-Type: text/plain" taken into account wiyh HTTPCPOST AT command

### Actual Behavior

Header request "Content-Type: text/plain" is not takink into account. Only Content-Type: text/xml

### Steps to repropduce

1. send At command to chip to post on httpbin.org with HTTPCPOST
AT+HTTPCPOST="http://httpbin.org/post",4,1,"Content-Type: text/plain"
2. chip response:
AT+HTTPCPOST="http://httpbin.org/post",4,1,"Content-Type: text/plain"

OK

>
3. Send data to send:
test
4. chip response
+HTTPCPOST:282,{
  "args": {}, 
  "data": "test", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Content-Length": "4", 
    "Content-Type": "text/xml", 
    "Host": "httpbin.org", 
    "User-Agent": "ESP32 HTTP Client/1.0", 
    "X-Amzn-Trace-Id": "Root=1-609a741f-3ff4b2c73937431438351862"
 
+HTTPCPOST:90, }, 
  "json": null, 
  "origin": "46.247.162.249", 
  "url": "http://httpbin.org/post"
}

SEND OK

**Comment by ustccw** [comment]
@xdjbobo could you please capture the packets by wireshark.
It should get some useful information from the packets, which include the `HTTP POST` request.

**Comment by ymichon** [comment]
same issue with "Content-Type: application/json" -> the server receives: Content-Type: text/xml

**Comment by ustccw** [comment]
@ymichon @xdjbobo it got fixed at: https://github.com/espressif/esp-at/commit/3464b2631a7cd0a46f2a96eef1ef37c18d750493
please check.

**Comment by robertpoll** [comment]
It looks like this was rolled into 2.2.1.0 for ESP8266 - is the ESP32 release coming soon?

**Comment by ustccw** [comment]
@robertpoll The bugfix has been synchronized to branch https://github.com/espressif/esp-at/tree/release/v2.2.0.0_esp32,
user can self-compile ESP32-AT firmware on this branch.

The next version of ESP-AT firmware for ESP32 is in preparatory stage, but no an estimated time of release.  
Please know.
