### ISSUE TITLE
AT+CIUPDATE does not work

### ISSUE THREAD

**Issue by omerk** [espressif/esp-at#545]
## Environment
**Module or chip used:**  ESP8266 on a custom board with 64Mbit SPI FLASH. Programmed with the ESP8266 Download Tool V3.8.8:

![image](https://user-images.githubusercontent.com/9847/121721283-ff9c1600-cadb-11eb-9f04-30f1c52f8e12.png)

**Firmware used:** v2.0.0.0 - ESP8266-IDF-AT_V2.0_0.zip
```
AT+GMR
AT version:2.0.0.0(88c2cde - Jul  9 2019 11:03:33)
SDK version:v3.2
compile time:Jul 15 2019 09:23:26
Bin version:2.0.0(WROOM-02)

OK
```

## Problem Description

`AT+CIUPDATE` command fails.

The board is connected to the WiFi network and can resolve DNS:
```
AT+CIPDOMAIN="espressif.com"
+CIPDOMAIN:119.9.92.99

OK
```

Update command fails:
```
AT+CIUPDATE
+CIPUPDATE:1
+CIPUPDATE:2
+CIPUPDATE:3

ERROR
```

Happy to provide further debug info if you could advise how to get debug log output (as in #103), I don't see any debug output on either AT console or UART0?

**Comment by ustccw** [comment]
@omerk Hi, please take a look https://docs.espressif.com/projects/esp-at/en/latest/Get_Started/Hardware_connection.html#esp8266-series

Log output is from UART1, please provide the log output from UART1 and UART0.

**Comment by omerk** [comment]
@ustccw What baud rate does UART1 use? No mention of this anywhere in the docs, I see data just nothing that makes sense at common baud rates that I have tried.

**Comment by ustccw** [comment]
@omerk baud rate of UART0 and UART1 is `115200`. thanks! will add the note to docs.

in addition, how u get the this firmware.
- if the firmware is downloaded from [ESP-AT GitHub Actions](https://github.com/espressif/esp-at/actions) or [AT Binary Lists](https://docs.espressif.com/projects/esp-at/en/latest/AT_Binary_Lists/index.html), it should work
- if the firmware is generated by self-compile, please according to the guide: https://docs.espressif.com/projects/esp-at/en/latest/Compile_and_Develop/How_to_implement_OTA_update.html

**Comment by ustccw** [comment]
@omerk any updates? we added the note here at the same time: https://docs.espressif.com/projects/esp-at/en/latest/Get_Started/Hardware_connection.html

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details. Thanks.
