### ISSUE TITLE
libesp_at_core.a where is the source code?

### ISSUE THREAD

**Issue by keeturan** [espressif/esp-at#547]
I want to make changes to libesp_at_core.a source file, how can I do

**Comment by ustccw** [comment]
@keeturan sorry for that. code is closed source, no plan to open.

would you mind telling me what would u want to change, maybe I can give you some advice.

**Comment by keeturan** [comment]
I don't want to print the mqtt incoming message to the screen.

**Comment by ustccw** [comment]
@keeturan all the data sent to host mcu should go through [at_port_write_data()](https://github.com/espressif/esp-at/blob/master/main/interface/uart/at_uart_task.c#L123), user can do some preprocessing work in it.
