### ISSUE TITLE
Build Error on Windows 10

### ISSUE THREAD

**Issue by hattmt** [espressif/esp-at#549]
Hello !

I tried to build ESP-AT v2.2 with ESP-IDF 4.2 on windows 10,  for ESP32-WROOM 
but at the end I get a git tree error.

![errorwindows10atbuild](https://user-images.githubusercontent.com/56161715/124574171-824d9200-de4a-11eb-8909-0a392be3dc7c.png)

I succeded before with previous version on Debian but with the new release it was stated that we could build it on Windows.
So I tried but I failed.
Do you have a solution for this problem ?

Regards.

**Comment by charon22** [comment]
Hi ESP-AT,
I also tried to build a new ESP-AT development environment on another computer.
The same error as above occurred.

So when I tried to delete the existing project from my computer and get it again, the above error occurred.

**Comment by SquaredPotato** [comment]
I'm having the same error on MacOS, oddly enough.
Also tried a fresh download and I got the same error.

**Comment by ezlife** [comment]
modify esp-at\module_config\module_esp32_default\IDF_VERSION commit with new
commit:1e3638390964c86b0e7ef3af02973b30c58ea1be
repository:https://github.com/espressif/esp-idf.git

**Comment by ustccw** [comment]
@hattmt @charon22 @SquaredPotato @ezlife So sorry for that. But it should work now.
> This is because esp-idf release/v4.2 cannot sync to GitHub automatically before. we pushed it internally, and now it is available now.

please try again.

**Comment by SquaredPotato** [comment]
This issue is resolved for me now using the master branch, thanks!

**Comment by hattmt** [comment]
The build also worked for me, thanks !
