### ISSUE TITLE
ESP32C3 BLE Command Questions

### ISSUE THREAD

**Issue by leungngok** [espressif/esp-at#557]
## Environment

- Development Kit: ESP32-C3-M1
- IDF version: v3.4 (master branch)

## Question
There are read/write characteristic commands for BLE GATT client, but I only find set characteristic command for server. 
Any command for server to read characteristic?

Thank you.

**Comment by Luxin812** [comment]
@leungngok At present, ESP-AT master has implemented AT+BLEGATTCRD command on the server side. If you still need these functions, please test and develop based on ESP-AT master
