### ISSUE TITLE
idf.py build 出现cmake failed with exit code 1，（编译hello-world成功）

### ISSUE THREAD

**Issue by AHulyi** [espressif/esp-at#559]
PS E:\ESP32\esp-idf\examples\get-started\esp-at\esp-at> idf.py build
Executing action: all (aliases: build)
Running cmake in directory e:\esp32\esp-idf\examples\get-started\esp-at\esp-at\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 e:\esp32\esp-idf\examples\get-started\esp-at\esp-at"...
CMake Error at CMakeLists.txt:9 (string):
  string no output variable specified

CMake Error at CMakeLists.txt:13 (string):
  string begin index: 9 is out of range 0 - 0

CMake Error at CMakeLists.txt:14 (string):
  string sub-command STRIP requires two arguments.

CMake Error at CMakeLists.txt:15 (string):
  string no output variable specified

silence:0 sdkconfig:E:/ESP32/esp-idf/examples/get-started/esp-at/esp-at/module_config/module__default/sdkconfig.defaults
CMake Error at CMakeLists.txt:49 (include):
  include could not find load file:

    E:/ESP32/esp-idf/examples/get-started/esp-at/esp-at/esp-idf/tools/cmake/project.cmake

-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: E:/MinGW/mingw64/bin/gcc.exe
-- Check for working C compiler: E:/MinGW/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: E:/MinGW/mingw64/bin/c++.exe
-- Check for working CXX compiler: E:/MinGW/mingw64/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:76 (add_dependencies):
  Cannot add target-level dependencies to non-existent target "flash".

  The add_dependencies works for top-level logical targets created by the
  add_executable, add_library, or add_custom_target commands.  If you want to
  add file-level dependencies see the DEPENDS option of the add_custom_target
  and add_custom_command commands.

-- Configuring incomplete, errors occurred!
See also "E:/ESP32/esp-idf/examples/get-started/esp-at/esp-at/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1
PS E:\ESP32\esp-idf\examples\get-started\esp-at\esp-at>

**Comment by xcguang** [comment]
Please read https://docs.espressif.com/projects/esp-at/en/latest/Compile_and_Develop/How_to_clone_project_and_compile_it.html step by step
