### ISSUE TITLE
MQTT connect exception

### ISSUE THREAD

**Issue by edieruby** [espressif/esp-at#568]
ESP8266
V2.1.0.0

ESP8266 connect to treafik:2.5.1 failed with tcp over tls.
get the error log:
[11:30:43.648] [0;31mE (611272) MQTT_CLIENT: Invalid MSG_TYPE response: 6, read_len: 0[0m

treafik:2.5.1 with tcp over tls  verified is OK.

ESP8266 connect to treafik:2.4.8 with tcp over tls is OK.

guess has some problems when build connection with treafik:2.5.1 over tcp over tls.

![微信截图_20210918125539](https://user-images.githubusercontent.com/8832188/133873182-e387dc35-e2c2-45b0-9d87-ba2db6c41533.png)
![微信图片_20210918125502](https://user-images.githubusercontent.com/8832188/133873186-824be94f-194a-4d0d-9d5c-657ff7fea4b4.png)
![微信图片_20210918125441](https://user-images.githubusercontent.com/8832188/133873187-62ffa7ef-cc13-4334-ba8a-55e4f862d8e6.png)

**Comment by ustccw** [comment]
1. After connect failed, what is the output of `AT+SYSRAM?`
2. Have you tested whether MQTT over TCP connect to `docker xxx v2.5.1`

**Comment by edieruby** [comment]
go version 1.17.x  optimize the TLS handshake.
I guess ESP8266 is OOM.

![微信截图_20210923145924](https://user-images.githubusercontent.com/8832188/134466182-de214a44-251b-4109-987b-85e8821d57b4.png)
![微信截图_20210923145833](https://user-images.githubusercontent.com/8832188/134466187-60e5942d-588f-4692-96b3-8b94eb7acddc.png)

**Comment by ustccw** [comment]
yes, you are right.
