### ISSUE TITLE
`AT+CIPDNS` configuration not working during auto-connection

### ISSUE THREAD

**Issue by AdriPapa** [espressif/esp-at#574]
## Environment

- Development Kit: none
- Module or chip used: ESP32-WROOM-32D
- ESP-AT version: v2.2.0.0_esp32
- IDF version (run ``git describe --tags`` to find it): 
  ESP-IDF v4.2.2-76-gefa6eca8b8
- Build System: Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
  (crosstool-NG esp-2020r3) 8.4.0
- Operating System: Windows
- Power Supply: xternal 3.3V

## Problem Description

`AT+CIPDNS` configuration not take into account during auto-connection.

### Expected Behavior

Initial configuration:
 - Set `AT+SYSSTORE=1`:  command configuration is stored into flash.
 - Set `AT+CWAUTOCONN=1`: enable automatic connection to an AP when powered on.
 - Set `AT+CIPDNS=0`: Enable automatic DNS settings from DHCP.

Connection to an Access Point.

After reset:
 - Auto-connection to AP
 - Use DNS settings from DHCP

### Actual Behavior

After reset:
 - Auto-connection to AP
 - Use DNS 208.67.222.222

### Steps to repropduce

See AT command above.

## Debug Logs

DHCP server used when auto-reconnection exchange (with the bug):

```
11:55:01    208.67.222.222    53    UDP
11:55:02    208.67.222.222    53    UDP
11:55:04    208.67.222.222    53    UDP
```

DHCP server used connection with`AT+CWJAP`, behaviour need to be the same during auto-connexion:

```
11:50:33    192.168.80.1    53    UDP
11:50:35    192.168.80.1    53    UDP
```

**Comment by ustccw** [comment]
@AdriPapa thanks for the report. will check it in the next week.

**Comment by ustccw** [comment]
@AdriPapa this issue should be fixed on commit: https://github.com/espressif/esp-at/commit/60389a1a34016be8f8b865e403e632b403481544
please `git pull` latest code and test. If it cannot, plz reopen issue.
