### ISSUE TITLE
esp8266 cannot connect via SSL

### ISSUE THREAD

**Issue by musapinar** [espressif/esp-at#590]
Chip is ESP8266-12F
ESP is soldered to Arduino Mega via Serial1 UART
ESP is in Station mode, mux=1

I believe I read somewhere that SSL does not work with UART-WiFi passthrough?

ESP works fine and can send http requests to my remote server via TCP port 80
but fails via SSL port 443

Below are logs on Serial1 with timestamps and AT commands sent to ESP and replies from the ESP

```

12:48:10.813 -> AT+CIPSSLSIZE=4096
12:48:10.860 -> 
12:48:10.860 -> OK

12:48:36.485 -> AT+CIPSTATUS
12:48:36.532 -> STATUS:4
12:48:36.532 -> 
12:48:36.532 -> OK

12:48:46.917 -> AT+CIFSR
12:48:46.917 -> +CIFSR:STAIP,"192.168.0.15"
12:48:46.964 -> +CIFSR:STAMAC,"44:17:93:0d:6c:78"
12:48:47.010 -> 
12:48:47.010 -> OK

12:49:11.204 -> AT+CIPSNTPCFG=1,8
12:49:11.250 -> 
12:49:11.250 -> ERROR

12:49:20.549 -> AT+CIPSSLCCONF=2
12:49:20.549 -> 
12:49:20.549 -> ERROR

12:49:22.556 -> AT+CIPSSLCCONF=0
12:49:22.556 -> 
12:49:22.556 -> ERROR

12:49:25.457 -> AT+CIPSSLCCONF=0,0
12:49:25.457 -> 
12:49:25.457 -> ERROR

12:49:28.484 -> AT+CIPSSLCCONF=0,0,0
12:49:28.484 -> 
12:49:28.484 -> ERROR

12:49:49.167 -> AT+CIPSTART=0,"SSL","laf*****e.**",443
12:49:49.261 -> 
12:49:49.261 -> ERROR
12:49:49.261 -> 0,CLOSED


```

I just want to make the ESP work with SSL as I need to send http requests to my web server that only accepts connections on port 443 (port 80 is permanently redirected to 443 via http code 302)
A workaround, event if it does not verify certificates, would be appreciated.
(So far I created a secret subdomain and secret port that allows unsecure http to bypass this issue...)

```

15:09:04.765 -> AT+GMR

15:09:04.765 -> AT version:1.3.0.0(Jul 14 2016 18:54:01)
15:09:04.812 -> SDK version:2.0.0(5a875ba)
15:09:04.859 -> v1.0.0.3
15:09:04.859 -> Mar 13 2018 09:37:06
15:09:04.907 -> OK


```

**Comment by ustccw** [comment]
Sorry, here is esp-at project, but the deprecated 1.3.0.0 version is from ESP8266_NONOS_SDK project.

It is strongly recommended that you use [v2.2.1.0](https://docs.espressif.com/projects/esp-at/en/release-v2.2.0.0_esp8266/AT_Binary_Lists/ESP8266_AT_binaries.html) firmware.
