### ISSUE TITLE
How do you enter LIGHT sleep mode?

### ISSUE THREAD

**Issue by musapinar** [espressif/esp-at#591]
chip is ESP8266-12F

```

15:09:04.765 -> AT+GMR

15:09:04.765 -> AT version:1.3.0.0(Jul 14 2016 18:54:01)
15:09:04.812 -> SDK version:2.0.0(5a875ba)
15:09:04.859 -> v1.0.0.3
15:09:04.859 -> Mar 13 2018 09:37:06
15:09:04.907 -> OK

```

Documentation explains how to enter DEEP sleep mode,
Documentation explains how to wake up from LIGHT sleep via GPIO pull up and how to read state via an other GPIO,
Documentation explains how to set sleep mode,
But documentation does NOT explain how to ENTER LIGHT sleep mode?

How do you enter LIGHT sleep mode with an AT command? (I do not use SDK)

**Comment by ustccw** [comment]
Sorry, here is esp-at project, but the deprecated 1.3.0.0 version is from ESP8266_NONOS_SDK project.

It is strongly recommended that you use [v2.2.1.0](https://docs.espressif.com/projects/esp-at/en/release-v2.2.0.0_esp8266/AT_Binary_Lists/ESP8266_AT_binaries.html) firmware. Document about light sleep is [AT+SLEEP](https://docs.espressif.com/projects/esp-at/en/release-v2.2.0.0_esp8266/AT_Command_Set/Basic_AT_Commands.html#cmd-sleep).
