### ISSUE TITLE
AT+BTSECPARAM does not selectable

### ISSUE THREAD

**Issue by Daniel-Sies** [espressif/esp-at#593]
## Environment

- Development Kit: [ESP32-DevKitM-1]
- Kit version : [v1]
- Module or chip used:  [ESP32-MINI-1]
- IDF version (run ``git describe --tags`` to find it): v4.2.2
- Build System:         [Make|CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): v8.4.0
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows]
- Power Supply:         [USB]

## Problem Description

I have activated the bt classic and I am able to use some BT classic commands as "AT+BTINIT=1" or "AT+BTSPPINIT=2" but I can not use "AT+BTSECPARAM" it does not appear when you use "AT+CMD?" command. I need it because it seems to be mandatory to make work SPP over windows. Has it been removed?

### Expected Behavior

AT+BTSECPARAM=3,1,"9527"

OK

### Actual Behavior

AT+BTSECPARAM=3,1,"9527"

ERROR

## Debug Logs

at+cmd?
+CMD:0,"AT",0,0,0,1
+CMD:1,"ATE0",0,0,0,1
+CMD:2,"ATE1",0,0,0,1
+CMD:3,"AT+RST",0,0,0,1
+CMD:4,"AT+GMR",0,0,0,1
+CMD:5,"AT+CMD",0,1,0,0
+CMD:6,"AT+GSLP",0,0,1,0
+CMD:7,"AT+SYSTIMESTAMP",0,1,1,0
+CMD:8,"AT+SLEEP",0,1,1,0
+CMD:9,"AT+RESTORE",0,0,0,1
+CMD:10,"AT+SYSRAM",0,1,0,0
+CMD:11,"AT+SYSFLASH",0,1,1,0
+CMD:12,"AT+RFPOWER",0,1,1,0
+CMD:13,"AT+SYSMSG",0,1,1,0
+CMD:14,"AT+SYSROLLBACK",0,0,0,1
+CMD:15,"AT+SYSLOG",0,1,1,0
+CMD:16,"AT+SYSLSPCFG",0,0,1,0
+CMD:17,"AT+SYSLSP",0,0,0,1
+CMD:18,"AT+SYSSTORE",0,1,1,0
+CMD:19,"AT+SLEEPWKCFG",0,0,1,0
+CMD:20,"AT+SYSREG",0,0,1,0
+CMD:21,"AT+USERRAM",0,1,1,0
+CMD:22,"AT+USEROTA",0,0,1,0
+CMD:23,"AT+CWMODE",0,1,1,0
+CMD:24,"AT+CWSTATE",0,1,0,0
+CMD:25,"AT+CWJAP",0,1,1,1
+CMD:26,"AT+CWRECONNCFG",0,1,1,0
+CMD:27,"AT+CWLAP",0,0,1,1
+CMD:28,"AT+CWLAPOPT",0,0,1,0
+CMD:29,"AT+CWQAP",0,0,0,1
+CMD:30,"AT+CWSAP",0,1,1,0
+CMD:31,"AT+CWLIF",0,0,0,1
+CMD:32,"AT+CWQIF",0,0,1,1
+CMD:33,"AT+CWDHCP",0,1,1,0
+CMD:34,"AT+CWDHCPS",0,1,1,0
+CMD:35,"AT+CWSTAPROTO",0,1,1,0
+CMD:36,"AT+CWAPPROTO",0,1,1,0
+CMD:37,"AT+CWAUTOCONN",0,1,1,0
+CMD:38,"AT+CWHOSTNAME",0,1,1,0
+CMD:39,"AT+CWCOUNTRY",0,1,1,0
+CMD:40,"AT+CIFSR",0,0,0,1
+CMD:41,"AT+CIPSTAMAC",0,1,1,0
+CMD:42,"AT+CIPAPMAC",0,1,1,0
+CMD:43,"AT+CIPSTA",0,1,1,0
+CMD:44,"AT+CIPAP",0,1,1,0
+CMD:45,"AT+CIPV6",0,1,1,0
+CMD:46,"AT+CIPDNS",0,1,1,0
+CMD:47,"AT+CIPDOMAIN",0,0,1,0
+CMD:48,"AT+CIPSTATUS",0,0,0,1
+CMD:49,"AT+CIPSTATE",0,1,0,0
+CMD:50,"AT+CIPSTART",0,0,1,0
+CMD:51,"AT+CIPSTARTEX",0,0,1,0
+CMD:52,"AT+CIPTCPOPT",0,1,1,0
+CMD:53,"AT+CIPCLOSE",0,0,1,1
+CMD:54,"AT+CIPSEND",0,0,1,1
+CMD:55,"AT+CIPSENDL",0,0,1,0
+CMD:56,"AT+CIPSENDLCFG",0,1,1,0
+CMD:57,"AT+CIPSENDEX",0,0,1,0
+CMD:58,"AT+CIPDINFO",0,1,1,0
+CMD:59,"AT+CIPMUX",0,1,1,0
+CMD:60,"AT+CIPRECVMODE",0,1,1,0
+CMD:61,"AT+CIPRECVDATA",0,0,1,0
+CMD:62,"AT+CIPRECVLEN",0,1,0,0
+CMD:63,"AT+CIPSERVER",0,1,1,0
+CMD:64,"AT+CIPSERVERMAXCONN",0,1,1,0
+CMD:65,"AT+CIPSSLCCONF",0,1,1,0
+CMD:66,"AT+CIPSSLCCN",0,1,1,0
+CMD:67,"AT+CIPSSLCSNI",0,1,1,0
+CMD:68,"AT+CIPSSLCALPN",0,1,1,0
+CMD:69,"AT+CIPSSLCPSK",0,1,1,0
+CMD:70,"AT+CIPMODE",0,1,1,0
+CMD:71,"AT+CIPSTO",0,1,1,0
+CMD:72,"AT+SAVETRANSLINK",0,0,1,0
+CMD:73,"AT+CIPSNTPCFG",0,1,1,0
+CMD:74,"AT+CIPSNTPINTV",0,1,1,0
+CMD:75,"AT+CIPSNTPTIME",0,1,0,0
+CMD:76,"AT+CIPRECONNINTV",0,1,1,0
+CMD:77,"AT+MQTTUSERCFG",0,0,1,0
+CMD:78,"AT+MQTTCLIENTID",0,0,1,0
+CMD:79,"AT+MQTTUSERNAME",0,0,1,0
+CMD:80,"AT+MQTTPASSWORD",0,0,1,0
+CMD:81,"AT+MQTTCONNCFG",0,0,1,0
+CMD:82,"AT+MQTTALPN",0,0,1,0
+CMD:83,"AT+MQTTCONN",0,1,1,0
+CMD:84,"AT+MQTTPUB",0,0,1,0
+CMD:85,"AT+MQTTPUBRAW",0,0,1,0
+CMD:86,"AT+MQTTSUB",0,1,1,0
+CMD:87,"AT+MQTTUNSUB",0,0,1,0
+CMD:88,"AT+MQTTCLEAN",0,0,1,0
+CMD:89,"AT+HTTPCLIENT",0,0,1,0
+CMD:90,"AT+HTTPGETSIZE",0,0,1,0
+CMD:91,"AT+HTTPURLCFG",0,1,1,0
+CMD:92,"AT+HTTPCGET",0,0,1,0
+CMD:93,"AT+HTTPCPOST",0,0,1,0
+CMD:94,"AT+BLEINIT",0,1,1,0
+CMD:95,"AT+BLEADDR",0,1,1,0
+CMD:96,"AT+BLENAME",0,1,1,0
+CMD:97,"AT+BLEADVPARAM",0,1,1,0
+CMD:98,"AT+BLEADVDATA",0,1,1,0
+CMD:99,"AT+BLEADVDATAEX",0,1,1,0
+CMD:100,"AT+BLEADVSTART",0,0,0,1
+CMD:101,"AT+BLEADVSTOP",0,0,0,1
+CMD:102,"AT+BLESCANRSPDATA",0,1,1,0
+CMD:103,"AT+BLEGATTSSRVCRE",0,0,0,1
+CMD:104,"AT+BLEGATTSSRVSTART",0,0,1,1
+CMD:105,"AT+BLEGATTSSRVSTOP",0,0,1,1
+CMD:106,"AT+BLEGATTSSRV",0,1,0,0
+CMD:107,"AT+BLEGATTSCHAR",0,1,0,0
+CMD:108,"AT+BLEGATTSNTFY",0,0,1,0
+CMD:109,"AT+BLEGATTSIND",0,0,1,0
+CMD:110,"AT+BLEGATTSSETATTR",0,0,1,0
+CMD:111,"AT+BLESCANPARAM",0,1,1,0
+CMD:112,"AT+BLESCAN",0,0,1,0
+CMD:113,"AT+BLECONNPARAM",0,1,1,0
+CMD:114,"AT+BLECONN",0,1,1,0
+CMD:115,"AT+BLEDISCONN",0,0,1,1
+CMD:116,"AT+BLEDATALEN",0,0,1,0
+CMD:117,"AT+BLECFGMTU",0,1,1,0
+CMD:118,"AT+BLEGATTCPRIMSRV",0,0,1,0
+CMD:119,"AT+BLEGATTCINCLSRV",0,0,1,0
+CMD:120,"AT+BLEGATTCCHAR",0,0,1,0
+CMD:121,"AT+BLEGATTCRD",0,0,1,0
+CMD:122,"AT+BLEGATTCWR",0,0,1,0
+CMD:123,"AT+BLESPPCFG",0,1,1,0
+CMD:124,"AT+BLESPP",0,0,0,1
+CMD:125,"AT+BLESECPARAM",0,1,1,0
+CMD:126,"AT+BLEENC",0,0,1,0
+CMD:127,"AT+BLEENCRSP",0,0,1,0
+CMD:128,"AT+BLEKEYREPLY",0,0,1,0
+CMD:129,"AT+BLECONFREPLY",0,0,1,0
+CMD:130,"AT+BLESETKEY",0,1,1,0
+CMD:131,"AT+BLEENCDEV",0,1,0,0
+CMD:132,"AT+BLEENCCLEAR",0,0,1,1
+CMD:133,"AT+BLEHIDNAME",0,1,1,0
+CMD:134,"AT+BLEHIDINIT",0,1,1,0
+CMD:135,"AT+BLEHIDKB",0,0,1,0
+CMD:136,"AT+BLEHIDMUS",0,0,1,0
+CMD:137,"AT+BLEHIDCONSUMER",0,0,1,0
+CMD:138,"AT+BLUFINAME",0,1,1,0
+CMD:139,"AT+BLUFI",0,1,1,0
+CMD:140,"AT+BTINIT",0,1,1,0
+CMD:141,"AT+BTNAME",0,1,1,0
+CMD:142,"AT+BTSCANMODE",0,1,1,0
+CMD:143,"AT+BTSTARTDISC",0,0,1,0
+CMD:144,"AT+BTPINREPLY",0,0,1,0
+CMD:145,"AT+BTENCDEV",0,1,0,0
+CMD:146,"AT+BTENCCLEAR",0,0,1,1
+CMD:147,"AT+BTCOD",0,0,1,0
+CMD:148,"AT+BTPOWER",0,1,1,0
+CMD:149,"AT+BTSPPINIT",0,1,1,0
+CMD:150,"AT+BTSPPCONN",0,1,1,0
+CMD:151,"AT+BTSPPSTART",0,0,0,1
+CMD:152,"AT+BTSPPDISCONN",0,0,1,0
+CMD:153,"AT+BTSPPSEND",0,0,1,1
+CMD:154,"AT+MDNS",0,0,1,0
+CMD:155,"AT+WPS",0,0,1,0
+CMD:156,"AT+CWSTARTSMART",0,0,1,1
+CMD:157,"AT+CWSTOPSMART",0,0,0,1
+CMD:158,"AT+PING",0,0,1,0
+CMD:159,"AT+CIUPDATE",0,1,1,1
+CMD:160,"AT+FACTPLCP",0,0,1,0
+CMD:161,"AT+UART",0,1,1,0
+CMD:162,"AT+UART_CUR",0,1,1,0
+CMD:163,"AT+UART_DEF",0,1,1,0

## Other items if possible

[sdkconfig.zip](https://github.com/espressif/esp-at/files/7712202/sdkconfig.zip)

**Comment by Luxin812** [comment]
Maybe you can test it with the latest version, "AT+BTSECPARAM" is not deleted.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
