### ISSUE TITLE
请问ESP32-C3的AT+SYSFLASH?命令为什么没有返回相应的分区信息

### ISSUE THREAD

**Issue by doudouladou** [espressif/esp-at#595]
如下图所示，一个固件版本有返回相应的信息，一个固件版本没有返回相应的信息

有返回
![image](https://user-images.githubusercontent.com/96154947/146328252-cde66e15-8b89-4f57-86f2-f7de9e2ca1dc.png)

没有返回
![image](https://user-images.githubusercontent.com/96154947/146328712-f1e7a09e-a6db-4252-bfa3-e218d3e420a7.png)

尝试擦擦除或写入分区也会失败
![image](https://user-images.githubusercontent.com/96154947/146329900-35e3f3c0-c965-44d8-8180-a0b712f3b872.png)

**Comment by ustccw** [comment]
@doudouladou please double check the download config. it seems that the partition may not be burned.

**Comment by doudouladou** [comment]
好的， 谢谢你，我换了个新的固件就可以用了@ustccw

**Comment by ustccw** [comment]
no probs.
