### ISSUE TITLE
请问，SSL连接时，IPD上报的数据长度，能设置成真实的数据长度吗，不要加密后的数据长度

### ISSUE THREAD

**Issue by doudouladou** [espressif/esp-at#597]
![image](https://user-images.githubusercontent.com/96154947/147063620-5c06092b-063d-46f4-abed-d87bf8521c3e.png)

**Comment by ustccw** [comment]
same to https://github.com/espressif/esp-at/issues/589

**Comment by doudouladou** [comment]
好的，谢谢你，那意思就是我拿AT+CIPRECVDATA获取到的数据长度就是真实的数据长度对吧

**Comment by ustccw** [comment]
yes, `AT+CIPRECVDATA` always returns actual data and actual length.

**Comment by doudouladou** [comment]
好的，谢谢你@ustccw
