### ISSUE TITLE
What exactly AT+CIPSNTPINTV does?

### ISSUE THREAD

**Issue by MaJerle** [espressif/esp-at#603]
What exactly `AT+CIPSNTPINTV` does when SNTP module is enabled?
It configures interval for synchronization, which means that it sets interval how often ESP connects to NTP servers to get new time?

This is not explained in the docs
https://docs.espressif.com/projects/esp-at/en/latest/AT_Command_Set/TCP-IP_AT_Commands.html#cmd-sntpintv

**Comment by ustccw** [comment]
@MaJerle absolutely right. Thank you for your advice and the document will be updated.

**Comment by MaJerle** [comment]
Thanks, issue can be closed
