### ISSUE TITLE
Can't enable Notification or Indication with AT+BLEGATTCWR 

### ISSUE THREAD

**Issue by Staibii** [espressif/esp-at#608]
## Environment

- Development Kit:      [none]
- Module or chip used:  [ESP32-WROOM-32|ESP32-C3-WROOM]
- Power Supply:         [external 3.3V]

## Problem Description
I am using two ESP modules communicating over BLE, sending AT commands via UART. One modul as BLE Client[ESP32-WROOM-32] and the other as Server[ESP32-C3-WROOM]. Everything works fine until I want to enabel notification or indication. Therefore I want to write 2 Bytes of Data to the corresponding CCCD, using the AT+BLEGATTCWR command. The Problem is that no matter how many Bytes or which value I send , the operation always writes the same two Bytes ('1''0') to the CCCD on the server side.   

#### Client side:
Sending: AT+BLEGATTCWR=0,4,1,1,2\r\n 
Receiving: >
Sending: '2''0' (note that '2''0' are integers and not ASCII values)

#### Server side:
Receiving: +WRITE:0,2,1,1,2,'2''0'\r\n

#### Client side:
Sending: AT+BLEGATTCWR=0,4,1,1,2\r\n 
Receiving: >
Sending: '2''0'

#### Server side:
Receiving: +WRITE:0,2,1,1,2,'1''0'\r\n
#### Server

--> AT+BLEINIT=2
--> AT+BLEADDR? --> +BLEADDR:"7c:df:a1:b2:a2:6e"
--> AT+BLEGATTSSRVCRE
--> AT+BLEGATTSSRVSTART
--> AT+BLEGATTSCHAR? --> +BLEGATTSCHAR:"char",1,1,0x2A2B,0x12
+BLEGATTSCHAR:"desc",1,1,1,0x2902
+BLEGATTSCHAR:"char",2,1,0x2700,0x3a
+BLEGATTSCHAR:"desc",2,1,1,0x2902
+BLEGATTSCHAR:"desc",2,1,2,0x2901
+BLEGATTSCHAR:"char",2,2,0x2700,0x02
+BLEGATTSCHAR:"desc",2,2,1,0x2901
--> AT+BLEADVPARAM=100,200,0,0,7
--> AT+BLEADVSTART

#### Client 

--> AT+BLEINIT=1
--> AT+BLESCAN=1,3 --> +BLESCAN:"7c:df:a1:b2:a2:6e",-32,,,0

#### Client 

--> AT+BLECONN=0,"7c:df:a1:b2:a2:6e" --> +BLECONN:0,"7c:df:a1:b2:a2:6e"

#### Client

--> AT+BLEGATTCPRIMSRV=0 --> +BLEGATTCPRIMSRV:0,1,0x1801,1
+BLEGATTCPRIMSRV:0,2,0x1800,1
+BLEGATTCPRIMSRV:0,3,0x1805,1
+BLEGATTCPRIMSRV:0,4,0x2D59D6C1C1CE4A1AAAACF59BD3F057DB,1

--> AT+BLEGATTCCHAR=0,4 --> +BLEGATTCCHAR:"char",0,4,1,0x2700,0x3a
+BLEGATTCCHAR:"desc",0,4,1,1,0x2902
+BLEGATTCCHAR:"desc",0,4,1,2,0x2901
+BLEGATTCCHAR:"char",0,4,2,0x2700,0x02
+BLEGATTCCHAR:"desc",0,4,2,1,0x2901

--> AT+BLEGATTCWR=0,4,1,1,2 --> '>'
-->'0''2' --> OK

#### Server 

+WRITE:0,2,1,1,2,'1''0'

## Other items if possible
[BleAllMightyService.csv](https://github.com/espressif/esp-at/files/8040665/BleAllMightyService.csv)

- [ ] Service csv file

**Comment by Luxin812** [comment]
Whether the Service characteristic descriptor you want to write only supports the notify.

**Comment by Luxin812** [comment]
If your service feature description only support the notify, it will automatically modify the value you write to 0x0001.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
