### ISSUE TITLE
Commands that give wifi connection information do not work properly

### ISSUE THREAD

**Issue by keeturan** [espressif/esp-at#609]
AT+CWSTATUS & +CIPSTATUS Commands that give wifi connection information do not work properly.
I am using latest fw esp8266 at bin 2.2.1.
i disconnect wifi it shows still tcp socket created status (some wifi drops during uplink operations*).

**Comment by keeturan** [comment]
CWSTATE & CIPSTATUS

**Comment by ustccw** [comment]
As the [docs](https://docs.espressif.com/projects/esp-at/en/latest/AT_Command_Set/TCP-IP_AT_Commands.html?highlight=CIPSTATUS#id4) said, It is recommended to use [AT+CWSTATE](https://docs.espressif.com/projects/esp-at/en/latest/AT_Command_Set/Wi-Fi_AT_Commands.html#cmd-wstate) command to query Wi-Fi state and [AT+CIPSTATE](https://docs.espressif.com/projects/esp-at/en/latest/AT_Command_Set/TCP-IP_AT_Commands.html?highlight=CIPSTATUS#cmd-ipstate) command to query TCP/UDP/SSL state.

`AT+CIPSTATUS` command is deprecated.

**Comment by ustccw** [comment]
May I know if there is any update? If the issue still exists, please let us know.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
