### ISSUE TITLE
esp32-s2-mini-1 AT+HTTPCLIENT command - can't send any json data

### ISSUE THREAD

**Issue by ortros1107** [espressif/esp-at#610]
Greetings!

I have a problem. Whenever I'm trying to send a data through httpclient at command using json, I get an error (sending with the other content types seems to work - I've send data using urlencoded and xml content-types). The only thing that can be send is an empty json object. I've also tried (among other things) to send json data using the examples from the official documentation but to no avail. Otherwise I'm using esp32-s2-mini-1 version 2.1.0.0. Thank You in advance for answers!

**Comment by ustccw** [comment]
@ortros1107 have you escaped the following special characters:

![image](https://user-images.githubusercontent.com/24221485/157582847-d113a594-81ad-48f3-974b-84c6de7d5fd6.png)

**Comment by ustccw** [comment]
For example, if you wanna send json string like `"{"array": [1,2,3]}"`, so in AT commands, they should be like `"\"{\"array\": [1\,2\,3]}\""`.

**Comment by ortros1107** [comment]
First I want to thank You for replying. The problem was (actually) because
I used only one set of double quotation marks (when I should've used two)
when writing json. However, thank You again for your kindness and have a
nice day.

V V čet., 10. mar. 2022 ob 04:38 je oseba ustccw ***@***.***>
napisala:

**Comment by ustccw** [comment]
no probs.

**Comment by ustccw** [comment]
May I know if there is any update? If the issue still exists, please let us know.

**Comment by ortros1107** [comment]
I haven't tested it yet, but as soon as I will, I will tell You about it.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.

**Comment by ortros1107** [comment]
Yes it did, thank you very much. I'm sorry for not answering sooner. You
can close it whenever You want.
