### ISSUE TITLE
Add support for ESP32-PICO-MINI-02

### ISSUE THREAD

**Issue by mrx23dot** [espressif/esp-at#614]
Please Add support for **ESP32-PICO-MINI-02**

**Comment by ustccw** [comment]
@mrx23dot you can read the https://docs.espressif.com/projects/esp-at/en/latest/Compile_and_Develop/esp-at_firmware_differences.html#esp-at-firmware-differences, and pick up the similar firmware, i think `ESP32-PICO-D4_AT_Bin`  firmware should work.

**Comment by mrx23dot** [comment]
Will do, thanks!
