### ISSUE TITLE
wifi easy connect

### ISSUE THREAD

**Issue by sumanclimote** [espressif/esp-at#622]
Does this lib support the "wifi easy connect", I am interested to make a IOT system with this:
https://www.wi-fi.org/discover-wi-fi/wi-fi-easy-connect
https://www.wi-fi.org/download.php?file=/sites/default/files/private/Wi-Fi_Easy_Connect_Specification_v2.0.pdf

I am looking for this port in at lib-
https://github.com/espressif/esp-idf/tree/95b3dad771/examples/wifi/wifi_easy_connect/dpp-enrollee

**Comment by ustccw** [comment]
@sumanclimote Sorry that esp-at has no plan about **wifi easy connect** for AT commands.

I would like to suggest you add your AT commands  according to your needs.
Refer to:
- https://docs.espressif.com/projects/esp-at/en/latest/esp32/Compile_and_Develop/How_to_add_user-defined_AT_commands.html
- esp-at/esp-idf/examples/wifi/wifi_easy_connect

**Comment by ustccw** [comment]
May I know if there is any update? If the issue still exists, please let us know.

**Comment by ayoububilite** [comment]
After compiling the ESP IDF Project, Wifi Easy Connect isn't shown, is it still supported?

**Comment by aayoub13** [comment]
Trying to connect Easy Connect using Oneplus 0Pro, 7T, Samsung Note10, no Response
