### ISSUE TITLE
ESP32, TCP serveur in single connection passthrough mode

### ISSUE THREAD

**Issue by ExpertVelouze57** [espressif/esp-at#631]
Hello,

I use an ESP32c3 dev kit

For my application I connect my ESP to an external access point wifi and host the tcp server into the esp module.
I need to speed up the throughput of the link and I would like to activate WIFI passthrough mode in this configuration.

I can't activate WIFI passtrough mode despite having only one active client (CPMUX=1 to get the TCP server started as CPMUX=0 block the TCP server) 
As indicate in the last release 2.3.0.0 it should be possible. ("Added passthrough mode support when AT as server but only have one connection")
AT+CIPMODE=1 return OK but the next step AT+CIPSEND return an error.

What is the initialisation process to get the ESP32 C3 to work in passthrough mode when AT as server?

Thanks

**Comment by ustccw** [comment]
An example to set up passthrough mode is like the following.  we will add the detailed example for it in next month.
```
ready
AT+CWMODE=1

OK
AT+CWJAP="688018.sh",""
WIFI CONNECTED
WIFI GOT IP

OK
AT+CIPMUX=1

OK
AT+CIPSERVERMAXCONN=1

OK
AT+CIPSERVER=1,1234

OK
AT+CIPMODE=1

OK
0,CONNECT
AT+CIPSEND

OK

>
```

**Comment by ExpertVelouze57** [comment]
Hello, 

Thank you very much, that works.
