### ISSUE TITLE
ESP32-C3-MINI-1_AT_Bin_V2.4.0.0 : Once connected and disconnected by a client, the server becomes indiscoverable.

### ISSUE THREAD

**Issue by gkg-7** [espressif/esp-at#635]
Once connected and disconnected by a client, the server becomes indiscoverable. For this case I am manually giving AT+BLEADVSTART once I receive a disconnection.

**Comment by Luxin812** [comment]
Hi, There is only one case, the device will automatically broadcast after disconnecting as a server, that is, your device enters SPP mode. When the <auto_conn> parameter of your AT+BLESPPCFG command is set to 1, the device will automatically broadcast after disconnection. In other cases of being disconnected, the device will not automatically broadcast. After disconnecting, you need to send the AT+BLEADVSTART command to start broadcasting.
