### ISSUE TITLE
M5 STAMP-C3U device support

### ISSUE THREAD

**Issue by jerrygzy** [espressif/esp-at#637]
about the device

https://docs.m5stack.com/en/core/stamp_c3u

how can I set the UART port for this device?

do I need to update `factory_param_data.csv` ? or use `build.py menuconfig` ?

**Comment by felmue** [comment]
Hello @jerrygzy 

depends. by default esp-at uses two UART ports. One for logging and one for AT commands. The former is set using `menuconfig`, the latter is set in `factory_param_data.csv`. See [here](https://docs.espressif.com/projects/esp-at/en/latest/esp32/Compile_and_Develop/How_to_set_AT_port_pin.html).

Thanks
Felix

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
