### ISSUE TITLE
How to Enable AT  FS COMMAND SUPPORT

### ISSUE THREAD

**Issue by Nagarajan2507** [espressif/esp-at#638]
Hi

I am following "[ESP32C3-AT][v2.4.0.0]User-Guide.pdf" Chapter 5 How to Compile and Develop Your Own AT Project.

Module: ESP32-C3-WROOM-2
IDF VER: 4.3.2

Component config -> AT -> AT FS Command Support is checked,

![image](https://user-images.githubusercontent.com/96462642/170925593-2db5d704-8228-4b09-ae70-82af1f179d58.png)

Facing compile errors as shown below:

D:\Espressif\proj\esp-at>python build.py build
Platform name:ESP32C3   Module name:MINI-1      Silence:0
Ready to set up environment variables..
PATH is D:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin;D:\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-8.4.0\xtensa-esp32s2-elf\bin;D:\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin;D:\Espressif\tools\riscv32-esp-elf\esp-2021r2-8.4.0\riscv32-esp-elf\bin;D:\Espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;D:\Espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;D:\Espressif\tools\cmake\3.16.4\bin;D:\Espressif\tools\openocd-esp32\v0.10.0-esp32-20211111\openocd-esp32\bin;D:\Espressif\tools\ninja\1.10.2\;D:\Espressif\tools\idf-exe\1.0.1\;D:\Espressif\tools\ccache\3.7\;D:\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;D:\Espressif\esp-idf\tools;D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\;D:\Espressif\tools\idf-git\2.34.2\cmd\;D:\Espressif;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Users\Nagarajan\AppData\Local\Android\Sdk\platform-tools;C:\Users\Nagarajan\AppData\Local\Android\Sdk\tools;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\FTDI\Vinculum II Toolchain\Tools\bin;C:\Users\Nagarajan\AppData\Local\Programs\Python\Python37;C:\Program Files (x86)\Common Files\PerkinElmer\;C:\Program Files\OpenSSL-Win64\bin;C:\Users\Nagarajan\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Sophos\Sophos SSL VPN Client\bin;C:\Users\Nagarajan\AppData\Local\Programs\Microsoft VS Code\bin
IDF_PYTHON_ENV_PATH is D:\Espressif\python_env\idf4.3_py3.8_env
sys.platform is win32
Not using an unsupported version of tool xtensa-esp32-elf found in PATH: esp-2021r2-8.4.0. To use it, run 'D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe esp-idf\tools\idf_tools.py export --prefer-system'
Not using an unsupported version of tool xtensa-esp32s2-elf found in PATH: esp-2021r2-8.4.0. To use it, run 'D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe esp-idf\tools\idf_tools.py export --prefer-system'
Not using an unsupported version of tool xtensa-esp32s3-elf found in PATH: esp-2021r2-8.4.0. To use it, run 'D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe esp-idf\tools\idf_tools.py export --prefer-system'
Not using an unsupported version of tool riscv32-esp-elf found in PATH: esp-2021r2-8.4.0. To use it, run 'D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe esp-idf\tools\idf_tools.py export --prefer-system'
Not using an unsupported version of tool openocd-esp32 found in PATH: v0.10.0-esp32-20211111. To use it, run 'D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe esp-idf\tools\idf_tools.py export --prefer-system'
PATH is D:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin;D:\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin;D:\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin;D:\Espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin;D:\Espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin;D:\Espressif\proj\esp-at\esp-idf\tools;%PATH%;D:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin;D:\Espressif\tools\xtensa-esp32s2-elf\esp-2021r2-8.4.0\xtensa-esp32s2-elf\bin;D:\Espressif\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin;D:\Espressif\tools\riscv32-esp-elf\esp-2021r2-8.4.0\riscv32-esp-elf\bin;D:\Espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;D:\Espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;D:\Espressif\tools\cmake\3.16.4\bin;D:\Espressif\tools\openocd-esp32\v0.10.0-esp32-20211111\openocd-esp32\bin;D:\Espressif\tools\ninja\1.10.2\;D:\Espressif\tools\idf-exe\1.0.1\;D:\Espressif\tools\ccache\3.7\;D:\Espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;D:\Espressif\esp-idf\tools;D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\;D:\Espressif\tools\idf-git\2.34.2\cmd\;D:\Espressif;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Users\Nagarajan\AppData\Local\Android\Sdk\platform-tools;C:\Users\Nagarajan\AppData\Local\Android\Sdk\tools;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\FTDI\Vinculum II Toolchain\Tools\bin;C:\Users\Nagarajan\AppData\Local\Programs\Python\Python37;C:\Program Files (x86)\Common Files\PerkinElmer\;C:\Program Files\OpenSSL-Win64\bin;C:\Users\Nagarajan\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Sophos\Sophos SSL VPN Client\bin;C:\Users\Nagarajan\AppData\Local\Programs\Microsoft VS Code\bin
IDF_PYTHON_ENV_PATH is D:\Espressif\python_env\idf4.3_py3.8_env
Executing action: all (aliases: build)
Running ninja in directory d:\espressif\proj\esp-at\build
Executing "ninja all"...
[0/1] Re-running CMake...
silence:0  sdkconfig:D:/Espressif/proj/esp-at/module_config/module_esp32c3_default/sdkconfig.defaults
esp-at branch: master
esp-at docs version: latest
-- ccache will be used for faster recompilation
-- Building ESP-IDF components for target esp32c3
-- Project sdkconfig file D:/Espressif/proj/esp-at/sdkconfig
Loading defaults file D:/Espressif/proj/esp-at/module_config/module_esp32c3_default/sdkconfig.defaults...
-- App "esp-at" version: v2.4.0.0-2-g40ae56a
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.api.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.libgcc.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.newlib.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.version.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.newlib-nano.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.newlib-time.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.eco3.ld
-- Adding linker script D:/Espressif/proj/esp-at/build/esp-idf/esp32c3/esp32c3_out.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp32c3/ld/esp32c3.project.ld.in
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp32c3/ld/esp32c3.peripherals.ld
silence:0 , ld core:D:/Espressif/proj/esp-at/components/at/lib/libesp32c3_at_core.a
silence:0 , ld core:D:/Espressif/proj/esp-at/components/clouds/qcloud/lib/libesp32c3_qcloud_core.a
Parsing CSV input...
Verifying table...
-- Components: app_trace app_update asio at bootloader bootloader_support bt cbor clouds cmock coap console customized_partitions cxx driver efuse esp-tls esp32c3 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_ipc esp_local_ctrl esp_netif esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py expat fatfs freemodbus freertos hal heap idf_test jsmn json libsodium log lwip main mbedtls mdns mqtt newlib nghttp nvs_flash openssl partition_table protobuf-c protocomm pthread riscv sdmmc soc spi_flash spiffs tcp_transport tcpip_adapter tinyusb unity vfs wear_levelling wifi_provisioning wpa_supplicant
-- Component paths: D:/Espressif/proj/esp-at/esp-idf/components/app_trace D:/Espressif/proj/esp-at/esp-idf/components/app_update D:/Espressif/proj/esp-at/esp-idf/components/asio D:/Espressif/proj/esp-at/components/at D:/Espressif/proj/esp-at/esp-idf/components/bootloader D:/Espressif/proj/esp-at/esp-idf/components/bootloader_support D:/Espressif/proj/esp-at/esp-idf/components/bt D:/Espressif/proj/esp-at/esp-idf/components/cbor D:/Espressif/proj/esp-at/components/clouds D:/Espressif/proj/esp-at/esp-idf/components/cmock D:/Espressif/proj/esp-at/esp-idf/components/coap D:/Espressif/proj/esp-at/esp-idf/components/console D:/Espressif/proj/esp-at/components/customized_partitions D:/Espressif/proj/esp-at/esp-idf/components/cxx D:/Espressif/proj/esp-at/esp-idf/components/driver D:/Espressif/proj/esp-at/esp-idf/components/efuse D:/Espressif/proj/esp-at/esp-idf/components/esp-tls D:/Espressif/proj/esp-at/esp-idf/components/esp32c3 D:/Espressif/proj/esp-at/esp-idf/components/esp_adc_cal D:/Espressif/proj/esp-at/esp-idf/components/esp_common D:/Espressif/proj/esp-at/esp-idf/components/esp_eth D:/Espressif/proj/esp-at/esp-idf/components/esp_event D:/Espressif/proj/esp-at/esp-idf/components/esp_gdbstub D:/Espressif/proj/esp-at/esp-idf/components/esp_hid D:/Espressif/proj/esp-at/esp-idf/components/esp_http_client D:/Espressif/proj/esp-at/esp-idf/components/esp_http_server D:/Espressif/proj/esp-at/esp-idf/components/esp_https_ota D:/Espressif/proj/esp-at/esp-idf/components/esp_https_server D:/Espressif/proj/esp-at/esp-idf/components/esp_hw_support D:/Espressif/proj/esp-at/esp-idf/components/esp_ipc D:/Espressif/proj/esp-at/esp-idf/components/esp_local_ctrl D:/Espressif/proj/esp-at/esp-idf/components/esp_netif D:/Espressif/proj/esp-at/esp-idf/components/esp_pm D:/Espressif/proj/esp-at/esp-idf/components/esp_ringbuf D:/Espressif/proj/esp-at/esp-idf/components/esp_rom D:/Espressif/proj/esp-at/esp-idf/components/esp_serial_slave_link D:/Espressif/proj/esp-at/esp-idf/components/esp_system D:/Espressif/proj/esp-at/esp-idf/components/esp_timer D:/Espressif/proj/esp-at/esp-idf/components/esp_websocket_client D:/Espressif/proj/esp-at/esp-idf/components/esp_wifi D:/Espressif/proj/esp-at/esp-idf/components/espcoredump D:/Espressif/proj/esp-at/esp-idf/components/esptool_py D:/Espressif/proj/esp-at/esp-idf/components/expat D:/Espressif/proj/esp-at/esp-idf/components/fatfs D:/Espressif/proj/esp-at/esp-idf/components/freemodbus D:/Espressif/proj/esp-at/esp-idf/components/freertos D:/Espressif/proj/esp-at/esp-idf/components/hal D:/Espressif/proj/esp-at/esp-idf/components/heap D:/Espressif/proj/esp-at/esp-idf/components/idf_test D:/Espressif/proj/esp-at/esp-idf/components/jsmn D:/Espressif/proj/esp-at/esp-idf/components/json D:/Espressif/proj/esp-at/esp-idf/components/libsodium D:/Espressif/proj/esp-at/esp-idf/components/log D:/Espressif/proj/esp-at/esp-idf/components/lwip D:/Espressif/proj/esp-at/main D:/Espressif/proj/esp-at/esp-idf/components/mbedtls D:/Espressif/proj/esp-at/esp-idf/components/mdns D:/Espressif/proj/esp-at/esp-idf/components/mqtt D:/Espressif/proj/esp-at/esp-idf/components/newlib D:/Espressif/proj/esp-at/esp-idf/components/nghttp D:/Espressif/proj/esp-at/esp-idf/components/nvs_flash D:/Espressif/proj/esp-at/esp-idf/components/openssl D:/Espressif/proj/esp-at/esp-idf/components/partition_table D:/Espressif/proj/esp-at/esp-idf/components/protobuf-c D:/Espressif/proj/esp-at/esp-idf/components/protocomm D:/Espressif/proj/esp-at/esp-idf/components/pthread D:/Espressif/proj/esp-at/esp-idf/components/riscv D:/Espressif/proj/esp-at/esp-idf/components/sdmmc D:/Espressif/proj/esp-at/esp-idf/components/soc D:/Espressif/proj/esp-at/esp-idf/components/spi_flash D:/Espressif/proj/esp-at/esp-idf/components/spiffs D:/Espressif/proj/esp-at/esp-idf/components/tcp_transport D:/Espressif/proj/esp-at/esp-idf/components/tcpip_adapter D:/Espressif/proj/esp-at/esp-idf/components/tinyusb D:/Espressif/proj/esp-at/esp-idf/components/unity D:/Espressif/proj/esp-at/esp-idf/components/vfs D:/Espressif/proj/esp-at/esp-idf/components/wear_levelling D:/Espressif/proj/esp-at/esp-idf/components/wifi_provisioning D:/Espressif/proj/esp-at/esp-idf/components/wpa_supplicant
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Espressif/proj/esp-at/build
[1/8] Running utility command for customized_bin
generating ble_data.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\BLEService.py -t D:/Espressif/proj/esp-at/build/customized_partitions\ble_data.bin D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\ble_data\example.csv
'make' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
generating fatfs.bin: D:/Espressif/proj/esp-at\build\mkfatfs\mkfatfs -c D:/Espressif/proj/esp-at\components\fs_image -s 102400 D:/Espressif/proj/esp-at/build/customized_partitions\fatfs.bin
generating server_cert.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\server_cert.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\server_cert\server_cert.crt
generating server_key.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\server_key.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\server_key\server.key
generating server_ca.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\server_ca.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\server_ca\server_ca.crt
generating client_cert.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\client_cert.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\client_cert\client_cert_00.crt cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\client_cert\client_cert_01.crt
generating client_key.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\client_key.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\client_key\client_key_00.key cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\client_key\client_key_01.key
generating client_ca.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\client_ca.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\client_ca\client_ca_00.crt cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\client_ca\client_ca_01.crt
generating wpa2_cert.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\wpa2_cert.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\wpa2_cert\wpa2_client.crt
generating wpa2_key.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\wpa2_key.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\wpa2_key\wpa2_client.key
generating wpa2_ca.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\wpa2_ca.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\wpa2_ca\wpa2_ca.pem
generating mqtt_cert.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\mqtt_cert.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\mqtt_cert\mqtt_client.crt
generating mqtt_key.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\mqtt_key.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\mqtt_key\mqtt_client.key
generating mqtt_ca.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\AtPKI.py generate_bin -b D:/Espressif/proj/esp-at/build/customized_partitions\mqtt_ca.bin  cert D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\mqtt_ca\mqtt_ca.crt
generate parameter bin: platform PLATFORM_ESP32C3, module name MINI-1
generating factory_param.bin: D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at\tools\factory_param_generate.py --platform PLATFORM_ESP32C3 --module MINI-1 --bin_name D:/Espressif/proj/esp-at/build/customized_partitions\factory_param.bin --define_file D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\factory_param\factory_param_type.csv --module_file D:/Espressif/proj/esp-at\components\customized_partitions\raw_data\factory_param\factory_param_data.csv --log_file D:/Espressif/proj/esp-at/build\factory\factory_parameter.log
[2/8] Performing build step for 'bootloader'
[0/1] Re-running CMake...
-- Building ESP-IDF components for target esp32c3
-- Project sdkconfig file D:/Espressif/proj/esp-at/sdkconfig
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp32c3/ld/esp32c3.peripherals.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.api.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.libgcc.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.newlib.ld
-- Adding linker script D:/Espressif/proj/esp-at/esp-idf/components/bootloader/subproject/main/ld/esp32c3/bootloader.ld
-- Components: bootloader bootloader_support efuse esp32c3 esp_common esp_hw_support esp_rom esp_system esptool_py hal log main micro-ecc newlib partition_table riscv soc spi_flash
-- Component paths: D:/Espressif/proj/esp-at/esp-idf/components/bootloader D:/Espressif/proj/esp-at/esp-idf/components/bootloader_support D:/Espressif/proj/esp-at/esp-idf/components/efuse D:/Espressif/proj/esp-at/esp-idf/components/esp32c3 D:/Espressif/proj/esp-at/esp-idf/components/esp_common D:/Espressif/proj/esp-at/esp-idf/components/esp_hw_support D:/Espressif/proj/esp-at/esp-idf/components/esp_rom D:/Espressif/proj/esp-at/esp-idf/components/esp_system D:/Espressif/proj/esp-at/esp-idf/components/esptool_py D:/Espressif/proj/esp-at/esp-idf/components/hal D:/Espressif/proj/esp-at/esp-idf/components/log D:/Espressif/proj/esp-at/esp-idf/components/bootloader/subproject/main D:/Espressif/proj/esp-at/esp-idf/components/bootloader/subproject/components/micro-ecc D:/Espressif/proj/esp-at/esp-idf/components/newlib D:/Espressif/proj/esp-at/esp-idf/components/partition_table D:/Espressif/proj/esp-at/esp-idf/components/riscv D:/Espressif/proj/esp-at/esp-idf/components/soc D:/Espressif/proj/esp-at/esp-idf/components/spi_flash
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Espressif/proj/esp-at/build/bootloader
ninja: no work to do.
[5/6] Generating binary image from built executable
esptool.py v3.3-dev
Creating esp32c3 image...
Merged 1 ELF section
Successfully created esp32c3 image.
Generated D:/Espressif/proj/esp-at/build/esp-at.bin
[6/6] Running utility command for factory_bin
FAILED: CMakeFiles/factory_bin.util
cmd.exe /C "cd /D D:\Espressif\proj\esp-at\build && D:\Espressif\python_env\idf4.3_py3.8_env\Scripts\python.exe D:/Espressif/proj/esp-at/tools/esp_at_factory_bin_combine.py --module_name "MINI-1 " --bin_directory D:/Espressif/proj/esp-at/build --flash_mode dio --flash_size 4MB --flash_speed 40m --parameter_file D:/Espressif/proj/esp-at/build/factory/factory_parameter.log --download_config D:/Espressif/proj/esp-at/build/flash_project_args"
0x8000,partition_table/partition-table.bin
0xd000,ota_data_initial.bin
0xf000,phy_multiple_init_data.bin
0x0,bootloader/bootloader.bin
0x60000,esp-at.bin
0x1e000,at_customize.bin
0x1f000,customized_partitions/ble_data.bin
0x47000,customized_partitions/fatfs.bin
Traceback (most recent call last):
  File "D:/Espressif/proj/esp-at/tools/esp_at_factory_bin_combine.py", line 98, in <module>
    main()
  File "D:/Espressif/proj/esp-at/tools/esp_at_factory_bin_combine.py", line 94, in main
    esp32_at_combine_bin(args.module_name.upper(), args.flash_mode.upper(), args.flash_size.upper(),
  File "D:/Espressif/proj/esp-at/tools/esp_at_factory_bin_combine.py", line 47, in esp32_at_combine_bin
    with open(os.path.join(build_dir, bin_file), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Espressif/proj/esp-at/build\\customized_partitions/fatfs.bin'
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
A fatal error occurred: idf.py build failed

I am struggling to success more than one week.
Any help is very much appreciated.

Regards
V.Nagarajan

**Comment by ustccw** [comment]
@Nagarajan2507 Thanks for the report! will fix it in two weeks.

**Comment by Nagarajan2507** [comment]
Thanks for looking into this.
Waiting for fix.

**Comment by ustccw** [comment]
@Nagarajan2507 
Could you please unzip the following zip and copy it to esp-at/build/customized_partitions/fatfs.bin, then try to compile again.   
[fatfs.zip](https://github.com/espressif/esp-at/files/8907716/fatfs.zip)

### Reason for compilation failure
In the logs you provided, it mentioned that “ 'make' is not recognized as an internal or external command”.
it means that your windows OS is lack of gcc and g++ compiler. But our [fatfs partition](https://github.com/espressif/esp-at/blob/master/module_config/module_esp32c3_default/at_customize.csv#L16) is generated by [mkfatfs](https://github.com/espressif/esp-at/tree/master/tools/mkfatfs) component, this component is from https://github.com/jkearins/ESP32_mkfatfs, and it need gcc and g++ compiler.
So esp-at project compiled failed due to lack of such compiler.

### Possible workaround for you
1. Use the generated `fatfs.bin` directly, as i mentioned at the beginning.
2. If you have a linux os, just run `sudo apt install gcc g++`, this would be the easier way.
3. Download and install gcc and g++ tools directly into your windows OS.
4. Set up a windows environment where installing such additional tools is possible. Eg. https://chocolatey.org/.

### Actions for ESP-AT project
We're porting ESP-IDF release/v5.0 to esp-at project, once it‘s done, esp-at will use cross-platform [FatFs Partition Generator](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/fatfs.html#fatfs-partition-generator) instead of deprecated  [mkfatfs](https://github.com/espressif/esp-at/tree/master/tools/mkfatfs) tool.

**Comment by Nagarajan2507** [comment]
Thanks for your support.
Workaround 1 is OK
Workaround 3 is not able to succeed. Any help for this.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
