### ISSUE TITLE
What is the ideal RSSI value for a ESP32C3-Mini module with both Wifi and BLE ON?

### ISSUE THREAD

**Issue by gkg-7** [espressif/esp-at#639]

**Comment by gkg-7** [comment]
What is the ideal RSSI value for a ESP32C3-Mini module with both Wifi and BLE ON?

**Comment by ustccw** [comment]
@gkg-7 Actually, there is no an exact answer, just a reference value. Please visit https://www.metageek.com/training/resources/understanding-rssi/ and search `Acceptable Signal Strengths` for more details.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
