### ISSUE TITLE
ESP8266 cannot use 'AT+HTTPCLIENT' command to send https request

### ISSUE THREAD

**Issue by MarchAwake** [espressif/esp-at#644]
================================SEND HTTPS REQUEST ===================================
>>> Transceiver.send_command('AT+HTTPCLIENT=2,0,"https://httpbin.org/get","httpbin.org","/get",2')
exec AT+HTTPCLIENT=2,0,"https://httpbin.org/get","httpbin.org","/get",2 response: AT+HTTPCLIENT=2,0,"https://httpbin.org/get","httpbin.org","/get",2

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x40100000, len 6960, room 16 
tail 0
chksum 0xa5
load 0x3ffe8008, len 24, room 8 
tail 0
chksum 0x2c
load 0x3ffe8020, len 3196, room 8 
tail 4
chksum 0xb8
csum 0xb8

ready

(False, 'AT+HTTPCLIENT=2,0,"https://httpbin.org/get","httpbin.org","/get",2\r\n\r\n ets Jan  8 2013,rst cause:4, boot mode:(3,7)\r\n\r\nwdt reset\r\nload 0x40100000, len 6960, room 16 \r\ntail 0\r\nchksum 0xa5\r\nload 0x3ffe8008, len 24, room 8 \r\ntail 0\r\nchksum 0x2c\r\nload 0x3ffe8020, len 3196, room 8 \r\ntail 4\r\nchksum 0xb8\r\ncsum 0xb8\r\n\r\nready\r\n')
================================SEND HTTPS REQUEST ===================================

================================SEND HTTP REQUEST ===================================
>>> Transceiver.send_command('AT+HTTPCLIENT=2,0,"http://httpbin.org/get","httpbin.org","/get",1')
exec AT+HTTPCLIENT=2,0,"http://httpbin.org/get","httpbin.org","/get",1 response: WIFI CONNECTED
WIFI GOT IP
AT+HTTPCLIENT=2,0,"http://httpbin.org/get","httpbin.org","/get",1
+HTTPCLIENT:282,{
  "args": {}, 
  "headers": {
    "Content-Length": "0", 
    "Content-Type": "application/x-www-form-urlencoded", 
    "Host": "httpbin.org", 
    "User-Agent": "ESP32 HTTP Client/1.0", 
    "X-Amzn-Trace-Id": "Root=1-62a52431-5db81a105463d9a02a4b1388"
  }, 
  "origin": "116.22.
+HTTPCLIENT:45,1.230", 
  "url": "http://httpbin.org/get"
}

OK

(True, 'WIFI CONNECTED\r\nWIFI GOT IP\r\nAT+HTTPCLIENT=2,0,"http://httpbin.org/get","httpbin.org","/get",1\r\n+HTTPCLIENT:282,{\n  "args": {}, \n  "headers": {\n    "Content-Length": "0", \n    "Content-Type": "application/x-www-form-urlencoded", \n    "Host": "httpbin.org", \n    "User-Agent": "ESP32 HTTP Client/1.0", \n    "X-Amzn-Trace-Id": "Root=1-62a52431-5db81a105463d9a02a4b1388"\n  }, \n  "origin": "116.22.\r\n+HTTPCLIENT:45,1.230", \n  "url": "http://httpbin.org/get"\n}\n\r\n\r\nOK\r\n')
>>> 
================================SEND HTTP REQUEST ===================================

**Comment by ustccw** [comment]
For ESP8266 series of devices, if the URL is HTTPS type or ``<transport_type>`` parameter is 2, you need to enlarge `at_process_task` stack size to more than 4096 by configuring `./build.py menuconfig` -> `Component config` -> `AT` -> `The stack size of the AT process task`, otherwise ESP8266 will restart due to insufficient stack.

See [AT+HTTPCLIENT notes](https://docs.espressif.com/projects/esp-at/en/release-v2.2.0.0_esp8266/AT_Command_Set/HTTP_AT_Commands.html#notes) for more details.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
