### ISSUE TITLE
AT Module INIT conflicts with VOIP

### ISSUE THREAD

**Issue by wenxiao11** [espressif/esp-at#661]
## Environment
Development Kit: ESP32-LyraT V4.3
Module: ESP32-WROVER-E
IDF version: v4.4
ADF version: v2.4
## Problem
I try to add a user-defined command to run voip call, and there are some conflicts between the esp-at and voip. The voip code is the sample code in ADF. I add the `esp_at_module_init()` at the beginning of main. It will cause the ringbuffer problem after the audio pipeline is created. If I comment the code related to `player_pipeline_open()`, the audio pipeline works correctly without speaker.
## Error logs
<Pre>
I (33298) VOIP_EXAMPLE: SIP_EVENT_AUDIO_SESSION_BEGIN
I (33298) I2S: APLL expected frequency is 8192000 Hz, real frequency is 8191999 Hz
I (33308) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (33318) I2S: DMA Malloc info, datalen=blocksize=1200, dma_buf_count=3
I (33328) I2S: I2S0, MCLK output by GPIO0
I (33328) LYRAT_V4_3: I2S0, MCLK output by GPIO0
I (33338) AUDIO_PIPELINE: link el->rb, el:0x3f818174, tag:i2s, rb:0x3f819dd4
I (33348) AUDIO_PIPELINE: link el->rb, el:0x3f8182e8, tag:filter_r, rb:0x3f81be14
I (33348) AUDIO_PIPELINE: link el->rb, el:0x3f818438, tag:algo, rb:0x3f81e654
I (33358) AUDIO_PIPELINE: link el->rb, el:0x3f819a04, tag:filter, rb:0x3f820694
I (33368) AUDIO_PIPELINE: link el->rb, el:0x3f819b34, tag:sip_enc, rb:0x3f820ed4
I (33378) VOIP_EXAMPLE:  SIP recorder has been created
E (33378) I2S: register I2S object to platform failed
I (33388) I2S: I2S0, MCLK output by GPIO0
I (33388) LYRAT_V4_3: I2S0, MCLK output by GPIO0
I (33398) AUDIO_PIPELINE: link el->rb, el:0x3f821734, tag:raw, rb:0x3f821d04
I (33408) AUDIO_PIPELINE: link el->rb, el:0x3f821864, tag:sip_dec, rb:0x3f823d44
I (33408) AUDIO_PIPELINE: link el->rb, el:0x3f8219d8, tag:filter, rb:0x3f824584
I (33428) VOIP_EXAMPLE: SIP player has been created
I (33428) AUDIO_PIPELINE: start el[             raw], linked:1, state:1,[0x3f821734],
I (33438) AUDIO_ELEMENT: [raw-0x3f821734] Element task created
I (33438) AUDIO_PIPELINE: start el[         sip_dec], linked:1, state:1,[0x3f821864],
I (33448) AUDIO_THREAD: The sip_dec task allocate stack on external memory
I (33458) AUDIO_ELEMENT: [sip_dec-0x3f821864] Element task created
I (33468) AUDIO_PIPELINE: start el[          filter], linked:1, state:1,[0x3f8219d8],
I (33468) AUDIO_THREAD: The filter task allocate stack on external memory
I (33478) AUDIO_ELEMENT: [filter-0x3f8219d8] Element task created
I (33488) AUDIO_PIPELINE: start el[             i2s], linked:1, state:1,[0x3f821b70],
I (33498) AUDIO_ELEMENT: [i2s-0x3f821b70] Element task created
I (33498) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:4101267 Bytes, Inter:155639 Bytes, Dram:121399 Bytes

I (33518) AUDIO_ELEMENT: [sip_dec] AEL_MSG_CMD_RESUME,state:1
I (33518) CODEC_ELEMENT_HELPER: The element is 0x3f821864. The reserve data 2 is 0x0.
I (33528) AUDIO_ELEMENT: [filter] AEL_MSG_CMD_RESUME,state:1
I (33548) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (33548) I2S_STREAM: AUDIO_STREAM_WRITER
I (33548) AUDIO_PIPELINE: Pipeline started
I (33548) AUDIO_PIPELINE: start el[             i2s], linked:1, state:1,[0x3f818174],
I (33558) AUDIO_ELEMENT: [i2s-0x3f818174] Element task created
I (33568) AUDIO_PIPELINE: start el[        filter_r], linked:1, state:1,[0x3f8182e8],
I (33578) AUDIO_THREAD: The filter_r task allocate stack on external memory
I (33578) AUDIO_ELEMENT: [filter_r-0x3f8182e8] Element task created
I (33588) AUDIO_PIPELINE: start el[            algo], linked:1, state:1,[0x3f818438],
I (33598) AUDIO_THREAD: The algo task allocate stack on external memory
I (33608) AUDIO_ELEMENT: [algo-0x3f818438] Element task created
I (33608) AUDIO_PIPELINE: start el[          filter], linked:1, state:1,[0x3f819a04],
I (33618) AUDIO_THREAD: The filter task allocate stack on external memory
I (33628) AUDIO_ELEMENT: [filter-0x3f819a04] Element task created
I (33638) AUDIO_PIPELINE: start el[         sip_enc], linked:1, state:1,[0x3f819b34],
I (33638) AUDIO_THREAD: The sip_enc task allocate stack on external memory
I (33648) AUDIO_ELEMENT: [sip_enc-0x3f819b34] Element task created
I (33658) AUDIO_PIPELINE: start el[             raw], linked:1, state:1,[0x3f819c64],
I (33668) AUDIO_ELEMENT: [raw-0x3f819c64] Element task created
I (33668) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:3815911 Bytes, Inter:149463 Bytes, Dram:115223 Bytes

I (33688) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
I (33688) AUDIO_ELEMENT: [filter_r] AEL_MSG_CMD_RESUME,state:1[0m
I (33698) RSP_FILTER: sample rate of source data : 8000, channel of source data : 1, sample rate of destination data : 16000, channel of destination data : 2
 (33698)RSP_FLTER: sample rate ofsource data : 16000, channel ofsouce data : 2, sampe rae f estination data : 6000, channl of dstinatio data : 1
I (33698) AUDIO_ELEMENT: [algo] AEL_MSG_CMD_RESUME,state:1
I (33738) AUDIO_ELEMENT: [filter] AEL_MSG_CMD_RESUME,state:1
I (33738) RSP_FILTER: sample rate of source data : 16000, channel of source data : 1, sample rate of destination data : 8000, channel of destination data : 1
I (33758) AUDIO_ELEMENT: [sip_enc] AEL_MSG_CMD_RESUME,ste:1
I (33768) AUDIO_PIPELINE: Pipeline started
I (33768) SIP_RTP: receive task, local addr=10.0.28.110:35728
:1357868) SIP_RTP: send task, remote addr=34.203.251.129
Initial ONE-MIC auido front-end for speech recognition, mode:1, (Dec 10 2021 20:29:24)
I (33898) AUDIO_THREAD: The algo_fetchtask allocate stack on external memory
ERROR! rb_in slow!!!
ERROR! rb_in slow!!!
ERROR! rb_in slow!!!
ERROR! rb_in slow!!!
</Pre>

Is it a hardware conflict or software conflict? Is there any way to solve it?
Also, is there any schedule for updating the ESP-AT to support IDFv4.4? The current VoIP example cannot run in IDFv4.3

Thanks

**Comment by ustccw** [comment]
@wenxiao11 i'm afraid that ESP32-AT cannot work with ESP-IDF 4.4. Currently, the latest IDF version supported by ESP32-AT is ESP-IDF 4.3. 
ESP32-AT will support ESP-IDF 5.0 in the next few months, and does not have a plan to support ESP-IDF 4.4.
Please know.
