### ISSUE TITLE
AT+BLEGATTSNTFY    does this AT command   have a max length limit?

### ISSUE THREAD

**Issue by hustzju** [espressif/esp-at#663]
with the lastest version of AT firmware, AT+BLEGATTSNTFY  could send data  which length bigger than MTU-3. SO  does this AT command   have a max length limit?  the  length can be an arbitrarily larger value？

**Comment by Luxin812** [comment]
> with the lastest version of AT firmware, AT+BLEGATTSNTFY could send data which length bigger than MTU-3. SO does this AT command have a max length limit? the length can be an arbitrarily larger value？

Hi,

The maximum length of the <length> parameter of the AT+BLEGATTSNTFY command is 600 bytes.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
