### ISSUE TITLE
esp8266 at build error

### ISSUE THREAD

**Issue by zhaojinyun** [espressif/esp-at#664]
1.  Use v2.2.0.0_esp8266 branch and the default configuration (platform_esp8266 & esp8266_1mb & silence mode) compile at firmware, prompting "cannot find - lc_nano". How to solve this problem?
2. After disabling 'nano' formatting options in menuconfig, another error "region ` iram0_0_seg 'overflowed by 23652 bytes" is prompted. How to solve it?
3. gcc ver (xtensa-lx106-elf-linux64-1.22.0-100-ge567ec7-5.2.0.tar.gz)

thanks !!!

**Comment by zhaojinyun** [comment]
have already been solved

**Comment by guomingdong** [comment]
How to solve?
