### ISSUE TITLE
BLE advertisement - Manufacturer data truncation difference between 2.2.0 and 2.4.0

### ISSUE THREAD

**Issue by vitorb-rzero** [espressif/esp-at#665]
ESP32 seems to be truncating the manufacturer data in a different way between 2.2.0 and 2.4.0 (WROOM32). I'm using the official firmware builds for this test.

Steps
1. `AT+BLEINIT=2`
2. `AT+BLEADVDATAEX="My cool dev","A002","CACAAABBCCDDEEFFAABBCCDDEEFF",1`
3. `AT+BLEADVSTART`

Checking on EFR Connect or nRF Connect (Android), I get `0xAABBCCDDEEFFAA` on 2.4.0, while 2.2.0 yields `0xAABBCCDDEEFFAABBCCDDEE` (note only the last `0xFF` is missing on 2.2.0).

On both versions, I get more bytes on the manufacturer data field the more I reduce the device name length.
Questions:
1. Why there's a difference in behavior? I've checked the changelog but couldn't spot anything that would lead to this
2. Is there a way to use the extended advertising mode, so I can fit more bytes into the manufacturer data field?

**Comment by Luxin812** [comment]
> ESP32 seems to be truncating the manufacturer data in a different way between 2.2.0 and 2.4.0 (WROOM32). I'm using the official firmware builds for this test.
> 
> Steps
> 
> 1. `AT+BLEINIT=2`
> 2. `AT+BLEADVDATAEX="My cool dev","A002","CACAAABBCCDDEEFFAABBCCDDEEFF",1`
> 3. `AT+BLEADVSTART`
> 
> Checking on EFR Connect or nRF Connect (Android), I get `0xAABBCCDDEEFFAA` on 2.4.0, while 2.2.0 yields `0xAABBCCDDEEFFAABBCCDDEE` (note only the last `0xFF` is missing on 2.2.0).
> 
> On both versions, I get more bytes on the manufacturer data field the more I reduce the device name length. Questions:
> 
> 1. Why there's a difference in behavior? I've checked the changelog but couldn't spot anything that would lead to this
> 2. Is there a way to use the extended advertising mode, so I can fit more bytes into the manufacturer data field?

Maybe you can do this by combining AT+BLEADVDATA and BLESCANRSPDATA commands like:
```
If you want to broadcast device name(16 bytes) and UUID(16 bytes), you can use the `AT+BLEADVDATA` and `AT+BLESCANRSPDATA` comands.

for example:

device name(16 bytes): Example-Name-001
UUID(16 bytes): 0xff0102030405060708090a0b0c0d0e0f
 
AT+BLEADVDATA="02010611094578616d706c652d4e616d652d303031"    // device name
AT+BLESCANRSPDATA="1107ff0102030405060708090a0b0c0d0e0f"    // complete 16 bytes  UUID
```
Of course, it should be noted that the AT+BLEADVPARAM command needs to be executed before the AT+BLEADVDATA command is executed, and after the AT+BLEADVDATA command is executed, the AT+BLEADVSTART command can be executed to start broadcasting.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
