### ISSUE TITLE
HTTPS Problem

### ISSUE THREAD

**Issue by charon22** [espressif/esp-at#670]
## Environment
Development Kit: ESP32-LyraT V4.3
Module: ESP32-WROVER-E
IDF version: v4.4
ESP-AT version: v2.4

## Problem
We must use ESP-IDF 4.4 to do our current project. 
When we use ESP-AT's HTTP command, we mainly use HTTPS, and each time we use it, the cpu halt phenomenon occurs. 
When I checked this, I found out that the esp_http_client_config_t structure of esp_http_client.h of ESP-IDFV4.4 is a problem caused by the different structures of ESP-IDFV4.3. 
I would like to know if it is possible to support IDF4.4 structures in ESP-AT.
ESP-IDFV4.4 --------------------------------------------------------------------------------ESP-IDFV4.3
![image](https://user-images.githubusercontent.com/16707763/192597380-37e214c8-a63d-44f5-bdbd-25a665e4ae68.png)

Thanks

**Comment by xcguang** [comment]
Hello,
Sorry, we have no plan to use IDF v4.4 on AT project, and after released C2 AT, we will use IDF release/v5.0 for ESP32 and ESP32C3 AT.

BTW, ADF is https://github.com/espressif/esp-adf, is not AT.

**Comment by xcguang** [comment]
emm, ESP32 AT may work on IDF v5.0 in October or in November, and if everything goes well, maybe released in December.

What's your project schedule, if I may ask?

**Comment by charon22** [comment]
We are currently testing the feature implementation. The PCB will be manufactured next month, and production will probably start early next year.

**Comment by charon22** [comment]
Can you close this issue
