### ISSUE TITLE
AT+CIPSEND The transparent transmission interval is 20ms

### ISSUE THREAD

**Issue by funful** [espressif/esp-at#671]
How do I change the 20ms interval in AT firmware Transparent mode？

**Comment by ustccw** [comment]
it can't be changed till now. May i ask why you need to change this value?

**Comment by funful** [comment]
It doesn't work when I'm passing through at 120HZ at high speed

**Comment by LimaBR** [comment]
Hi. Any updates? Is it defined in the closed source libraries?

**Comment by 2fdesign** [comment]
It's probably ties to BLE spec of 20bytes per 20ms.  Even though CIPSEND can be used in SPP, I wouldn't be surprised if it is still ticked off 20ms.  How big is the data packet?  Maybe you can increase the packet size to increase throughput?

**Comment by ustccw** [comment]
has added an AT command: `AT+TRANSINTV=<ms>` to support configurable interval in passthrough mode.  
Wait the internal CI passed and then push to GitHub.
