### ISSUE TITLE
STM32 OTA

### ISSUE THREAD

**Issue by hzhh110** [espressif/esp-at#682]
How to use the at command to download an HTTP remote file and save it in the specified file
After the download is successful, print the MD5 value and file information of the file just saved with the at command, and print out the whole file through the serial port

**Comment by ustccw** [comment]
@hzhh110 there is no available AT commands now. but
- you can download a HTTP resource by [AT+HTTPCGET](https://docs.espressif.com/projects/esp-at/en/latest/esp32/AT_Command_Set/HTTP_AT_Commands.html#cmd-httpcget) command.
- you can save resource by [AT+FS](https://docs.espressif.com/projects/esp-at/en/latest/esp32/AT_Command_Set/Basic_AT_Commands.html#cmd-fs) command (disable by default, you should enable it in menuconfig). 
- you can use APIs which in ESP-IDF to implement MD5 calculation (esp_rom_md5_init series APIs).

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
