### ISSUE TITLE
同时使用TCPserver与TCPclient存在问题

### ISSUE THREAD

**Issue by CamelShoko** [espressif/esp-at#687]
同时使用TCPserver与TCPclient存在问题

问题的根本原因是 

[linkid],CONNECT
我不知道这个link是来自server还是clinet

具体描述如下:
1、 AT+CIPSERVER=1,80
2、 AT+CIPSTART=1,"TCP","xxxx",1234

此后出现的 
1,CONNECT 

他到底是来自server还是client呢.

**Comment by ustccw** [comment]
来自于 client，因为 AT+CIPSTART 第一个参数是 `link_id`

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
