### ISSUE TITLE
Version selection question

### ISSUE THREAD

**Issue by zrs5532** [espressif/esp-at#694]
Hi dear community and developers, a quick question. 
I would like to add an ESP32 as a wifi coprocessor with AT option to my existing STM32 project on windows environment. but it seems there are two major releases(versions), v3 and v2.4.2. is there a document lists the difference? should i go for a newer one with v3 and order esp32-c2(ESP8684)?
Thanks a lot!

**Comment by ustccw** [comment]
@zrs5532 It depends on what you need.
### About chip choice
You could compare chips by [ESP Product Selector](https://products.espressif.com/#/product-selector?language=zh&names=).   
In short, if performance is preferred, please consider ESP32 or ESP32-C3, if price performance is preferred, please consider ESP32-C2.

### About esp-at version choice
You could read the [Which Type of Firmware Shall I Choose](https://docs.espressif.com/projects/esp-at/en/latest/esp32/AT_Binary_Lists/index.html#which-type-of-firmware-shall-i-choose)

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
