### ISSUE TITLE
Blufi not returning SSID list

### ISSUE THREAD

**Issue by matt-wood-ct** [espressif/esp-at#695]
Hi we are trialing use of the blufi system for a product and we have found that with the current release ESP-AT firmware on a ESP32-C3 module we are not getting an SSID list back when running that blufi command, it is not returning any errors just also no SSIDs

Is this a known issue with the AT fimware or is it an issue with the app?

Many Thanks,
Matt

**Comment by matt-wood-ct** [comment]
Further detail, we are sending a "Get the Wi-Fi list" command (0x9) and we are not receiving the followup frames as suggested in the documentation.
![image](https://user-images.githubusercontent.com/67578755/217496851-ce187b06-db49-45af-b1fc-37818260e156.png)
This issue is happening with both our own javascript implementation and the blufi demo app provided by Espressif.

**Comment by Luxin812** [comment]
> Hi we are trialing use of the blufi system for a product and we have found that with the current release ESP-AT firmware on a ESP32-C3 module we are not getting an SSID list back when running that blufi command, it is not returning any errors just also no SSIDs
> 
> Is this a known issue with the AT fimware or is it an issue with the app?
> 

> Many Thanks, Matt

Hi,
Please download the AT firmware on the latest master branch from github to test this function. This function is only supported on AT not long ago. There is no release version that supports this function.
![Screenshot_20230210_105705_com espressif espblufi](https://user-images.githubusercontent.com/54392702/217989300-28867fcd-a9f7-47d5-90b1-7e287c4cb4b1.jpg)

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
