### ISSUE TITLE
esp-at分支问题

### ISSUE THREAD

**Issue by MrYanLK** [espressif/esp-at#707]
您好，我在执行./build.py menuconfig时报了这个问题，请问下怎么解决？
![image](https://user-images.githubusercontent.com/129147916/233956066-5f91b6ad-3162-4e41-9a45-2952928be1ae.png)

**Comment by MrYanLK** [comment]
![image](https://user-images.githubusercontent.com/129147916/233956268-f30f119d-c35e-474a-869b-81fe074e62df.png)

**Comment by ustccw** [comment]
将目录下的 `build sdkconfig esp-idf` 删除掉，重新 `./build.py install` 和 `./build.py menuconfig` 试试。

**Comment by MrYanLK** [comment]
好像是因为我先编译过ESP32 的AT固件，当前修改过文件，现在切换到8266的分支上就提示这个，我对git不太熟，不知怎么提交修改或丢弃修改，

error: Your local changes to the following files would be overwritten by checkout:
        components/customized_partitions/raw_data/factory_param/factory_param_data.csv
Please commit your changes or stash them before you switch branches.
Aborting
