### ISSUE TITLE
MQTT commands response time

### ISSUE THREAD

**Issue by leungngok** [espressif/esp-at#709]
Is AT+MQTTPUB command maximum timeout 10 second?

How to shorten this timeout, like the <so_sndtimeo> option for AT+CIPSEND?

**Comment by ustccw** [comment]
network timeout is 10 seconds, not the command timeout. you could change the network timeout in `esp-idf/components/mqtt/esp-mqtt/lib/include/mqtt_config.h` (`MQTT_NETWORK_TIMEOUT_MS`)

**Comment by leungngok** [comment]
> network timeout is 10 seconds, not the command timeout. you could change the network timeout in `esp-idf/components/mqtt/esp-mqtt/lib/include/mqtt_config.h` (`MQTT_NETWORK_TIMEOUT_MS`)

Thanks for your reply!
