### ISSUE TITLE
我用ESP32 AT 的wifi 连接AP 成功后，使用AT+CIPSTART=0,\"TCP\",\"192.168.22.192\",8888\r\n 是可以连接到端口的, 然后我禁用了ESP32 AT的wifi 模块, 使用自己写的代码连接wifi 成功后，用AT+CIPSTART指令就返回ERROR, esp32c3 显示no ip

### ISSUE THREAD

**Issue by edwardL** [espressif/esp-at#716]
![image](https://github.com/espressif/esp-at/assets/3971345/78ccba63-189b-4847-9ea9-ef41211846d5)

**Comment by ustccw** [comment]
TCP/IP 相关命令是基于 Wi-Fi 命令的。如果 Wi-Fi 命令被禁用，那 TCP/IP 命令也是不可用的。或者你自己写一套 TCP/IP 命令；或者还是使用自带的 Wi-Fi 命令集。
