### ISSUE TITLE
Any information when client connected to ESP32 AP?

### ISSUE THREAD

**Issue by zavovi** [espressif/esp-at#72]
Hi all,
I am working with ESP32-wroom module and I tried make WiFi AP with ESP32. I see the WiFi in my smartphone, I can connect to this AP, but I didn't see any text on UART, that client (smartphone) is connected or something like that. 

Is it possible allow something like this?

Thank you

**Comment by CoryFF** [comment]
I think what you need to do is send the AT+CWLIF command. That will list out which client IPs are connected.

**Comment by schwac** [comment]
You need to send AT+CWLIF periodically. That will list out the connected clients IPs.

**Comment by xcguang** [comment]
Hi ,
We will add it ASAP.

**Comment by zavovi** [comment]
Hi, thank you for all answers, if I want use AT+CWLIF, it should be send in poll and it is wasting time. But now, it may be solution. 

@xcguang, I will wait for your solution :+1: Thank you

**Comment by MaJerle** [comment]
Should be solved the same way as in ESP8266

**Comment by xcguang** [comment]
@MaJerle Yes, we will add the same message as ESP8266.
