### ISSUE TITLE
开启透传模式后无法接收和发送AT指令了

### ISSUE THREAD

**Issue by xiaoheng14** [espressif/esp-at#726]
如题，开启透传模式下，只能发送接收tcp数据，此时不能下发和接收AT指令，请问有没解决方案;如果不使用透传模式的话，tcp发送速度会慢很多。

**Comment by ustccw** [comment]
透传模式的行为是 AT 通用的，请参考：
- https://en.wikipedia.org/wiki/Hayes_AT_command_set#+++
- https://docs.espressif.com/projects/esp-at/zh_CN/latest/esp32/index_of_abbreviations.html#term-Data-Mode
如果想发送和接收 AT 指令。请按照 [AT 文档说明](https://docs.espressif.com/projects/esp-at/zh_CN/latest/esp32/AT_Command_Set/TCP-IP_AT_Commands.html#cmd-plus)退出透传。

提高 TCP 吞吐速度，请参考文档：https://docs.espressif.com/projects/esp-at/zh_CN/latest/esp32/Compile_and_Develop/How_to_optimize_throughput.html

~

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
