### ISSUE TITLE
Allow any BLEADDR-esses

### ISSUE THREAD

**Issue by mrx23dot** [espressif/esp-at#745]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Setting this address is ineffective, it still advertises using the original (AT+BLEADDR?) address.

```
AT+RST
OK
ready

 AT+GMR  // first to debug
    AT version:2.4.0.0(4c6eb5e - ESP32 - May 20 2022 03:11:58)
    SDK version:qa-test-v4.3.3-20220423
    compile time(5641e0a):May 20 2022 11:12:05
    Bin version:2.4.0(WROOM-32)
    OK

AT+BLEINIT=2
    OK

AT+BLEADDR=1,"d9:2c:b0:e1:26:19"
    OK

AT+BLEADDR?
    +BLEADDR:"3c:e9:0e:86:8e:xx"    // ineffective??
    OK

AT+BLEADVSTART
    OK
```

Still advertises with original address (3c:e9:0e:86:8e)
even when I try to set example from user manual
`AT+BLEADDR=1,"f8:7f:24:87:1c:7b"`

Also there shouldn't be MSB bit restriction, only full 0, 255 restriction.

**Comment by ustccw** [comment]
@Luxin812 PTAL

**Comment by Luxin812** [comment]
@mrx23dot Maybe you can try to set the <own_addr_type> parameter of AT+BLEADVPARAM command to 1, you can refer to the following [example](https://docs.espressif.com/projects/esp-at/en/latest/esp32/AT_Command_Set/BLE_AT_Commands.html#cmd-badvp):
![bleaddr](https://github.com/espressif/esp-at/assets/54392702/36f4422a-6515-4516-9303-345892c4629d)

**Comment by Luxin812** [comment]
The address queried by the AT+BLEADDR command in ESP32 AT is always the <BLE_public_addr> address, you can check the [AT+BLEADDR command introduction](https://docs.espressif.com/projects/esp
![33333](https://github.com/espressif/esp-at/assets/54392702/f6e38b67-3a7d-4b04-9c13-5cbd586850d2)
-at/en/latest/esp32/AT_Command_Set/BLE_AT_Commands.html#id1)

**Comment by Luxin812** [comment]
If the two parameters "1,"12:34:45:78:66:88"" are not used, they can be omitted directly, as long as the <own_addr_type> parameter in the AT+BLEADVPARAM command and the <addr_type> in the AT+BLEADDR command are guaranteed The parameters are the same.
I use the above sample test here, it works normally, is your mobile phone location turned on? If it is convenient, can you take a screenshot to see the nrf screen of your mobile phone and provide your mobile phone model?
![655e4aed7c6dcd8751e4e0529ff33cfa](https://github.com/espressif/esp-at/assets/54392702/b385b351-ce29-4ce7-ab80-b288d50e2c0d)
![企业微信截图_16908597997363](https://github.com/espressif/esp-at/assets/54392702/cb388d6f-9cf5-4c4e-88b8-4c6e2c84a528)
