### ISSUE TITLE
RFPOWER error

### ISSUE THREAD

**Issue by mrx23dot** [espressif/esp-at#746]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I wanted to set max power 
```
AT+RFPOWER=84,0,0,0
ERROR

AT+RFPOWER=78,0,0,0
ERROR

AT+RFPOWER=77,0,0,0
ERROR

AT+RFPOWER?
+RFPOWER:76,0,0,0

AT+RFPOWER=76,0,0,0
ERROR   // why???
```

doc say 
For ESP32 devices, the range is [40,**84**]

```
AT version:3.2.0.0(s-ec2dec2 - ESP32 - Jul 28 2023 07:05:28)
SDK version:v5.0.2-376-g24b9d38a24-dirty
compile time(6118fc22):Jul 28 2023 10:14:50
Bin version:v3.2.0.0(PICO-D4)

```

**Comment by ustccw** [comment]
Please initialize the ble ([AT+BLEINIT=1](https://docs.espressif.com/projects/esp-at/en/latest/esp32/AT_Command_Set/BLE_AT_Commands.html#cmd-binit)) before you try to set ble rf power. 
See https://docs.espressif.com/projects/esp-at/en/latest/esp32/AT_Command_Set/Basic_AT_Commands.html#id89 for more details.

**Comment by ustccw** [comment]
@mrx23dot For a well-designed command, it should do what it describes. When you set the RF power, the command should only return "OK" after the RF power has been successfully set in reality. If it merely stores the value of the RF power, you won't know for sure if the command has actually taken effect in the end.

**Comment by ustccw** [comment]
@mrx23dot Hello, i am not sure what you did. the right commands according to your description should like the following:
```
// deinit the wifi
AT+CWINIT=0

// init the ble
AT+BLEINIT=1

// just set the rf power of ble 
AT+RFPOWER=,7,7,7
```
