### ISSUE TITLE
ESP32 release v3.2.0 -> NO WROVER?

### ISSUE THREAD

**Issue by MaJerle** [espressif/esp-at#747]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

https://github.com/espressif/esp-at/releases/tag/v3.2.0.0

**Comment by ustccw** [comment]
@MaJerle Yes, starting from the current version, we do not plan to release AT firmware for the ESP32 WROVER series. This decision is primarily based on the following considerations:

1. Looking at the historical releases of ESP32 WROVER firmware, there have been no customer demands for ESP32 WROVER to have AT firmware by default. One reason is that the ESP32 WROVER series includes PSRAM, which increases the cost for customers. Another reason is that AT firmware does not require external PSRAM, making it more recommended for customers to choose the more cost-effective ESP32-C3 or ESP32-C2 series modules.

2. The AT firmware for the WROVER series includes classic Bluetooth, which results in a large binary size and iram usage. The current default firmware cannot accommodate this, and it would require resources to optimize the binary size and iram. Of course, if customers still wish to use ESP32 WROVER, they can compile their own firmware and disable some unused features to save on binary size and iram.

~

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
