### ISSUE TITLE
How to use ESP-AT as static library in other project?

### ISSUE THREAD

**Issue by ypiotrp** [espressif/esp-at#756]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have ESP32 connected to STM32 via UART.  I'd like to use esp-at module as a library in my project to communicate between the microcontrollers. I don't need AT Command Set present in the project. All I need is the core of the esp-at. I'd like to create my own commands. 
I already tried adding `libesp32_at_core.a` using:
1. `add_prebuilt_library()` but it didn't work. Maybe I did it wrong?
2. The other way was adding this to my CMakeLists.txt but it also didn't work: 
```
add_library(esp32_at_core STATIC IMPORTED)
set_property(TARGET esp32_at_core PROPERTY IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/../esp-at/components/at/lib/libesp32_at_core.a)
target_link_libraries(${COMPONENT_LIB} INTERFACE esp32_at_core)
set_property(TARGET esp32_at_core APPEND PROPERTY INTERFACE_LINK_LIBRARIES ${COMPONENT_LIB})
```

Please help me add this lib to my project. I don't want to write my own AT commands service when there is this one available.
Regards

**Comment by xcguang** [comment]
Please refer to https://github.com/espressif/esp-at/tree/master/components/at, in fact, you can build your project based on esp-at project and add your commands, and disable the commands which you do not use.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
