### ISSUE TITLE
FR: HTTP interact with the file system

### ISSUE THREAD

**Issue by pauldeng** [espressif/esp-at#772]
### Describe the solution you'd like.

It would be great if HTTP commands could work with the file system.

For example:
 - AT+HTTPCGET could straight download the file into ESP32 file system
 - AT+HTTPCPOST and AT+HTTPCPUT could straight post/put the specified file from ESP32 file system to a url

This feature is similar to the [AT+UHTTPC command](https://cdn.sparkfun.com/assets/b/6/2/4/5/SARA-R5_ATCommands__UBX-19047455_.pdf) provided by the U-Blox R510S module.

**Comment by pauldeng** [comment]
Dear repo owner/maintainer,

Is there any update for this Feature Request?
We probably could have a discussion about it.

Cheers,
Paul

**Comment by ustccw** [comment]
@pauldeng thanks for your feature request. We will consider it with low priority because the default flash available is very limited and can only store very small files.

**Comment by pauldeng** [comment]
Dear @ustccw, 

Thanks for your reply.

This feature is not intended to be used to download a movie. In my use case, it is a binary file that is < 1MB.

Can I ask how to prioritise this feature? Or do you allow contribution from other personal/company, so that I probably can work on this.

We can discuss how to proceed if you are interested.

Cheers,
Paul

**Comment by pauldeng** [comment]
Dear @ustccw,

If I would like to contribute, how do I proceed?

Cheers,
Paul

**Comment by ustccw** [comment]
@pauldeng I apologize for the delayed response. If you urgently need this feature, it might be more appropriate for you to undertake secondary development and implement custom AT commands. We also have plans for this feature, but it's scheduled for 2024.Q2.

**Comment by pauldeng** [comment]
That is great!
Appreciate.

**Comment by denravonska** [comment]
How's this coming along? 2024.Q2 was 5 Qs ago.

**Comment by ustccw** [comment]
Yes. Now you can try this two examples:
- https://github.com/espressif/esp-at/tree/master/examples/at_http_get_to_fatfs
- https://github.com/espressif/esp-at/tree/master/examples/at_fatfs_to_http_server
