### ISSUE TITLE
关于ESP8266的AT指令版本的问题

### ISSUE THREAD

**Issue by Zency-Sun** [espressif/esp-at#784]
### Is your feature request related to a problem?

根据官网描述，目前ESP8266的最新AT指令更新至v2.2.0.0版本。
我在使用AT+GMR指令查询固件版本信息的时候出现如下信息：
`AT version:2.3.0.0-dev(s-bcd64d2 - ESP8266 - Jun 23 2021 11:42:05)
SDK version:v3.4-22-g967752e2
compile time(b498b58):Jun 30 2021 11:28:20
Bin version:2.2.0(ESP8266_1MB)
`
但是目前没有针对V2.3.0.0版本的ESP8266的AT指令文档，请问我需要在哪里获取到与固件版本相匹配的AT文档呢？

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
