### ISSUE TITLE
mbedtls_pk_parse_keyfile returned -0x3D20，cert and key is check in openssl no problem but now branch failed

### ISSUE THREAD

**Issue by sjWang** [espressif/esp-at#786]
### Answers checklist

- [x] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [x] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### AT+GMR

AT+GMR
AT version:3.2.0.0(ec2dec2 - ESP32C3 - Jul 28 2023 07:04:22)
SDK version:v5.0.2-376-g24b9d38a24-dirty
compile time(6118fc22):Nov 25 2023 22:59:36
Bin version:v3.2.0.0(MINI-1)

### ESP-AT Firmware Source

3.Compile use branch master and release/v3.2.0.0 alway the same result but for release/v2.4.2.0 is ok

### Hardware Information

ESP32C3-MINI-1

### Power Supply used

USB

### What is the expected behavior?

right cert and key(EC) pass 

### What is the actual behavior?

right cert and key(EC) failed

### Probability of recurrence

Must appear

### AT+SYSRAM?

AT+SYSRAM?
+SYSRAM:126120,97748
OK

### Steps to reproduce

just add a EC cert and key and ca to customized_partitions\raw_data\mqtt_ca\
and run connect

### AT command port output

```plain
Common sanity checks
MBEDTLS_ECP_TYPE_SHORT_WEIERSTRASS
ecp_mul_comb_after_precomp start
********ecp_mul_comb_after_precomp:1
********ecp_mul_comb_after_precomp:2
********ecp_mul_comb_after_precomp:3
********ecp_mul_comb_core:1
********ecp_mul_comb_core:2
********ecp_randomize_jac,ret:-32
mbedtls_ecp_mul,ret:-32
pk_parse_key_sec1_der ret:-0x3D20
E (11102) esp-tls-mbedtls: mbedtls_pk_parse_keyfile returned -0x3D20
E (11109) esp-tls-mbedtls: Failed to set client pki context
E (11115) esp-tls-mbedtls: Failed to set client configurations, returned [0x8019] (UNKNOWN ERROR)
E (11126) esp-tls: create_ssl_handle failed
E (11130) esp-tls: Failed to open new connection
E (11135) transport_base: Failed to open a new connection
E (11145) mqtt_client: Error transport connect
MQTT ERROR
MQTT DISCONNECTED
```

### AT log port output

```plain
ready
WIFI CONNECTED
WIFI GOT IP
AT+MQTTUSERCFG=0,5,"venus&/MCHJ23926DNND1010003/TLS/AUK1_MQTT_HMAC_SHA1/1700794165000/AUTH","/venus/MCHJ23926DNND1010003","",0,0,""

OK
AT+MQTTCONN=0,"auk-iot.test.zservey.com",1883,1
+MQTTDISCONNECTED:0

ERROR
```

**Comment by ustccw** [comment]
@sjWang It seems that there is an issue with parsing the private key, returning an incorrect private key format errno. I would like to look into this issue if you can provide your EC certificate and private key, and ca.

**Comment by sjWang** [comment]
> @sjWang It seems that there is an issue with parsing the private key, returning an incorrect private key format errno. I would like to look into this issue if you can provide your EC certificate and private key, and ca.

already find problem:
1、aes_ctx not seed，because of mbedtls3.x interface change。
![image](https://github.com/espressif/esp-at/assets/8464901/f072eb67-9115-4b42-a99a-76bafb268340)

2、v2.4.2.0 pass because NULL default seed, code below:
#if !defined(MBEDTLS_ECP_NO_INTERNAL_RNG)
    if( f_rng == NULL )
    {
        /* Adjust pointers */
        f_rng = &ecp_drbg_random;
#if defined(MBEDTLS_ECP_RESTARTABLE)
        if( rs_ctx != NULL && rs_ctx->rsm != NULL )
            p_rng = &rs_ctx->rsm->drbg_ctx;
        else
#endif
            p_rng = &drbg_ctx;

        /* Initialize internal DRBG if necessary */
#if defined(MBEDTLS_ECP_RESTARTABLE)
        if( rs_ctx == NULL || rs_ctx->rsm == NULL ||
            rs_ctx->rsm->drbg_seeded == 0 )
#endif
        {
            const size_t m_len = ( grp->nbits + 7 ) / 8;
            MBEDTLS_MPI_CHK( ecp_drbg_seed( p_rng, m, m_len ) );//seed here
        }
#if defined(MBEDTLS_ECP_RESTARTABLE)
        if( rs_ctx != NULL && rs_ctx->rsm != NULL )
            rs_ctx->rsm->drbg_seeded = 1;
#endif
        mbedtls_printf("%s f_rng reset and seed:%ld\r\n",__func__,grp->nbits);
    }
#endif /* !MBEDTLS_ECP_NO_INTERNAL_RNG */


now,temporary modified and pass code :
esp_err_t esp_create_mbedtls_handle(const char *hostname, size_t hostlen, const void *cfg, esp_tls_t *tls)
{
    assert(cfg != NULL);
    assert(tls != NULL);
    int ret;
    esp_err_t esp_ret = ESP_FAIL;
    tls->server_fd.fd = tls->sockfd;
    mbedtls_ssl_init(&tls->ssl);
    mbedtls_ctr_drbg_init(&tls->ctr_drbg);
    mbedtls_ssl_config_init(&tls->conf);
    mbedtls_entropy_init(&tls->entropy);

    // fix: add seed after mbedtls_ctr_drbg_init
    if ((ret = mbedtls_ctr_drbg_seed(&tls->ctr_drbg,
                                     mbedtls_entropy_func, &tls->entropy, NULL, 0)) != 0) {
        ESP_LOGE(TAG, "mbedtls_ctr_drbg_seed returned -0x%04X", -ret);
        mbedtls_print_error_msg(ret);
        ESP_INT_EVENT_TRACKER_CAPTURE(tls->error_handle, ESP_TLS_ERR_TYPE_MBEDTLS, -ret);
        esp_ret = ESP_ERR_MBEDTLS_CTR_DRBG_SEED_FAILED;
        goto exit;
    }

**Comment by ustccw** [comment]
@sjWang 非常感谢您的反馈！
个人基本认可上面的做法，应该是先调用 [mbedtls_ctr_drbg_seed()](https://github.com/espressif/esp-idf/blob/master/components/esp-tls/esp_tls_mbedtls.c#L133C16-L133C37), 再调用 [set_client_config()](https://github.com/espressif/esp-idf/blob/master/components/esp-tls/esp_tls_mbedtls.c#L97C19-L97C36), 我会和负责这部分的同事进一步确认后，再修复。

再次感谢！

**Comment by ustccw** [comment]
@sjWang 此问题已在 master 上修复，请验证。如有问题，请 reopen 一下。

**Comment by sjWang** [comment]
> @sjWang 此问题已在 master 上修复，请验证。如有问题，请 reopen 一下。

ok，thanks

**Comment by ustccw** [comment]
Hello @sjWang ! 我们想加一些 testcases 来测试此类私钥，您方便告知一下，这种私钥是如何生成的么？  :pray: 
我们尝试了一些 `openssl ecparam` 命令，似乎都无法复现之前的问题。

**Comment by ustccw** [comment]
用 GenAI 填一个很久之前的坑 😄 

生成全套 PKI 脚本：
[gen_pki.zip](https://github.com/user-attachments/files/28005422/gen_pki.zip)
