### ISSUE TITLE
Any Encrypted AT command feature available ? 

### ISSUE THREAD

**Issue by vinodstanur** [espressif/esp-at#789]
### Is your feature request related to a problem?

From a security perspective, transmitting plain-text AT commands poses a vulnerability, as they can be easily intercepted with minimal or zero effort. 

### Describe the solution you'd like.

Encrypting these commands using say AES and implementing a one-time, randomly generated key significantly enhances security, making it more challenging for unauthorized entities to intercept and decode sensitive information.

**Comment by ustccw** [comment]
@vinodstanur Thank you for your feedback. We already have plans internally to implement this feature, as it's crucial for product security. The addition of this feature to AT is expected in 2024.Q1.

**Comment by jcoteBrio** [comment]
Hi @ustccw, 

Can you confirm it is done since 2024.Q1 is now completed ?
If not when do you think this will be implemented ?

Best regards

**Comment by ustccw** [comment]
I am really sorry for this delay. This feature would be implemented by an external example in 2024.Q3. 
Apologies for any inconvenience caused.

**Comment by ustccw** [comment]
@vinodstanur @jcoteBrio I'm very sorry for the long delay regarding this feature. The feature is now supported through the example. Could you please use [examples/at_interface_security](https://github.com/espressif/esp-at/tree/master/examples/at_interface_security) to verify it. If there is any questions, feel free to ask me.
