### ISSUE TITLE
Flash AT Firmware into Your Device (ESP32-C6)

### ISSUE THREAD

**Issue by blue-freedom-technologies** [espressif/esp-at#805]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Bug in the ESP-AT documentation [inux-or-macos](https://docs.espressif.com/projects/esp-at/en/latest/esp32c6/Get_Started/Downloading_guide.html#linux-or-macos)

When flashing with the command:

```bash
esptool.py --chip auto --port /dev/tty.usbserial-0001 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size 4MB 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial.bin 0xf000 phy_init_data.bin 0x0 bootloader/bootloader.bin 0x60000 esp-at.bin 0x1e000 at_customize.bin 0x1f000 customized_partitions/mfg_nvs.bin
```

![image](https://github.com/espressif/esp-at/assets/142290531/885f975e-1308-407b-b58e-c3f061f119e6)

There is no "phy_init_data.bin" file in the [ESP32-C6-4MB-AT-V4.0.0.0.zip](https://dl.espressif.com/esp-at/firmwares/esp32c6/ESP32-C6-4MB-AT-V4.0.0.0.zip) firmware update.

Running the command without the "phy_init_data.bin 0x0" it works as a charm.

```bash
esptool.py --chip auto --port /dev/tty.usbserial-0001 --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size 4MB 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial.bin 0xf000  bootloader/bootloader.bin 0x60000 esp-at.bin 0x1e000 at_customize.bin 0x1f000 customized_partitions/mfg_nvs.bin
```

Would be nice to update the documentation.

Cheers,

**Comment by ustccw** [comment]
@blue-freedom-technologies thanks for your report! 
The document indeed needs to be updated. The `phy_init_data.bin` should be removed. This binary was previously used to store phy data separately, but now it's embedded within the application `esp-at.bin`.
