### ISSUE TITLE
Linux driver for ESP32 AT

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-at#809]
### Is your feature request related to a problem?

I would like use ESP32 as a wifi net device of Linux OS. Is it possible? hardware interface is not a concern, both SDIO and SPI are ok. Is there a Linux wireless driver for ESP32 AT?

**Comment by JAndrassy** [comment]
https://github.com/espressif/esp-hosted/tree/master/esp_hosted_ng

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
