### ISSUE TITLE
BLE broken pipe unrecoverable

### ISSUE THREAD

**Issue by mrx23dot** [espressif/esp-at#813]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

After first BLE connection failure with broken pipe it cannot connect to anything without a reboot.

So it's getting stuck.

```
AT+BLEINIT=1

# ensure not connected
AT+BLEDISCONN=0
ERROR

# connection fails 
AT+BLECONN=0,"73:f7:7c:18:70:b1",1,5
+BLESCANDONE
+BLECONN:0,-1
ERROR

# ensure not connected
AT+BLEDISCONN=0
ERROR

# connect to any other
AT+BLECONN=0,"5f:29:72:aa:82:c4",1,5
+BLESCANDONE
+BLECONN:0,-1
ERROR

# same error to any other addresses without reboot
```

It doesn't even seem to wait for timeout period, fails instantly.

Reboot solves the issue.
AT+BLEINIT=0 seems to simply reboot the system, which is slow.

```
AT+BLEINIT=0
ready
```

version
```
AT+GMR
AT+GMR
AT version:3.2.0.0(s-ec2dec2 - ESP32 - Jul 28 2023 07:05:28)
SDK version:v5.0.2-376-g24b9d38a24-dirty
compile time(6118fc22):Jul 28 2023 10:14:50
Bin version:v3.2.0.0(PICO-D4)
```

**Comment by ustccw** [comment]
@Luxin812 PTAL

**Comment by Luxin812** [comment]
> ### Answers checklist.
> * [x]  I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
> * [x]  I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
> * [x]  I have searched the issue tracker for a similar issue and not found a similar issue.
> 
> ### General issue report
> After first BLE connection failure with broken pipe it cannot connect to anything without a reboot.
> 
> So it's getting stuck.
> 
> ```
> AT+BLEINIT=1
> 
> # ensure not connected
> AT+BLEDISCONN=0
> ERROR
> 
> # connection fails 
> AT+BLECONN=0,"73:f7:7c:18:70:b1",1,5
> +BLESCANDONE
> +BLECONN:0,-1
> ERROR
> 
> # ensure not connected
> AT+BLEDISCONN=0
> ERROR
> 
> # connect to any other
> AT+BLECONN=0,"5f:29:72:aa:82:c4",1,5
> +BLESCANDONE
> +BLECONN:0,-1
> ERROR
> 
> # same error to any other addresses without reboot
> ```
> 
> It doesn't even seem to wait for timeout period, fails instantly.
> 
> Reboot solves the issue. AT+BLEINIT=0 seems to simply reboot the system, which is slow.
> 
> ```
> AT+BLEINIT=0
> ready
> ```
> 
> version
> 
> ```
> AT+GMR
> AT+GMR
> AT version:3.2.0.0(s-ec2dec2 - ESP32 - Jul 28 2023 07:05:28)
> SDK version:v5.0.2-376-g24b9d38a24-dirty
> compile time(6118fc22):Jul 28 2023 10:14:50
> Bin version:v3.2.0.0(PICO-D4)
> ```

Hi, this issue has been fixed. You can use [release v3.4.0.0](https://docs.espressif.com/projects/esp-at/zh_CN/latest/esp32/AT_Binary_Lists/esp_at_binaries.html) or the latest firmware on [the master branch](https://github.com/espressif/esp-at) to test it.

**Comment by ustccw** [comment]
We assume this worked for you, and will close it. If that's not the case, please open another github issue.
