### ISSUE TITLE
Unclear documentation ESP-AT flash process for modified bin

### ISSUE THREAD

**Issue by JavierReyes945** [espressif/esp-at#851]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am trying to understand the flash process of the ESP-AT firmware, specifically combined with a modification of parameters via the at.py tool. Details as follows:

I have successfully flashed the default firmware (v4.0.0 release) into my ESP32 C6 DevKit M1. For this, I have run the application (in Windows), using the procedure listed as "To download multiple bins separately to different addresses".

Q1: If one is flashing the default firmware, is the procedure with multiple bins correct? Why is there another procedure for "To download one combined factory bin"? What are the differences (from the user perspective)? When shall one or the other be used?

Now, we are evaluating to use a different UART baudrate for the AT interface. Based on the [official guide](https://docs.espressif.com/projects/esp-at/en/latest/esp32c6/Compile_and_Develop/tools_at_py.html#at-py-tool), we understand the change to the firmware shall be made with:

```
python at.py modify_bin --baud 921600 --input .\ESP32-C6-4MB-V4.0.0.0\factory\factory_ESP32C6-4MB.bin
```

Q2: Is it relevant for the at.py tool, from which location is the tool executed? The tool generates a folder `mfg_nvs` in current folder with a csv and a bin file, but also generated a target.bin file. Should the files in `mfg_nvs` be replaced into the corresponding ESP32-C6-4MB-V4.0.0.0 folder? Should the file target.bin be used at all?

Q3: After the modification for this specific parameter, shall the flash process be still the one for "download multiple bins separately to different addresses"? Does anything change in regard to addresses or sizes?

By inspecting the at.py tool help menu, there is an argument --output available.

Q4: If one runs the command below, where the output file is the same as the input, would this replace the files in folder `mvg_nvs`? Or should one run/generate outside and manually replace the files? If so, which files shall be replaced? What about the target.bin?

Thanks in advance for any clarification on this matter, as the guide is not particularly written for clarity (IMHO).

Kind regards

**Comment by ustccw** [comment]
@JavierReyes945 Hello!

## Q1
Both are right.
- [Download one combined factory bin](https://docs.espressif.com/projects/esp-at/en/latest/esp32/Get_Started/Downloading_guide.html#id6) is a easy way, but cost much time to download, normally used for develop stage. 
- [Download multiple bins](https://docs.espressif.com/projects/esp-at/en/latest/esp32/Get_Started/Downloading_guide.html#id7) is a time-save way to flash, but a little bit complex to choose each bin and click config, normally used for massive product stage.

btw, the command to change uart baud rate you mentioned, is right.

## Q2
You can use `at.py` anywhere.
- If you [Download one combined factory bin](https://docs.espressif.com/projects/esp-at/en/latest/esp32/Get_Started/Downloading_guide.html#id6), just use `target.bin` and ignore others.
- If you [Download multiple bins](https://docs.espressif.com/projects/esp-at/en/latest/esp32/Get_Started/Downloading_guide.html#id7), you should replace `customized_partitions/mfg_nvs.bin`  with new generated `mfg_nvs/mfg_nvs.bin`.

btw, the modified parameter configurations will have corresponding records in the `mfg_nvs.csv` file under the current `mfg_nvs` directory.

## Q3
Yes. The address and size of the binary is not changed.

## Q4
Yes. The output file will replace the input file, and all the files will be replaced if has same filename, but it's not the recommended way.

Thanks for your feedback! We should improve our document quality.
