### ISSUE TITLE
at.py gatt config argument parsing bug

### ISSUE THREAD

**Issue by benjaminaxiles** [espressif/esp-at#865]
### Answers checklist.

- [X] I have read the documentation [ESP-AT Programming Guide](https://docs.espressif.com/projects/esp-at/en/latest/) and the issue is not addressed there.
- [X] I have used the latest released firmware or have updated my ESP-AT branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Running
`
python3 at.py modify_bin  --gatts_cfg2 "0,16,0xC300,0x01,4,4,0000" --input <path_to_binary_file>
`
will modify line starting with cfg2, cfg20, cfg21, cfg22, cfg23, cfg24, cfg25, cfg26, cfg27, cfg28, cfg28, cfg29 of the _mfg_nvs.csv_ instead of line only cfg2 as expected.

This is because of the following function:

![image](https://github.com/user-attachments/assets/feb0abba-f643-4c37-9e9f-ff69976cc7ff)

At line 1040, when key is **cfg2**, the function `line.startswith(key)` matches with lines that start with cfg2, cfg20, cfg21, cfg22, cfg23, cfg24, cfg25, cfg26, cfg27, cfg28, cfg28, cfg29.

Replacing line 1040 with `if line.split(',')[0] == key and 'namespace' not in line:` fixes the bug.

**Comment by ustccw** [comment]
@benjaminaxiles thanks for your feedback and bugfix! You are absolutely right, will fix it soon.
