### ISSUE TITLE
GATT Service Bin Creation

### ISSUE THREAD

**Issue by mrbiondo** [espressif/esp-at#87]
Hello,
Is it possible to define more than one service with the procedure described in the toos folder?
If yes, can anyone explain how to do that?
Or, is there an alternative way to define and flash more than one service?
It seems that AT commands, like AT+BLEGATTSSRVSTART and AT+BLEGATTSSRVSTOP, can manage more than one service independently.
Thanks for any comment.

**Comment by xiewenxiang** [comment]
Hi ,
Only one service is currently supported.

**Comment by kurta999** [comment]
Any news on this issue? When it will be supported? Our company would need it, this ESP32 chip would be the best solution for us.

**Comment by xcguang** [comment]
Can you try commit b991a183bd6645340fc73a07cc964cfb3c5aae99?

**Comment by xiewenxiang** [comment]
This feature is supported, Please use the latest commit
